<?php

return [
    'kota' => [
        // ===== ACEH (23) =====
        ['slug' => 'aceh-barat', 'nama' => 'Aceh Barat', 'provinsi' => 'Aceh'],
        ['slug' => 'aceh-barat-daya', 'nama' => 'Aceh Barat Daya', 'provinsi' => 'Aceh'],
        ['slug' => 'aceh-besar', 'nama' => 'Aceh Besar', 'provinsi' => 'Aceh'],
        ['slug' => 'aceh-jaya', 'nama' => 'Aceh Jaya', 'provinsi' => 'Aceh'],
        ['slug' => 'aceh-selatan', 'nama' => 'Aceh Selatan', 'provinsi' => 'Aceh'],
        ['slug' => 'aceh-singkil', 'nama' => 'Aceh Singkil', 'provinsi' => 'Aceh'],
        ['slug' => 'aceh-tamiang', 'nama' => 'Aceh Tamiang', 'provinsi' => 'Aceh'],
        ['slug' => 'aceh-tengah', 'nama' => 'Aceh Tengah', 'provinsi' => 'Aceh'],
        ['slug' => 'aceh-tenggara', 'nama' => 'Aceh Tenggara', 'provinsi' => 'Aceh'],
        ['slug' => 'aceh-timur', 'nama' => 'Aceh Timur', 'provinsi' => 'Aceh'],
        ['slug' => 'aceh-utara', 'nama' => 'Aceh Utara', 'provinsi' => 'Aceh'],
        ['slug' => 'bener-meriah', 'nama' => 'Bener Meriah', 'provinsi' => 'Aceh'],
        ['slug' => 'bireuen', 'nama' => 'Bireuen', 'provinsi' => 'Aceh'],
        ['slug' => 'gayo-lues', 'nama' => 'Gayo Lues', 'provinsi' => 'Aceh'],
        ['slug' => 'nagan-raya', 'nama' => 'Nagan Raya', 'provinsi' => 'Aceh'],
        ['slug' => 'pidie', 'nama' => 'Pidie', 'provinsi' => 'Aceh'],
        ['slug' => 'pidie-jaya', 'nama' => 'Pidie Jaya', 'provinsi' => 'Aceh'],
        ['slug' => 'simeulue', 'nama' => 'Simeulue', 'provinsi' => 'Aceh'],
        ['slug' => 'banda-aceh', 'nama' => 'Banda Aceh', 'provinsi' => 'Aceh'],
        ['slug' => 'langsa', 'nama' => 'Langsa', 'provinsi' => 'Aceh'],
        ['slug' => 'lhokseumawe', 'nama' => 'Lhokseumawe', 'provinsi' => 'Aceh'],
        ['slug' => 'sabang', 'nama' => 'Sabang', 'provinsi' => 'Aceh'],
        ['slug' => 'subulussalam', 'nama' => 'Subulussalam', 'provinsi' => 'Aceh'],

        // ===== SUMATERA UTARA (33) =====
        ['slug' => 'asahan', 'nama' => 'Asahan', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'batu-bara', 'nama' => 'Batu Bara', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'dairi', 'nama' => 'Dairi', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'deli-serdang', 'nama' => 'Deli Serdang', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'humbang-hasundutan', 'nama' => 'Humbang Hasundutan', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'karo', 'nama' => 'Karo', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'labuhanbatu', 'nama' => 'Labuhanbatu', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'labuhanbatu-selatan', 'nama' => 'Labuhanbatu Selatan', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'labuhanbatu-utara', 'nama' => 'Labuhanbatu Utara', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'langkat', 'nama' => 'Langkat', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'mandailing-natal', 'nama' => 'Mandailing Natal', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'nias', 'nama' => 'Nias', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'nias-barat', 'nama' => 'Nias Barat', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'nias-selatan', 'nama' => 'Nias Selatan', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'nias-utara', 'nama' => 'Nias Utara', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'padang-lawas', 'nama' => 'Padang Lawas', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'padang-lawas-utara', 'nama' => 'Padang Lawas Utara', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'pakpak-bharat', 'nama' => 'Pakpak Bharat', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'samosir', 'nama' => 'Samosir', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'serdang-bedagai', 'nama' => 'Serdang Bedagai', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'simalungun', 'nama' => 'Simalungun', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'tapanuli-selatan', 'nama' => 'Tapanuli Selatan', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'tapanuli-tengah', 'nama' => 'Tapanuli Tengah', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'tapanuli-utara', 'nama' => 'Tapanuli Utara', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'toba', 'nama' => 'Toba', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'binjai', 'nama' => 'Binjai', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'gunungsitoli', 'nama' => 'Gunungsitoli', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'medan', 'nama' => 'Medan', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'padangsidimpuan', 'nama' => 'Padangsidimpuan', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'pematangsiantar', 'nama' => 'Pematangsiantar', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'sibolga', 'nama' => 'Sibolga', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'tanjungbalai', 'nama' => 'Tanjungbalai', 'provinsi' => 'Sumatera Utara'],
        ['slug' => 'tebing-tinggi', 'nama' => 'Tebing Tinggi', 'provinsi' => 'Sumatera Utara'],

        // ===== SUMATERA BARAT (19) =====
        ['slug' => 'agam', 'nama' => 'Agam', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'dharmasraya', 'nama' => 'Dharmasraya', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'kepulauan-mentawai', 'nama' => 'Kepulauan Mentawai', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'lima-puluh-kota', 'nama' => 'Lima Puluh Kota', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'padang-pariaman', 'nama' => 'Padang Pariaman', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'pasaman', 'nama' => 'Pasaman', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'pasaman-barat', 'nama' => 'Pasaman Barat', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'pesisir-selatan', 'nama' => 'Pesisir Selatan', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'sijunjung', 'nama' => 'Sijunjung', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'solok', 'nama' => 'Solok', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'solok-selatan', 'nama' => 'Solok Selatan', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'tanah-datar', 'nama' => 'Tanah Datar', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'bukittinggi', 'nama' => 'Bukittinggi', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'padang', 'nama' => 'Padang', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'padangpanjang', 'nama' => 'Padangpanjang', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'pariaman', 'nama' => 'Pariaman', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'payakumbuh', 'nama' => 'Payakumbuh', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'sawahlunto', 'nama' => 'Sawahlunto', 'provinsi' => 'Sumatera Barat'],
        ['slug' => 'kota-solok', 'nama' => 'Solok', 'provinsi' => 'Sumatera Barat'],

        // ===== RIAU (12) =====
        ['slug' => 'bengkalis', 'nama' => 'Bengkalis', 'provinsi' => 'Riau'],
        ['slug' => 'indragiri-hilir', 'nama' => 'Indragiri Hilir', 'provinsi' => 'Riau'],
        ['slug' => 'indragiri-hulu', 'nama' => 'Indragiri Hulu', 'provinsi' => 'Riau'],
        ['slug' => 'kampar', 'nama' => 'Kampar', 'provinsi' => 'Riau'],
        ['slug' => 'kepulauan-meranti', 'nama' => 'Kepulauan Meranti', 'provinsi' => 'Riau'],
        ['slug' => 'kuantan-singingi', 'nama' => 'Kuantan Singingi', 'provinsi' => 'Riau'],
        ['slug' => 'pelalawan', 'nama' => 'Pelalawan', 'provinsi' => 'Riau'],
        ['slug' => 'rokan-hilir', 'nama' => 'Rokan Hilir', 'provinsi' => 'Riau'],
        ['slug' => 'rokan-hulu', 'nama' => 'Rokan Hulu', 'provinsi' => 'Riau'],
        ['slug' => 'siak', 'nama' => 'Siak', 'provinsi' => 'Riau'],
        ['slug' => 'dumai', 'nama' => 'Dumai', 'provinsi' => 'Riau'],
        ['slug' => 'pekanbaru', 'nama' => 'Pekanbaru', 'provinsi' => 'Riau'],

        // ===== KEPULAUAN RIAU (7) =====
        ['slug' => 'bintan', 'nama' => 'Bintan', 'provinsi' => 'Kepulauan Riau'],
        ['slug' => 'karimun', 'nama' => 'Karimun', 'provinsi' => 'Kepulauan Riau'],
        ['slug' => 'kepulauan-anambas', 'nama' => 'Kepulauan Anambas', 'provinsi' => 'Kepulauan Riau'],
        ['slug' => 'lingga', 'nama' => 'Lingga', 'provinsi' => 'Kepulauan Riau'],
        ['slug' => 'natuna', 'nama' => 'Natuna', 'provinsi' => 'Kepulauan Riau'],
        ['slug' => 'batam', 'nama' => 'Batam', 'provinsi' => 'Kepulauan Riau'],
        ['slug' => 'tanjungpinang', 'nama' => 'Tanjungpinang', 'provinsi' => 'Kepulauan Riau'],

        // ===== JAMBI (11) =====
        ['slug' => 'batanghari', 'nama' => 'Batanghari', 'provinsi' => 'Jambi'],
        ['slug' => 'bungo', 'nama' => 'Bungo', 'provinsi' => 'Jambi'],
        ['slug' => 'kerinci', 'nama' => 'Kerinci', 'provinsi' => 'Jambi'],
        ['slug' => 'merangin', 'nama' => 'Merangin', 'provinsi' => 'Jambi'],
        ['slug' => 'muaro-jambi', 'nama' => 'Muaro Jambi', 'provinsi' => 'Jambi'],
        ['slug' => 'sarolangun', 'nama' => 'Sarolangun', 'provinsi' => 'Jambi'],
        ['slug' => 'tanjung-jabung-barat', 'nama' => 'Tanjung Jabung Barat', 'provinsi' => 'Jambi'],
        ['slug' => 'tanjung-jabung-timur', 'nama' => 'Tanjung Jabung Timur', 'provinsi' => 'Jambi'],
        ['slug' => 'tebo', 'nama' => 'Tebo', 'provinsi' => 'Jambi'],
        ['slug' => 'kota-jambi', 'nama' => 'Jambi', 'provinsi' => 'Jambi'],
        ['slug' => 'sungai-penuh', 'nama' => 'Sungai Penuh', 'provinsi' => 'Jambi'],

        // ===== SUMATERA SELATAN (17) =====
        ['slug' => 'banyuasin', 'nama' => 'Banyuasin', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'empat-lawang', 'nama' => 'Empat Lawang', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'lahat', 'nama' => 'Lahat', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'muara-enim', 'nama' => 'Muara Enim', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'musi-banyuasin', 'nama' => 'Musi Banyuasin', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'musi-rawas', 'nama' => 'Musi Rawas', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'musi-rawas-utara', 'nama' => 'Musi Rawas Utara', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'ogan-ilir', 'nama' => 'Ogan Ilir', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'ogan-komering-ilir', 'nama' => 'Ogan Komering Ilir', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'ogan-komering-ulu', 'nama' => 'Ogan Komering Ulu', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'ogan-komering-ulu-selatan', 'nama' => 'Ogan Komering Ulu Selatan', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'ogan-komering-ulu-timur', 'nama' => 'Ogan Komering Ulu Timur', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'penukal-abab-lematang-ilir', 'nama' => 'Penukal Abab Lematang Ilir', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'lubuklinggau', 'nama' => 'Lubuklinggau', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'pagar-alam', 'nama' => 'Pagar Alam', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'palembang', 'nama' => 'Palembang', 'provinsi' => 'Sumatera Selatan'],
        ['slug' => 'prabumulih', 'nama' => 'Prabumulih', 'provinsi' => 'Sumatera Selatan'],

        // ===== BANGKA BELITUNG (7) =====
        ['slug' => 'bangka', 'nama' => 'Bangka', 'provinsi' => 'Bangka Belitung'],
        ['slug' => 'bangka-barat', 'nama' => 'Bangka Barat', 'provinsi' => 'Bangka Belitung'],
        ['slug' => 'bangka-selatan', 'nama' => 'Bangka Selatan', 'provinsi' => 'Bangka Belitung'],
        ['slug' => 'bangka-tengah', 'nama' => 'Bangka Tengah', 'provinsi' => 'Bangka Belitung'],
        ['slug' => 'belitung', 'nama' => 'Belitung', 'provinsi' => 'Bangka Belitung'],
        ['slug' => 'belitung-timur', 'nama' => 'Belitung Timur', 'provinsi' => 'Bangka Belitung'],
        ['slug' => 'pangkalpinang', 'nama' => 'Pangkalpinang', 'provinsi' => 'Bangka Belitung'],

        // ===== BENGKULU (10) =====
        ['slug' => 'bengkulu-selatan', 'nama' => 'Bengkulu Selatan', 'provinsi' => 'Bengkulu'],
        ['slug' => 'bengkulu-tengah', 'nama' => 'Bengkulu Tengah', 'provinsi' => 'Bengkulu'],
        ['slug' => 'bengkulu-utara', 'nama' => 'Bengkulu Utara', 'provinsi' => 'Bengkulu'],
        ['slug' => 'kaur', 'nama' => 'Kaur', 'provinsi' => 'Bengkulu'],
        ['slug' => 'kepahiang', 'nama' => 'Kepahiang', 'provinsi' => 'Bengkulu'],
        ['slug' => 'lebong', 'nama' => 'Lebong', 'provinsi' => 'Bengkulu'],
        ['slug' => 'mukomuko', 'nama' => 'Mukomuko', 'provinsi' => 'Bengkulu'],
        ['slug' => 'rejang-lebong', 'nama' => 'Rejang Lebong', 'provinsi' => 'Bengkulu'],
        ['slug' => 'seluma', 'nama' => 'Seluma', 'provinsi' => 'Bengkulu'],
        ['slug' => 'bengkulu', 'nama' => 'Bengkulu', 'provinsi' => 'Bengkulu'],

        // ===== LAMPUNG (15) =====
        ['slug' => 'lampung-barat', 'nama' => 'Lampung Barat', 'provinsi' => 'Lampung'],
        ['slug' => 'lampung-selatan', 'nama' => 'Lampung Selatan', 'provinsi' => 'Lampung'],
        ['slug' => 'lampung-tengah', 'nama' => 'Lampung Tengah', 'provinsi' => 'Lampung'],
        ['slug' => 'lampung-timur', 'nama' => 'Lampung Timur', 'provinsi' => 'Lampung'],
        ['slug' => 'lampung-utara', 'nama' => 'Lampung Utara', 'provinsi' => 'Lampung'],
        ['slug' => 'mesuji', 'nama' => 'Mesuji', 'provinsi' => 'Lampung'],
        ['slug' => 'pesawaran', 'nama' => 'Pesawaran', 'provinsi' => 'Lampung'],
        ['slug' => 'pesisir-barat', 'nama' => 'Pesisir Barat', 'provinsi' => 'Lampung'],
        ['slug' => 'pringsewu', 'nama' => 'Pringsewu', 'provinsi' => 'Lampung'],
        ['slug' => 'tanggamus', 'nama' => 'Tanggamus', 'provinsi' => 'Lampung'],
        ['slug' => 'tulang-bawang', 'nama' => 'Tulang Bawang', 'provinsi' => 'Lampung'],
        ['slug' => 'tulang-bawang-barat', 'nama' => 'Tulang Bawang Barat', 'provinsi' => 'Lampung'],
        ['slug' => 'way-kanan', 'nama' => 'Way Kanan', 'provinsi' => 'Lampung'],
        ['slug' => 'bandar-lampung', 'nama' => 'Bandar Lampung', 'provinsi' => 'Lampung'],
        ['slug' => 'metro', 'nama' => 'Metro', 'provinsi' => 'Lampung'],

        // ===== BANTEN (8) =====
        ['slug' => 'lebak', 'nama' => 'Lebak', 'provinsi' => 'Banten'],
        ['slug' => 'pandeglang', 'nama' => 'Pandeglang', 'provinsi' => 'Banten'],
        ['slug' => 'serang', 'nama' => 'Serang', 'provinsi' => 'Banten'],
        ['slug' => 'tangerang', 'nama' => 'Tangerang', 'provinsi' => 'Banten'],
        ['slug' => 'cilegon', 'nama' => 'Cilegon', 'provinsi' => 'Banten'],
        ['slug' => 'kota-serang', 'nama' => 'Serang', 'provinsi' => 'Banten'],
        ['slug' => 'tangerang-selatan', 'nama' => 'Tangerang Selatan', 'provinsi' => 'Banten'],
        ['slug' => 'kota-tangerang', 'nama' => 'Tangerang', 'provinsi' => 'Banten'],

        // ===== JAWA BARAT (27) =====
        ['slug' => 'kabupaten-bandung', 'nama' => 'Bandung', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'bandung-barat', 'nama' => 'Bandung Barat', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'kabupaten-bekasi', 'nama' => 'Bekasi', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'kabupaten-bogor', 'nama' => 'Bogor', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'ciamis', 'nama' => 'Ciamis', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'cianjur', 'nama' => 'Cianjur', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'kabupaten-cirebon', 'nama' => 'Cirebon', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'garut', 'nama' => 'Garut', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'indramayu', 'nama' => 'Indramayu', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'karawang', 'nama' => 'Karawang', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'kuningan', 'nama' => 'Kuningan', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'majalengka', 'nama' => 'Majalengka', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'pangandaran', 'nama' => 'Pangandaran', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'purwakarta', 'nama' => 'Purwakarta', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'subang', 'nama' => 'Subang', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'kabupaten-sukabumi', 'nama' => 'Sukabumi', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'sumedang', 'nama' => 'Sumedang', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'kabupaten-tasikmalaya', 'nama' => 'Tasikmalaya', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'kota-bandung', 'nama' => 'Bandung', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'banjar', 'nama' => 'Banjar', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'kota-bekasi', 'nama' => 'Bekasi', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'kota-bogor', 'nama' => 'Bogor', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'cimahi', 'nama' => 'Cimahi', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'kota-cirebon', 'nama' => 'Cirebon', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'depok', 'nama' => 'Depok', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'kota-sukabumi', 'nama' => 'Sukabumi', 'provinsi' => 'Jawa Barat'],
        ['slug' => 'kota-tasikmalaya', 'nama' => 'Tasikmalaya', 'provinsi' => 'Jawa Barat'],

        // ===== DKI JAKARTA (6) =====
        ['slug' => 'kepulauan-seribu', 'nama' => 'Kepulauan Seribu', 'provinsi' => 'DKI Jakarta'],
        ['slug' => 'jakarta-barat', 'nama' => 'Jakarta Barat', 'provinsi' => 'DKI Jakarta'],
        ['slug' => 'jakarta-pusat', 'nama' => 'Jakarta Pusat', 'provinsi' => 'DKI Jakarta'],
        ['slug' => 'jakarta-selatan', 'nama' => 'Jakarta Selatan', 'provinsi' => 'DKI Jakarta'],
        ['slug' => 'jakarta-timur', 'nama' => 'Jakarta Timur', 'provinsi' => 'DKI Jakarta'],
        ['slug' => 'jakarta-utara', 'nama' => 'Jakarta Utara', 'provinsi' => 'DKI Jakarta'],

        // ===== JAWA TENGAH (35) =====
        ['slug' => 'banjarnegara', 'nama' => 'Banjarnegara', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'banyumas', 'nama' => 'Banyumas', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'batang', 'nama' => 'Batang', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'blora', 'nama' => 'Blora', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'boyolali', 'nama' => 'Boyolali', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'brebes', 'nama' => 'Brebes', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'cilacap', 'nama' => 'Cilacap', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'demak', 'nama' => 'Demak', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'grobogan', 'nama' => 'Grobogan', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'jepara', 'nama' => 'Jepara', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'karanganyar', 'nama' => 'Karanganyar', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'kebumen', 'nama' => 'Kebumen', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'kendal', 'nama' => 'Kendal', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'klaten', 'nama' => 'Klaten', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'kudus', 'nama' => 'Kudus', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'kabupaten-magelang', 'nama' => 'Magelang', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'pati', 'nama' => 'Pati', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'kabupaten-pekalongan', 'nama' => 'Pekalongan', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'pemalang', 'nama' => 'Pemalang', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'purbalingga', 'nama' => 'Purbalingga', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'purworejo', 'nama' => 'Purworejo', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'rembang', 'nama' => 'Rembang', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'kabupaten-semarang', 'nama' => 'Semarang', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'sragen', 'nama' => 'Sragen', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'sukoharjo', 'nama' => 'Sukoharjo', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'kabupaten-tegal', 'nama' => 'Tegal', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'temanggung', 'nama' => 'Temanggung', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'wonogiri', 'nama' => 'Wonogiri', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'wonosobo', 'nama' => 'Wonosobo', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'kota-magelang', 'nama' => 'Magelang', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'kota-pekalongan', 'nama' => 'Pekalongan', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'salatiga', 'nama' => 'Salatiga', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'kota-semarang', 'nama' => 'Semarang', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'surakarta', 'nama' => 'Surakarta', 'provinsi' => 'Jawa Tengah'],
        ['slug' => 'kota-tegal', 'nama' => 'Tegal', 'provinsi' => 'Jawa Tengah'],

        // ===== DI YOGYAKARTA (5) =====
        ['slug' => 'bantul', 'nama' => 'Bantul', 'provinsi' => 'DI Yogyakarta'],
        ['slug' => 'gunungkidul', 'nama' => 'Gunungkidul', 'provinsi' => 'DI Yogyakarta'],
        ['slug' => 'kulon-progo', 'nama' => 'Kulon Progo', 'provinsi' => 'DI Yogyakarta'],
        ['slug' => 'sleman', 'nama' => 'Sleman', 'provinsi' => 'DI Yogyakarta'],
        ['slug' => 'yogyakarta', 'nama' => 'Yogyakarta', 'provinsi' => 'DI Yogyakarta'],

        // ===== JAWA TIMUR (38) =====
        ['slug' => 'bangkalan', 'nama' => 'Bangkalan', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'banyuwangi', 'nama' => 'Banyuwangi', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kabupaten-blitar', 'nama' => 'Blitar', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'bojonegoro', 'nama' => 'Bojonegoro', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'bondowoso', 'nama' => 'Bondowoso', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'gresik', 'nama' => 'Gresik', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'jember', 'nama' => 'Jember', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'jombang', 'nama' => 'Jombang', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kabupaten-kediri', 'nama' => 'Kediri', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'lamongan', 'nama' => 'Lamongan', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'lumajang', 'nama' => 'Lumajang', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kabupaten-madiun', 'nama' => 'Madiun', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'magetan', 'nama' => 'Magetan', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kabupaten-malang', 'nama' => 'Malang', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kabupaten-mojokerto', 'nama' => 'Mojokerto', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'nganjuk', 'nama' => 'Nganjuk', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'ngawi', 'nama' => 'Ngawi', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'pacitan', 'nama' => 'Pacitan', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'pamekasan', 'nama' => 'Pamekasan', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kabupaten-pasuruan', 'nama' => 'Pasuruan', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'ponorogo', 'nama' => 'Ponorogo', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kabupaten-probolinggo', 'nama' => 'Probolinggo', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'sampang', 'nama' => 'Sampang', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'sidoarjo', 'nama' => 'Sidoarjo', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'situbondo', 'nama' => 'Situbondo', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'sumenep', 'nama' => 'Sumenep', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'trenggalek', 'nama' => 'Trenggalek', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'tuban', 'nama' => 'Tuban', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'tulungagung', 'nama' => 'Tulungagung', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'batu', 'nama' => 'Batu', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kota-blitar', 'nama' => 'Blitar', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kota-kediri', 'nama' => 'Kediri', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kota-madiun', 'nama' => 'Madiun', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kota-malang', 'nama' => 'Malang', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kota-mojokerto', 'nama' => 'Mojokerto', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kota-pasuruan', 'nama' => 'Pasuruan', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'kota-probolinggo', 'nama' => 'Probolinggo', 'provinsi' => 'Jawa Timur'],
        ['slug' => 'surabaya', 'nama' => 'Surabaya', 'provinsi' => 'Jawa Timur'],

        // ===== BALI (9) =====
        ['slug' => 'badung', 'nama' => 'Badung', 'provinsi' => 'Bali'],
        ['slug' => 'bangli', 'nama' => 'Bangli', 'provinsi' => 'Bali'],
        ['slug' => 'buleleng', 'nama' => 'Buleleng', 'provinsi' => 'Bali'],
        ['slug' => 'gianyar', 'nama' => 'Gianyar', 'provinsi' => 'Bali'],
        ['slug' => 'jembrana', 'nama' => 'Jembrana', 'provinsi' => 'Bali'],
        ['slug' => 'karangasem', 'nama' => 'Karangasem', 'provinsi' => 'Bali'],
        ['slug' => 'klungkung', 'nama' => 'Klungkung', 'provinsi' => 'Bali'],
        ['slug' => 'tabanan', 'nama' => 'Tabanan', 'provinsi' => 'Bali'],
        ['slug' => 'denpasar', 'nama' => 'Denpasar', 'provinsi' => 'Bali'],

        // ===== NUSA TENGGARA BARAT (10) =====
        ['slug' => 'kabupaten-bima', 'nama' => 'Bima', 'provinsi' => 'Nusa Tenggara Barat'],
        ['slug' => 'dompu', 'nama' => 'Dompu', 'provinsi' => 'Nusa Tenggara Barat'],
        ['slug' => 'lombok-barat', 'nama' => 'Lombok Barat', 'provinsi' => 'Nusa Tenggara Barat'],
        ['slug' => 'lombok-tengah', 'nama' => 'Lombok Tengah', 'provinsi' => 'Nusa Tenggara Barat'],
        ['slug' => 'lombok-timur', 'nama' => 'Lombok Timur', 'provinsi' => 'Nusa Tenggara Barat'],
        ['slug' => 'lombok-utara', 'nama' => 'Lombok Utara', 'provinsi' => 'Nusa Tenggara Barat'],
        ['slug' => 'sumbawa', 'nama' => 'Sumbawa', 'provinsi' => 'Nusa Tenggara Barat'],
        ['slug' => 'sumbawa-barat', 'nama' => 'Sumbawa Barat', 'provinsi' => 'Nusa Tenggara Barat'],
        ['slug' => 'kota-bima', 'nama' => 'Bima', 'provinsi' => 'Nusa Tenggara Barat'],
        ['slug' => 'mataram', 'nama' => 'Mataram', 'provinsi' => 'Nusa Tenggara Barat'],

        // ===== NUSA TENGGARA TIMUR (22) =====
        ['slug' => 'alor', 'nama' => 'Alor', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'belu', 'nama' => 'Belu', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'ende', 'nama' => 'Ende', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'flores-timur', 'nama' => 'Flores Timur', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'kabupaten-kupang', 'nama' => 'Kupang', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'lembata', 'nama' => 'Lembata', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'malaka', 'nama' => 'Malaka', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'manggarai', 'nama' => 'Manggarai', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'manggarai-barat', 'nama' => 'Manggarai Barat', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'manggarai-timur', 'nama' => 'Manggarai Timur', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'nagekeo', 'nama' => 'Nagekeo', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'ngada', 'nama' => 'Ngada', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'rote-ndao', 'nama' => 'Rote Ndao', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'sabu-raijua', 'nama' => 'Sabu Raijua', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'sikka', 'nama' => 'Sikka', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'sumba-barat', 'nama' => 'Sumba Barat', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'sumba-barat-daya', 'nama' => 'Sumba Barat Daya', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'sumba-tengah', 'nama' => 'Sumba Tengah', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'sumba-timur', 'nama' => 'Sumba Timur', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'timor-tengah-selatan', 'nama' => 'Timor Tengah Selatan', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'timor-tengah-utara', 'nama' => 'Timor Tengah Utara', 'provinsi' => 'Nusa Tenggara Timur'],
        ['slug' => 'kota-kupang', 'nama' => 'Kupang', 'provinsi' => 'Nusa Tenggara Timur'],

        // ===== KALIMANTAN BARAT (14) =====
        ['slug' => 'bengkayang', 'nama' => 'Bengkayang', 'provinsi' => 'Kalimantan Barat'],
        ['slug' => 'kapuas-hulu', 'nama' => 'Kapuas Hulu', 'provinsi' => 'Kalimantan Barat'],
        ['slug' => 'kayong-utara', 'nama' => 'Kayong Utara', 'provinsi' => 'Kalimantan Barat'],
        ['slug' => 'ketapang', 'nama' => 'Ketapang', 'provinsi' => 'Kalimantan Barat'],
        ['slug' => 'kubu-raya', 'nama' => 'Kubu Raya', 'provinsi' => 'Kalimantan Barat'],
        ['slug' => 'landak', 'nama' => 'Landak', 'provinsi' => 'Kalimantan Barat'],
        ['slug' => 'melawi', 'nama' => 'Melawi', 'provinsi' => 'Kalimantan Barat'],
        ['slug' => 'mempawah', 'nama' => 'Mempawah', 'provinsi' => 'Kalimantan Barat'],
        ['slug' => 'sambas', 'nama' => 'Sambas', 'provinsi' => 'Kalimantan Barat'],
        ['slug' => 'sanggau', 'nama' => 'Sanggau', 'provinsi' => 'Kalimantan Barat'],
        ['slug' => 'sekadau', 'nama' => 'Sekadau', 'provinsi' => 'Kalimantan Barat'],
        ['slug' => 'sintang', 'nama' => 'Sintang', 'provinsi' => 'Kalimantan Barat'],
        ['slug' => 'pontianak', 'nama' => 'Pontianak', 'provinsi' => 'Kalimantan Barat'],
        ['slug' => 'singkawang', 'nama' => 'Singkawang', 'provinsi' => 'Kalimantan Barat'],

        // ===== KALIMANTAN SELATAN (13) =====
        ['slug' => 'balangan', 'nama' => 'Balangan', 'provinsi' => 'Kalimantan Selatan'],
        ['slug' => 'banjar', 'nama' => 'Banjar', 'provinsi' => 'Kalimantan Selatan'],
        ['slug' => 'barito-kuala', 'nama' => 'Barito Kuala', 'provinsi' => 'Kalimantan Selatan'],
        ['slug' => 'hulu-sungai-selatan', 'nama' => 'Hulu Sungai Selatan', 'provinsi' => 'Kalimantan Selatan'],
        ['slug' => 'hulu-sungai-tengah', 'nama' => 'Hulu Sungai Tengah', 'provinsi' => 'Kalimantan Selatan'],
        ['slug' => 'hulu-sungai-utara', 'nama' => 'Hulu Sungai Utara', 'provinsi' => 'Kalimantan Selatan'],
        ['slug' => 'kotabaru', 'nama' => 'Kotabaru', 'provinsi' => 'Kalimantan Selatan'],
        ['slug' => 'tabalong', 'nama' => 'Tabalong', 'provinsi' => 'Kalimantan Selatan'],
        ['slug' => 'tanah-bumbu', 'nama' => 'Tanah Bumbu', 'provinsi' => 'Kalimantan Selatan'],
        ['slug' => 'tanah-laut', 'nama' => 'Tanah Laut', 'provinsi' => 'Kalimantan Selatan'],
        ['slug' => 'tapin', 'nama' => 'Tapin', 'provinsi' => 'Kalimantan Selatan'],
        ['slug' => 'banjarbaru', 'nama' => 'Banjarbaru', 'provinsi' => 'Kalimantan Selatan'],
        ['slug' => 'banjarmasin', 'nama' => 'Banjarmasin', 'provinsi' => 'Kalimantan Selatan'],

        // ===== KALIMANTAN TENGAH (14) =====
        ['slug' => 'barito-selatan', 'nama' => 'Barito Selatan', 'provinsi' => 'Kalimantan Tengah'],
        ['slug' => 'barito-timur', 'nama' => 'Barito Timur', 'provinsi' => 'Kalimantan Tengah'],
        ['slug' => 'barito-utara', 'nama' => 'Barito Utara', 'provinsi' => 'Kalimantan Tengah'],
        ['slug' => 'gunung-mas', 'nama' => 'Gunung Mas', 'provinsi' => 'Kalimantan Tengah'],
        ['slug' => 'kapuas', 'nama' => 'Kapuas', 'provinsi' => 'Kalimantan Tengah'],
        ['slug' => 'katingan', 'nama' => 'Katingan', 'provinsi' => 'Kalimantan Tengah'],
        ['slug' => 'kotawaringin-barat', 'nama' => 'Kotawaringin Barat', 'provinsi' => 'Kalimantan Tengah'],
        ['slug' => 'kotawaringin-timur', 'nama' => 'Kotawaringin Timur', 'provinsi' => 'Kalimantan Tengah'],
        ['slug' => 'lamandau', 'nama' => 'Lamandau', 'provinsi' => 'Kalimantan Tengah'],
        ['slug' => 'murung-raya', 'nama' => 'Murung Raya', 'provinsi' => 'Kalimantan Tengah'],
        ['slug' => 'pulang-pisau', 'nama' => 'Pulang Pisau', 'provinsi' => 'Kalimantan Tengah'],
        ['slug' => 'seruyan', 'nama' => 'Seruyan', 'provinsi' => 'Kalimantan Tengah'],
        ['slug' => 'sukamara', 'nama' => 'Sukamara', 'provinsi' => 'Kalimantan Tengah'],
        ['slug' => 'palangka-raya', 'nama' => 'Palangka Raya', 'provinsi' => 'Kalimantan Tengah'],

        // ===== KALIMANTAN TIMUR (10) =====
        ['slug' => 'berau', 'nama' => 'Berau', 'provinsi' => 'Kalimantan Timur'],
        ['slug' => 'kutai-barat', 'nama' => 'Kutai Barat', 'provinsi' => 'Kalimantan Timur'],
        ['slug' => 'kutai-kartanegara', 'nama' => 'Kutai Kartanegara', 'provinsi' => 'Kalimantan Timur'],
        ['slug' => 'kutai-timur', 'nama' => 'Kutai Timur', 'provinsi' => 'Kalimantan Timur'],
        ['slug' => 'mahakam-ulu', 'nama' => 'Mahakam Ulu', 'provinsi' => 'Kalimantan Timur'],
        ['slug' => 'paser', 'nama' => 'Paser', 'provinsi' => 'Kalimantan Timur'],
        ['slug' => 'penajam-paser-utara', 'nama' => 'Penajam Paser Utara', 'provinsi' => 'Kalimantan Timur'],
        ['slug' => 'balikpapan', 'nama' => 'Balikpapan', 'provinsi' => 'Kalimantan Timur'],
        ['slug' => 'bontang', 'nama' => 'Bontang', 'provinsi' => 'Kalimantan Timur'],
        ['slug' => 'samarinda', 'nama' => 'Samarinda', 'provinsi' => 'Kalimantan Timur'],

        // ===== KALIMANTAN UTARA (5) =====
        ['slug' => 'bulungan', 'nama' => 'Bulungan', 'provinsi' => 'Kalimantan Utara'],
        ['slug' => 'malinau', 'nama' => 'Malinau', 'provinsi' => 'Kalimantan Utara'],
        ['slug' => 'nunukan', 'nama' => 'Nunukan', 'provinsi' => 'Kalimantan Utara'],
        ['slug' => 'tana-tidung', 'nama' => 'Tana Tidung', 'provinsi' => 'Kalimantan Utara'],
        ['slug' => 'tarakan', 'nama' => 'Tarakan', 'provinsi' => 'Kalimantan Utara'],

        // ===== SULAWESI UTARA (15) =====
        ['slug' => 'bolaang-mongondow', 'nama' => 'Bolaang Mongondow', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'bolaang-mongondow-selatan', 'nama' => 'Bolaang Mongondow Selatan', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'bolaang-mongondow-timur', 'nama' => 'Bolaang Mongondow Timur', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'bolaang-mongondow-utara', 'nama' => 'Bolaang Mongondow Utara', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'kepulauan-sangihe', 'nama' => 'Kepulauan Sangihe', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'kepulauan-siau-tagulandang-biaro', 'nama' => 'Kepulauan Siau Tagulandang Biaro', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'kepulauan-talaud', 'nama' => 'Kepulauan Talaud', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'minahasa', 'nama' => 'Minahasa', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'minahasa-selatan', 'nama' => 'Minahasa Selatan', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'minahasa-tenggara', 'nama' => 'Minahasa Tenggara', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'minahasa-utara', 'nama' => 'Minahasa Utara', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'bitung', 'nama' => 'Bitung', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'kotamobagu', 'nama' => 'Kotamobagu', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'manado', 'nama' => 'Manado', 'provinsi' => 'Sulawesi Utara'],
        ['slug' => 'tomohon', 'nama' => 'Tomohon', 'provinsi' => 'Sulawesi Utara'],

        // ===== GORONTALO (6) =====
        ['slug' => 'boalemo', 'nama' => 'Boalemo', 'provinsi' => 'Gorontalo'],
        ['slug' => 'bone-bolango', 'nama' => 'Bone Bolango', 'provinsi' => 'Gorontalo'],
        ['slug' => 'kabupaten-gorontalo', 'nama' => 'Gorontalo', 'provinsi' => 'Gorontalo'],
        ['slug' => 'gorontalo-utara', 'nama' => 'Gorontalo Utara', 'provinsi' => 'Gorontalo'],
        ['slug' => 'pohuwato', 'nama' => 'Pohuwato', 'provinsi' => 'Gorontalo'],
        ['slug' => 'kota-gorontalo', 'nama' => 'Gorontalo', 'provinsi' => 'Gorontalo'],

        // ===== SULAWESI TENGAH (13) =====
        ['slug' => 'banggai', 'nama' => 'Banggai', 'provinsi' => 'Sulawesi Tengah'],
        ['slug' => 'banggai-kepulauan', 'nama' => 'Banggai Kepulauan', 'provinsi' => 'Sulawesi Tengah'],
        ['slug' => 'banggai-laut', 'nama' => 'Banggai Laut', 'provinsi' => 'Sulawesi Tengah'],
        ['slug' => 'buol', 'nama' => 'Buol', 'provinsi' => 'Sulawesi Tengah'],
        ['slug' => 'donggala', 'nama' => 'Donggala', 'provinsi' => 'Sulawesi Tengah'],
        ['slug' => 'morowali', 'nama' => 'Morowali', 'provinsi' => 'Sulawesi Tengah'],
        ['slug' => 'morowali-utara', 'nama' => 'Morowali Utara', 'provinsi' => 'Sulawesi Tengah'],
        ['slug' => 'parigi-moutong', 'nama' => 'Parigi Moutong', 'provinsi' => 'Sulawesi Tengah'],
        ['slug' => 'poso', 'nama' => 'Poso', 'provinsi' => 'Sulawesi Tengah'],
        ['slug' => 'sigi', 'nama' => 'Sigi', 'provinsi' => 'Sulawesi Tengah'],
        ['slug' => 'tojo-una-una', 'nama' => 'Tojo Una-Una', 'provinsi' => 'Sulawesi Tengah'],
        ['slug' => 'tolitoli', 'nama' => 'Tolitoli', 'provinsi' => 'Sulawesi Tengah'],
        ['slug' => 'palu', 'nama' => 'Palu', 'provinsi' => 'Sulawesi Tengah'],

        // ===== SULAWESI BARAT (6) =====
        ['slug' => 'majene', 'nama' => 'Majene', 'provinsi' => 'Sulawesi Barat'],
        ['slug' => 'mamasa', 'nama' => 'Mamasa', 'provinsi' => 'Sulawesi Barat'],
        ['slug' => 'mamuju', 'nama' => 'Mamuju', 'provinsi' => 'Sulawesi Barat'],
        ['slug' => 'mamuju-tengah', 'nama' => 'Mamuju Tengah', 'provinsi' => 'Sulawesi Barat'],
        ['slug' => 'pasangkayu', 'nama' => 'Pasangkayu', 'provinsi' => 'Sulawesi Barat'],
        ['slug' => 'polewali-mandar', 'nama' => 'Polewali Mandar', 'provinsi' => 'Sulawesi Barat'],

        // ===== SULAWESI SELATAN (24) =====
        ['slug' => 'bantaeng', 'nama' => 'Bantaeng', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'barru', 'nama' => 'Barru', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'bone', 'nama' => 'Bone', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'bulukumba', 'nama' => 'Bulukumba', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'enrekang', 'nama' => 'Enrekang', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'gowa', 'nama' => 'Gowa', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'jeneponto', 'nama' => 'Jeneponto', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'kepulauan-selayar', 'nama' => 'Kepulauan Selayar', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'luwu', 'nama' => 'Luwu', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'luwu-timur', 'nama' => 'Luwu Timur', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'luwu-utara', 'nama' => 'Luwu Utara', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'maros', 'nama' => 'Maros', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'pangkajene-dan-kepulauan', 'nama' => 'Pangkajene dan Kepulauan', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'pinrang', 'nama' => 'Pinrang', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'sidenreng-rappang', 'nama' => 'Sidenreng Rappang', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'sinjai', 'nama' => 'Sinjai', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'soppeng', 'nama' => 'Soppeng', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'takalar', 'nama' => 'Takalar', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'tana-toraja', 'nama' => 'Tana Toraja', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'toraja-utara', 'nama' => 'Toraja Utara', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'wajo', 'nama' => 'Wajo', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'makassar', 'nama' => 'Makassar', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'palopo', 'nama' => 'Palopo', 'provinsi' => 'Sulawesi Selatan'],
        ['slug' => 'parepare', 'nama' => 'Parepare', 'provinsi' => 'Sulawesi Selatan'],

        // ===== SULAWESI TENGGARA (17) =====
        ['slug' => 'bombana', 'nama' => 'Bombana', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'buton', 'nama' => 'Buton', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'buton-selatan', 'nama' => 'Buton Selatan', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'buton-tengah', 'nama' => 'Buton Tengah', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'buton-utara', 'nama' => 'Buton Utara', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'kolaka', 'nama' => 'Kolaka', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'kolaka-timur', 'nama' => 'Kolaka Timur', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'kolaka-utara', 'nama' => 'Kolaka Utara', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'konawe', 'nama' => 'Konawe', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'konawe-kepulauan', 'nama' => 'Konawe Kepulauan', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'konawe-selatan', 'nama' => 'Konawe Selatan', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'konawe-utara', 'nama' => 'Konawe Utara', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'muna', 'nama' => 'Muna', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'muna-barat', 'nama' => 'Muna Barat', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'wakatobi', 'nama' => 'Wakatobi', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'bau-bau', 'nama' => 'Bau-Bau', 'provinsi' => 'Sulawesi Tenggara'],
        ['slug' => 'kendari', 'nama' => 'Kendari', 'provinsi' => 'Sulawesi Tenggara'],

        // ===== MALUKU (11) =====
        ['slug' => 'buru', 'nama' => 'Buru', 'provinsi' => 'Maluku'],
        ['slug' => 'buru-selatan', 'nama' => 'Buru Selatan', 'provinsi' => 'Maluku'],
        ['slug' => 'kepulauan-aru', 'nama' => 'Kepulauan Aru', 'provinsi' => 'Maluku'],
        ['slug' => 'kepulauan-tanimbar', 'nama' => 'Kepulauan Tanimbar', 'provinsi' => 'Maluku'],
        ['slug' => 'maluku-barat-daya', 'nama' => 'Maluku Barat Daya', 'provinsi' => 'Maluku'],
        ['slug' => 'maluku-tengah', 'nama' => 'Maluku Tengah', 'provinsi' => 'Maluku'],
        ['slug' => 'maluku-tenggara', 'nama' => 'Maluku Tenggara', 'provinsi' => 'Maluku'],
        ['slug' => 'seram-bagian-barat', 'nama' => 'Seram Bagian Barat', 'provinsi' => 'Maluku'],
        ['slug' => 'seram-bagian-timur', 'nama' => 'Seram Bagian Timur', 'provinsi' => 'Maluku'],
        ['slug' => 'ambon', 'nama' => 'Ambon', 'provinsi' => 'Maluku'],
        ['slug' => 'tual', 'nama' => 'Tual', 'provinsi' => 'Maluku'],

        // ===== MALUKU UTARA (10) =====
        ['slug' => 'halmahera-barat', 'nama' => 'Halmahera Barat', 'provinsi' => 'Maluku Utara'],
        ['slug' => 'halmahera-selatan', 'nama' => 'Halmahera Selatan', 'provinsi' => 'Maluku Utara'],
        ['slug' => 'halmahera-tengah', 'nama' => 'Halmahera Tengah', 'provinsi' => 'Maluku Utara'],
        ['slug' => 'halmahera-timur', 'nama' => 'Halmahera Timur', 'provinsi' => 'Maluku Utara'],
        ['slug' => 'halmahera-utara', 'nama' => 'Halmahera Utara', 'provinsi' => 'Maluku Utara'],
        ['slug' => 'kepulauan-sula', 'nama' => 'Kepulauan Sula', 'provinsi' => 'Maluku Utara'],
        ['slug' => 'pulau-morotai', 'nama' => 'Pulau Morotai', 'provinsi' => 'Maluku Utara'],
        ['slug' => 'pulau-taliabu', 'nama' => 'Pulau Taliabu', 'provinsi' => 'Maluku Utara'],
        ['slug' => 'ternate', 'nama' => 'Ternate', 'provinsi' => 'Maluku Utara'],
        ['slug' => 'tidore-kepulauan', 'nama' => 'Tidore Kepulauan', 'provinsi' => 'Maluku Utara'],

        // ===== PAPUA (29) =====
        ['slug' => 'asmat', 'nama' => 'Asmat', 'provinsi' => 'Papua'],
        ['slug' => 'biak-numfor', 'nama' => 'Biak Numfor', 'provinsi' => 'Papua'],
        ['slug' => 'boven-digoel', 'nama' => 'Boven Digoel', 'provinsi' => 'Papua'],
        ['slug' => 'deiyai', 'nama' => 'Deiyai', 'provinsi' => 'Papua'],
        ['slug' => 'dogiyai', 'nama' => 'Dogiyai', 'provinsi' => 'Papua'],
        ['slug' => 'intan-jaya', 'nama' => 'Intan Jaya', 'provinsi' => 'Papua'],
        ['slug' => 'kabupaten-jayapura', 'nama' => 'Jayapura', 'provinsi' => 'Papua'],
        ['slug' => 'jayawijaya', 'nama' => 'Jayawijaya', 'provinsi' => 'Papua'],
        ['slug' => 'keerom', 'nama' => 'Keerom', 'provinsi' => 'Papua'],
        ['slug' => 'kepulauan-yapen', 'nama' => 'Kepulauan Yapen', 'provinsi' => 'Papua'],
        ['slug' => 'lanny-jaya', 'nama' => 'Lanny Jaya', 'provinsi' => 'Papua'],
        ['slug' => 'mamberamo-raya', 'nama' => 'Mamberamo Raya', 'provinsi' => 'Papua'],
        ['slug' => 'mamberamo-tengah', 'nama' => 'Mamberamo Tengah', 'provinsi' => 'Papua'],
        ['slug' => 'mappi', 'nama' => 'Mappi', 'provinsi' => 'Papua'],
        ['slug' => 'merauke', 'nama' => 'Merauke', 'provinsi' => 'Papua'],
        ['slug' => 'mimika', 'nama' => 'Mimika', 'provinsi' => 'Papua'],
        ['slug' => 'nabire', 'nama' => 'Nabire', 'provinsi' => 'Papua'],
        ['slug' => 'nduga', 'nama' => 'Nduga', 'provinsi' => 'Papua'],
        ['slug' => 'paniai', 'nama' => 'Paniai', 'provinsi' => 'Papua'],
        ['slug' => 'pegunungan-bintang', 'nama' => 'Pegunungan Bintang', 'provinsi' => 'Papua'],
        ['slug' => 'puncak', 'nama' => 'Puncak', 'provinsi' => 'Papua'],
        ['slug' => 'puncak-jaya', 'nama' => 'Puncak Jaya', 'provinsi' => 'Papua'],
        ['slug' => 'sarmi', 'nama' => 'Sarmi', 'provinsi' => 'Papua'],
        ['slug' => 'supiori', 'nama' => 'Supiori', 'provinsi' => 'Papua'],
        ['slug' => 'tolikara', 'nama' => 'Tolikara', 'provinsi' => 'Papua'],
        ['slug' => 'waropen', 'nama' => 'Waropen', 'provinsi' => 'Papua'],
        ['slug' => 'yahukimo', 'nama' => 'Yahukimo', 'provinsi' => 'Papua'],
        ['slug' => 'yalimo', 'nama' => 'Yalimo', 'provinsi' => 'Papua'],
        ['slug' => 'kota-jayapura', 'nama' => 'Jayapura', 'provinsi' => 'Papua'],

        // ===== PAPUA BARAT (7) =====
        ['slug' => 'fakfak', 'nama' => 'Fakfak', 'provinsi' => 'Papua Barat'],
        ['slug' => 'kaimana', 'nama' => 'Kaimana', 'provinsi' => 'Papua Barat'],
        ['slug' => 'manokwari', 'nama' => 'Manokwari', 'provinsi' => 'Papua Barat'],
        ['slug' => 'manokwari-selatan', 'nama' => 'Manokwari Selatan', 'provinsi' => 'Papua Barat'],
        ['slug' => 'pegunungan-arfak', 'nama' => 'Pegunungan Arfak', 'provinsi' => 'Papua Barat'],
        ['slug' => 'teluk-bintuni', 'nama' => 'Teluk Bintuni', 'provinsi' => 'Papua Barat'],
        ['slug' => 'teluk-wondama', 'nama' => 'Teluk Wondama', 'provinsi' => 'Papua Barat'],

        // ===== PAPUA BARAT DAYA (6) =====
        ['slug' => 'maybrat', 'nama' => 'Maybrat', 'provinsi' => 'Papua Barat Daya'],
        ['slug' => 'raja-ampat', 'nama' => 'Raja Ampat', 'provinsi' => 'Papua Barat Daya'],
        ['slug' => 'kabupaten-sorong', 'nama' => 'Sorong', 'provinsi' => 'Papua Barat Daya'],
        ['slug' => 'sorong-selatan', 'nama' => 'Sorong Selatan', 'provinsi' => 'Papua Barat Daya'],
        ['slug' => 'tambrauw', 'nama' => 'Tambrauw', 'provinsi' => 'Papua Barat Daya'],
        ['slug' => 'kota-sorong', 'nama' => 'Sorong', 'provinsi' => 'Papua Barat Daya'],
    ],
];
