<?php
function add($f, $entries, $prov) {
    $o = '';
    foreach ($entries as $e) {
        $p = explode('|', $e);
        $k = trim($p[0]); $n = trim($p[1]);
        $s = strtolower(str_replace(' ', '-', $n));
        $s = str_replace(["'", '/', '(', ')', '.'], '', $s);
        $s = str_replace('--', '-', $s); $s = trim($s, '-');
        $ne = str_replace("'", "\'", $n);
        $o .= "        ['slug' => '{$s}', 'nama' => '{$ne}', 'kota' => '{$k}', 'provinsi' => '{$prov}'],\n";
    }
    file_put_contents($f, $o, FILE_APPEND);
}
$f = __DIR__ . '/../config/pseo-kecamatan.php';

// JAWA BARAT (27 kab/kota, ~627 kecamatan)
add($f, [
'Bandung|Arjasari','Bandung|Baleendah','Bandung|Banjaran','Bandung|Bojongsoang','Bandung|Cangkuang',
'Bandung|Cicalengka','Bandung|Cikancung','Bandung|Cilengkrang','Bandung|Cileunyi','Bandung|Cimaung',
'Bandung|Cimenyan','Bandung|Ciparay','Bandung|Ciwidey','Bandung|Dayeuhkolot','Bandung|Ibun','Bandung|Katapang',
'Bandung|Kertasari','Bandung|Kutawaringin','Bandung|Majalaya','Bandung|Margaasih','Bandung|Margahayu',
'Bandung|Nagreg','Bandung|Pacet','Bandung|Pameungpeuk','Bandung|Pangalengan','Bandung|Paseh','Bandung|Pasirjambu',
'Bandung|Ranca Bali','Bandung|Rancaekek','Bandung|Solokan Jeruk','Bandung|Soreang',
'Bandung Barat|Batujajar','Bandung Barat|Cihampelas','Bandung Barat|Cikalong Wetan','Bandung Barat|Cililin',
'Bandung Barat|Cipatat','Bandung Barat|Cipeundeuy','Bandung Barat|Cipongkor','Bandung Barat|Gununghalu',
'Bandung Barat|Lembang','Bandung Barat|Ngamprah','Bandung Barat|Padalarang','Bandung Barat|Parongpong',
'Bandung Barat|Rongga','Bandung Barat|Saguling','Bandung Barat|Sindangkerta',
'Bekasi|Babelan','Bekasi|Bojongmangu','Bekasi|Cabangbungin','Bekasi|Cibarusah','Bekasi|Cibitung','Bekasi|Cikarang Barat',
'Bekasi|Cikarang Pusat','Bekasi|Cikarang Selatan','Bekasi|Cikarang Timur','Bekasi|Cikarang Utara','Bekasi|Karangbahagia',
'Bekasi|Kedungwaringin','Bekasi|Muara Gembong','Bekasi|Pebayuran','Bekasi|Serang Baru','Bekasi|Setu','Bekasi|Sukakarya',
'Bekasi|Sukatani','Bekasi|Sukawangi','Bekasi|Tambelang','Bekasi|Tambun Selatan','Bekasi|Tambun Utara','Bekasi|Tarumajaya',
'Bogor|Babakan Madang','Bogor|Bojonggede','Bogor|Caringin','Bogor|Cariu','Bogor|Ciampea','Bogor|Ciawi','Bogor|Cibinong',
'Bogor|Cibungbulang','Bogor|Cigombong','Bogor|Cigudeg','Bogor|Cijeruk','Bogor|Cileungsi','Bogor|Ciomas',
'Bogor|Cisarua','Bogor|Ciseeng','Bogor|Citeureup','Bogor|Dramaga','Bogor|Gunung Putri','Bogor|Gunung Sindur',
'Bogor|Jasinga','Bogor|Jonggol','Bogor|Kemang','Bogor|Klapanunggal','Bogor|Leuwiliang','Bogor|Leuwisadeng',
'Bogor|Megamendung','Bogor|Nanggung','Bogor|Pamijahan','Bogor|Parung','Bogor|Parung Panjang',
'Bogor|Ranca Bungur','Bogor|Rumpin','Bogor|Sukajaya','Bogor|Sukamakmur','Bogor|Sukaraja','Bogor|Tajurhalang',
'Bogor|Tamansari','Bogor|Tanjungsari','Bogor|Tenjo','Bogor|Tenjolaya',
'Ciamis|Banjarsari','Ciamis|Baregbeg','Ciamis|Ciamis','Ciamis|Cidolog','Ciamis|Cihaurbeuti','Ciamis|Cijeungjing',
'Ciamis|Cikoneng','Ciamis|Cimaragas','Ciamis|Cipaku','Ciamis|Cisaga','Ciamis|Jatinagara','Ciamis|Kawali',
'Ciamis|Lakbok','Ciamis|Lumbung','Ciamis|Mangunreja','Ciamis|Padaherang','Ciamis|Pamarican','Ciamis|Panawangan',
'Ciamis|Panjalu','Ciamis|Panumbangan','Ciamis|Purwadadi','Ciamis|Rajadesa','Ciamis|Rancah','Ciamis|Sadananya',
'Ciamis|Sindangkasih','Ciamis|Sukadana','Ciamis|Sukamantri','Ciamis|Tambaksari',
'Cianjur|Agrabinta','Cianjur|Bojongpicung','Cianjur|Campaka','Cianjur|Campaka Mulya','Cianjur|Cianjur','Cianjur|Cibeber',
'Cianjur|Cibinong','Cianjur|Cidaun','Cianjur|Cijati','Cianjur|Cikadu','Cianjur|Cikalongkulon','Cianjur|Cilaku',
'Cianjur|Cipanas','Cianjur|Ciranjang','Cianjur|Cugenang','Cianjur|Gekbrong','Cianjur|Haurwangi','Cianjur|Kadupandak',
'Cianjur|Karangtengah','Cianjur|Leles','Cianjur|Mande','Cianjur|Naringgul','Cianjur|Pacet','Cianjur|Pagelaran',
'Cianjur|Pasirkuda','Cianjur|Sindangbarang','Cianjur|Sukaluyu','Cianjur|Sukanagara','Cianjur|Sukaresmi',
'Cianjur|Takokak','Cianjur|Tanggeung','Cianjur|Warungkondang',
'Cirebon|Arjawinangun','Cirebon|Astanajapura','Cirebon|Babakan','Cirebon|Beber','Cirebon|Ciledug','Cirebon|Ciwaringin',
'Cirebon|Depok','Cirebon|Dukupuntang','Cirebon|Gebang','Cirebon|Gegesik','Cirebon|Gempol','Cirebon|Greged',
'Cirebon|Gunung Jati','Cirebon|Jamblang','Cirebon|Kaliwedi','Cirebon|Kapetakan','Cirebon|Karangsembung',
'Cirebon|Karangwareng','Cirebon|Kedawung','Cirebon|Klangenan','Cirebon|Lemahabang','Cirebon|Losari','Cirebon|Mundu',
'Cirebon|Pabedilan','Cirebon|Pabuaran','Cirebon|Palimanan','Cirebon|Pangenan','Cirebon|Panguragan','Cirebon|Pasaleman',
'Cirebon|Plered','Cirebon|Plumbon','Cirebon|Sedong','Cirebon|Sumber','Cirebon|Suranenggala','Cirebon|Susukan',
'Cirebon|Susukan Lebak','Cirebon|Talun','Cirebon|Tengah Tani','Cirebon|Waled','Cirebon|Weru',
'Garut|Banjarwangi','Garut|Banyuresmi','Garut|Bayongbong','Garut|Blubur Limbangan','Garut|Bungbulang','Garut|Caringin',
'Garut|Cibalong','Garut|Cibatu','Garut|Cibiuk','Garut|Cigedug','Garut|Cihurip','Garut|Cikajang','Garut|Cikelet',
'Garut|Cilawu','Garut|Cisewu','Garut|Cisompet','Garut|Cisurupan','Garut|Garut Kota','Garut|Kadungora',
'Garut|Karangpawitan','Garut|Karangtengah','Garut|Kersamanah','Garut|Leles','Garut|Leuwigoong','Garut|Malangbong',
'Garut|Mekarmukti','Garut|Pakenjeng','Garut|Pameungpeuk','Garut|Pamulihan','Garut|Pangatikan','Garut|Pasirwangi',
'Garut|Peundeuy','Garut|Samarang','Garut|Selaawi','Garut|Singajaya','Garut|Sucinaraja','Garut|Sukaresmi',
'Garut|Sukawening','Garut|Talegong','Garut|Tarogong Kaler','Garut|Tarogong Kidul','Garut|Wanaraja',
'Indramayu|Anjatan','Indramayu|Arahan','Indramayu|Balongan','Indramayu|Bangodua','Indramayu|Bongas','Indramayu|Cantigi',
'Indramayu|Cikedung','Indramayu|Gabuswetan','Indramayu|Gantar','Indramayu|Haurgeulis','Indramayu|Indramayu',
'Indramayu|Jatibarang','Indramayu|Juntinyuat','Indramayu|Kandanghaur','Indramayu|Karangampel','Indramayu|Kedokan Bunder',
'Indramayu|Kertasemaya','Indramayu|Krangkeng','Indramayu|Kroya','Indramayu|Lelea','Indramayu|Lohbener',
'Indramayu|Losarang','Indramayu|Pasekan','Indramayu|Patrol','Indramayu|Sindang','Indramayu|Sliyeg',
'Indramayu|Sukagumiwang','Indramayu|Sukra','Indramayu|Trisi','Indramayu|Tukdana','Indramayu|Widasari',
'Karawang|Banyusari','Karawang|Batujaya','Karawang|Ciampel','Karawang|Cibuaya','Karawang|Cikampek',
'Karawang|Cilamaya Kulon','Karawang|Cilamaya Wetan','Karawang|Cilebar','Karawang|Jatisari','Karawang|Jayakerta',
'Karawang|Karawang Barat','Karawang|Karawang Timur','Karawang|Klari','Karawang|Kotabaru','Karawang|Kutawaluya',
'Karawang|Lemahabang','Karawang|Majalaya','Karawang|Pakisjaya','Karawang|Pangkalan','Karawang|Pedes',
'Karawang|Purwasari','Karawang|Rawamerta','Karawang|Rengasdengklok','Karawang|Talagasari','Karawang|Tegalwaru',
'Karawang|Telukjambe Barat','Karawang|Telukjambe Timur','Karawang|Tempuran','Karawang|Tirtajaya','Karawang|Tirtamulya',
'Kuningan|Ciawigebang','Kuningan|Cibeureum','Kuningan|Cibingbin','Kuningan|Cidahu','Kuningan|Cigandamekar',
'Kuningan|Cigugur','Kuningan|Cilebak','Kuningan|Cilimus','Kuningan|Cimahi','Kuningan|Ciniru','Kuningan|Cipicung',
'Kuningan|Ciwaru','Kuningan|Darma','Kuningan|Garawangi','Kuningan|Hantara','Kuningan|Jalaksana','Kuningan|Japara',
'Kuningan|Kadugede','Kuningan|Kalimanggis','Kuningan|Karangkancana','Kuningan|Kramatmulya','Kuningan|Kuningan',
'Kuningan|Lebakwangi','Kuningan|Luragung','Kuningan|Maleber','Kuningan|Mandirancan','Kuningan|Nusaherang',
'Kuningan|Pancalang','Kuningan|Pasawahan','Kuningan|Selajambe','Kuningan|Sindangagung','Kuningan|Subang',
'Majalengka|Argapura','Majalengka|Banjaran','Majalengka|Bantarujeg','Majalengka|Cigasong','Majalengka|Cikijing',
'Majalengka|Cingambul','Majalengka|Dawuan','Majalengka|Jatitujuh','Majalengka|Jatiwangi','Majalengka|Kadipaten',
'Majalengka|Kasokandel','Majalengka|Kertajati','Majalengka|Lemahsugih','Majalengka|Leuwimunding','Majalengka|Ligung',
'Majalengka|Maja','Majalengka|Majalengka','Majalengka|Malausma','Majalengka|Palasah','Majalengka|Panyingkiran',
'Majalengka|Rajagaluh','Majalengka|Sindang','Majalengka|Sindangwangi','Majalengka|Sukahaji','Majalengka|Sumberjaya',
'Majalengka|Talaga',
'Pangandaran|Cigugur','Pangandaran|Cijulang','Pangandaran|Cimerak','Pangandaran|Kalipucang','Pangandaran|Langkaplancar',
'Pangandaran|Mangunjaya','Pangandaran|Padaherang','Pangandaran|Pangandaran','Pangandaran|Parigi','Pangandaran|Sidamulih',
'Purwakarta|Babakancikao','Purwakarta|Bojong','Purwakarta|Bungursari','Purwakarta|Campaka','Purwakarta|Cibatu',
'Purwakarta|Darangdan','Purwakarta|Jatiluhur','Purwakarta|Kiarapedes','Purwakarta|Maniis','Purwakarta|Pasawahan',
'Purwakarta|Plered','Purwakarta|Pondoksalam','Purwakarta|Purwakarta','Purwakarta|Sukasari','Purwakarta|Sukatani',
'Purwakarta|Tegalwaru','Purwakarta|Wanayasa',
'Subang|Binong','Subang|Blanakan','Subang|Ciasem','Subang|Ciater','Subang|Cibogo','Subang|Cijambe','Subang|Cikaum',
'Subang|Cipeundeuy','Subang|Cipunagara','Subang|Cisalak','Subang|Compreng','Subang|Dawuan','Subang|Jalancagak',
'Subang|Kalijati','Subang|Kasomalang','Subang|Legonkulon','Subang|Pabuaran','Subang|Pagaden','Subang|Pagaden Barat',
'Subang|Pamanukan','Subang|Patokbeusi','Subang|Purwadadi','Subang|Pusakajaya','Subang|Pusakanagara','Subang|Sagalaherang',
'Subang|Serangpanjang','Subang|Subang','Subang|Sukasari','Subang|Tambakdahan','Subang|Tanjungsiang',
'Sukabumi|Bantargadung','Sukabumi|Bojonggenteng','Sukabumi|Caringin','Sukabumi|Ciambar','Sukabumi|Cibadak',
'Sukabumi|Cibitung','Sukabumi|Cicantayan','Sukabumi|Cicurug','Sukabumi|Cidadap','Sukabumi|Cidahu','Sukabumi|Cidolog',
'Sukabumi|Ciemas','Sukabumi|Cikakak','Sukabumi|Cikembar','Sukabumi|Cikidang','Sukabumi|Cimanggu','Sukabumi|Ciracap',
'Sukabumi|Cireunghas','Sukabumi|Cisaat','Sukabumi|Cisolok','Sukabumi|Curugkembar','Sukabumi|Gegerbitung',
'Sukabumi|Gunung Guruh','Sukabumi|Jampang Kulon','Sukabumi|Jampang Tengah','Sukabumi|Kabandungan',
'Sukabumi|Kadudampit','Sukabumi|Kalapa Nunggal','Sukabumi|Kali Bunder','Sukabumi|Kebonpedes','Sukabumi|Lengkong',
'Sukabumi|Nagrak','Sukabumi|Nyalindung','Sukabumi|Pabuaran','Sukabumi|Parakan Salak','Sukabumi|Parung Kuda',
'Sukabumi|Pelabuhan Ratu','Sukabumi|Purabaya','Sukabumi|Sagaranten','Sukabumi|Simpenan','Sukabumi|Sukabumi',
'Sukabumi|Sukalarang','Sukabumi|Sukaraja','Sukabumi|Surade','Sukabumi|Tegal Buleud','Sukabumi|Waluran','Sukabumi|Warungkiara',
'Sumedang|Buahdua','Sumedang|Cibugel','Sumedang|Cimalaka','Sumedang|Cimanggung','Sumedang|Cisarua','Sumedang|Cisitu',
'Sumedang|Conggeang','Sumedang|Darmaraja','Sumedang|Ganeas','Sumedang|Jatigede','Sumedang|Jatinangor','Sumedang|Jatinunggal',
'Sumedang|Pamulihan','Sumedang|Paseh','Sumedang|Rancakalong','Sumedang|Situraja','Sumedang|Sukasari','Sumedang|Sumedang Selatan',
'Sumedang|Sumedang Utara','Sumedang|Surian','Sumedang|Tanjungkerta','Sumedang|Tanjungmedar','Sumedang|Tanjungsari',
'Sumedang|Tomo','Sumedang|Ujungjaya','Sumedang|Wado',
'Tasikmalaya|Bantarkalong','Tasikmalaya|Bojongasih','Tasikmalaya|Bojonggambir','Tasikmalaya|Ciawi','Tasikmalaya|Cibalong',
'Tasikmalaya|Cigalontang','Tasikmalaya|Cikalong','Tasikmalaya|Cikatomas','Tasikmalaya|Cineam','Tasikmalaya|Cipatujah',
'Tasikmalaya|Cisayong','Tasikmalaya|Culamega','Tasikmalaya|Gunung Tanjung','Tasikmalaya|Jamanis','Tasikmalaya|Jatiwaras',
'Tasikmalaya|Kadipaten','Tasikmalaya|Karang Jaya','Tasikmalaya|Karangnunggal','Tasikmalaya|Leuwisari','Tasikmalaya|Mangunreja',
'Tasikmalaya|Manonjaya','Tasikmalaya|Padakembang','Tasikmalaya|Pagerageung','Tasikmalaya|Pancatengah','Tasikmalaya|Parungponteng',
'Tasikmalaya|Puspahiang','Tasikmalaya|Rajapolah','Tasikmalaya|Salawu','Tasikmalaya|Salopa','Tasikmalaya|Sariwangi',
'Tasikmalaya|Singaparna','Tasikmalaya|Sodonghilir','Tasikmalaya|Sukahening','Tasikmalaya|Sukaraja','Tasikmalaya|Sukarame',
'Tasikmalaya|Sukaratu','Tasikmalaya|Sukaresik','Tasikmalaya|Tanjungjaya','Tasikmalaya|Taraju',
'Bandung Kota|Andir','Bandung Kota|Antapani','Bandung Kota|Arcamanik','Bandung Kota|Astanaanyar','Bandung Kota|Babakan Ciparay',
'Bandung Kota|Bandung Kidul','Bandung Kota|Bandung Kulon','Bandung Kota|Bandung Wetan','Bandung Kota|Batununggal',
'Bandung Kota|Bojongloa Kaler','Bandung Kota|Bojongloa Kidul','Bandung Kota|Buahbatu','Bandung Kota|Cibeunying Kaler',
'Bandung Kota|Cibeunying Kidul','Bandung Kota|Cibiru','Bandung Kota|Cicendo','Bandung Kota|Cidadap','Bandung Kota|Cinambo',
'Bandung Kota|Coblong','Bandung Kota|Gedebage','Bandung Kota|Kiaracondong','Bandung Kota|Lengkong','Bandung Kota|Mandalajati',
'Bandung Kota|Panyileukan','Bandung Kota|Rancasari','Bandung Kota|Regol','Bandung Kota|Sukajadi','Bandung Kota|Sukasari',
'Bandung Kota|Sumur Bandung','Bandung Kota|Ujungberung',
'Banjar|Banjar','Banjar|Langensari','Banjar|Pataruman','Banjar|Purwaharja',
'Bekasi Kota|Bantar Gebang','Bekasi Kota|Bekasi Barat','Bekasi Kota|Bekasi Selatan','Bekasi Kota|Bekasi Timur',
'Bekasi Kota|Bekasi Utara','Bekasi Kota|Jatiasih','Bekasi Kota|Jatisampurna','Bekasi Kota|Medan Satria',
'Bekasi Kota|Mustika Jaya','Bekasi Kota|Pondok Gede','Bekasi Kota|Pondok Melati','Bekasi Kota|Rawalumbu',
'Bogor Kota|Bogor Barat','Bogor Kota|Bogor Selatan','Bogor Kota|Bogor Tengah','Bogor Kota|Bogor Timur','Bogor Kota|Bogor Utara',
'Bogor Kota|Tanah Sareal',
'Cimahi|Cimahi Selatan','Cimahi|Cimahi Tengah','Cimahi|Cimahi Utara',
'Cirebon Kota|Harjamukti','Cirebon Kota|Kejaksan','Cirebon Kota|Kesambi','Cirebon Kota|Lemahwungkuk','Cirebon Kota|Pekalipan',
'Depok|Beji','Depok|Bojongsari','Depok|Cilodong','Depok|Cimanggis','Depok|Cinere','Depok|Cipayung','Depok|Limo',
'Depok|Pancoran Mas','Depok|Sawangan','Depok|Sukmajaya','Depok|Tapos',
'Sukabumi Kota|Baros','Sukabumi Kota|Cibeureum','Sukabumi Kota|Cikole','Sukabumi Kota|Citamiang','Sukabumi Kota|Gunung Puyuh',
'Sukabumi Kota|Lembursitu','Sukabumi Kota|Warudoyong',
'Tasikmalaya Kota|Bungursari','Tasikmalaya Kota|Cibeureum','Tasikmalaya Kota|Cihideung','Tasikmalaya Kota|Cipedes',
'Tasikmalaya Kota|Indihiang','Tasikmalaya Kota|Kawalu','Tasikmalaya Kota|Mangkubumi','Tasikmalaya Kota|Purbaratu',
'Tasikmalaya Kota|Tamansari','Tasikmalaya Kota|Tawang',
], 'Jawa Barat');

echo "Jawa Barat done.\n";
