<?php
function add($f, $entries, $prov) {
    $o = '';
    foreach ($entries as $e) {
        $p = explode('|', $e);
        $k = trim($p[0]); $n = trim($p[1]);
        $s = strtolower(str_replace(' ', '-', $n));
        $s = str_replace(["'", '/', '(', ')', '.'], '', $s);
        $s = str_replace('--', '-', $s); $s = trim($s, '-');
        $ne = str_replace("'", "\'", $n);
        $o .= "        ['slug' => '{$s}', 'nama' => '{$ne}', 'kota' => '{$k}', 'provinsi' => '{$prov}'],\n";
    }
    file_put_contents($f, $o, FILE_APPEND);
}
$f = __DIR__ . '/../config/pseo-kecamatan.php';

// PAPUA BARAT (13 kab/kota, ~218 kecamatan)
add($f, [
'Fakfak|Arguni','Fakfak|Bomberay','Fakfak|Fakfak','Fakfak|Fakfak Barat','Fakfak|Fakfak Tengah','Fakfak|Fakfak Timur',
'Fakfak|Fakfak Timur Tengah','Fakfak|Furwagi','Fakfak|Karas','Fakfak|Kayauni','Fakfak|Kokas','Fakfak|Kramongmongga',
'Fakfak|Mbahamdandara','Fakfak|Pariwari','Fakfak|Teluk Patipi','Fakfak|Tomage','Fakfak|Wartutin',
'Kaimana|Buruway','Kaimana|Kaimana','Kaimana|Kambrau','Kaimana|Teluk Arguni Atas','Kaimana|Teluk Arguni Bawah',
'Kaimana|Teluk Etna','Kaimana|Yamor',
'Manokwari|Manokwari Barat','Manokwari|Manokwari Selatan','Manokwari|Manokwari Timur','Manokwari|Manokwari Utara',
'Manokwari|Masni','Manokwari|Prafi','Manokwari|Sidey','Manokwari|Tanah Rubuh','Manokwari|Warmare',
'Manokwari Selatan|Dataran Isim','Manokwari Selatan|Momi Waren','Manokwari Selatan|Neney','Manokwari Selatan|Oransbari',
'Manokwari Selatan|Ransiki','Manokwari Selatan|Tohota',
'Pegunungan Arfak|Anggi','Pegunungan Arfak|Anggi Gida','Pegunungan Arfak|Catubouw','Pegunungan Arfak|Didohu',
'Pegunungan Arfak|Hingk','Pegunungan Arfak|Membey','Pegunungan Arfak|Minyambouw','Pegunungan Arfak|Sururey',
'Pegunungan Arfak|Taige','Pegunungan Arfak|Testega',
'Teluk Bintuni|Aranday','Teluk Bintuni|Aroba','Teluk Bintuni|Babo','Teluk Bintuni|Bintuni','Teluk Bintuni|Biscoop',
'Teluk Bintuni|Dataran Beimes','Teluk Bintuni|Fafurwar','Teluk Bintuni|Kaitaro','Teluk Bintuni|Kamundan','Teluk Bintuni|Kuri',
'Teluk Bintuni|Manimeri','Teluk Bintuni|Masyeta','Teluk Bintuni|Meriambuni','Teluk Bintuni|Meyado','Teluk Bintuni|Moswaren',
'Teluk Bintuni|Sumuri','Teluk Bintuni|Tembuni','Teluk Bintuni|Tomu','Teluk Bintuni|Tuhiba','Teluk Bintuni|Wamesa',
'Teluk Wondama|Kuri Wamesa','Teluk Wondama|Naikere','Teluk Wondama|Nikiwar','Teluk Wondama|Rasiei','Teluk Wondama|Roon',
'Teluk Wondama|Roswar','Teluk Wondama|Rumberpon','Teluk Wondama|Soug Jaya','Teluk Wondama|Teluk Duairi','Teluk Wondama|Wamesa',
'Teluk Wondama|Wasior','Teluk Wondama|Windesi','Teluk Wondama|Wondiboy',
'Sorong|Aimas','Sorong|Bagun','Sorong|Beraur','Sorong|Botain','Sorong|Buk','Sorong|Hobard','Sorong|Klabot','Sorong|Klamono',
'Sorong|Klasafet','Sorong|Klaso','Sorong|Klawak','Sorong|Klayili','Sorong|Konhir','Sorong|Makbon','Sorong|Malabotom',
'Sorong|Mariat','Sorong|Maudus','Sorong|Mayamuk','Sorong|Mayamuk Timur','Sorong|Mesana','Sorong|Moraid','Sorong|Mosal','Sorong|Salawati',
'Sorong|Salawati Selatan','Sorong|Salawati Tengah','Sorong|Sayosa','Sorong|Sayosa Timur','Sorong|Segun','Sorong|Seget',
'Sorong|Wemak',
'Sorong Selatan|Fokour','Sorong Selatan|Inanwatan','Sorong Selatan|Kais','Sorong Selatan|Kais Darat','Sorong Selatan|Kokoda',
'Sorong Selatan|Kokoda Utara','Sorong Selatan|Konda','Sorong Selatan|Matemani','Sorong Selatan|Moswaren','Sorong Selatan|Saifi',
'Sorong Selatan|Sawiat','Sorong Selatan|Seremuk','Sorong Selatan|Teminabuan','Sorong Selatan|Wayer',
'Tambrauw|Abun','Tambrauw|Amberbaken','Tambrauw|Amberbaken Barat','Tambrauw|Ases','Tambrauw|Bamusbama','Tambrauw|Bikar',
'Tambrauw|Fef','Tambrauw|Ireres','Tambrauw|Kasi','Tambrauw|Kebar','Tambrauw|Kebar Selatan','Tambrauw|Kebar Timur',
'Tambrauw|Kwesefo','Tambrauw|Kwoor','Tambrauw|Manekar','Tambrauw|Mawabuan','Tambrauw|Miyah','Tambrauw|Miyah Selatan',
'Tambrauw|Moraid','Tambrauw|Mpur','Tambrauw|Mubrani','Tambrauw|Sausapor','Tambrauw|Selemkai','Tambrauw|Senopi','Tambrauw|Syujak',
'Tambrauw|Tinggouw','Tambrauw|Tobouw','Tambrauw|Wilhem Roumbouts','Tambrauw|Yembun',
'Sorong Kota|Klaurung','Sorong Kota|Maladum Mes','Sorong Kota|Malaimsimsa','Sorong Kota|Sorong','Sorong Kota|Sorong Barat',
'Sorong Kota|Sorong Kepulauan','Sorong Kota|Sorong Kota','Sorong Kota|Sorong Manoi','Sorong Kota|Sorong Timur','Sorong Kota|Sorong Utara',
], 'Papua Barat');

// PAPUA (29 kab/kota, ~446 kecamatan)
add($f, [
'Asmat|Agats','Asmat|Akat','Asmat|Aswi','Asmat|Atsj','Asmat|Ayip','Asmat|Betcbamu','Asmat|Der Koumur','Asmat|Fayit',
'Asmat|Jetsy','Asmat|Joerat','Asmat|Kolf Braza','Asmat|Kopay','Asmat|Koroway Buluanop','Asmat|Pantai Kasuari',
'Asmat|Pulau Tiga','Asmat|Safan','Asmat|Sawa Erma','Asmat|Sirets','Asmat|Suator','Asmat|Suru-Suru','Asmat|Tomor Birip',
'Asmat|Unir Sirau',
'Biak Numfor|Aimando Padaido','Biak Numfor|Andey','Biak Numfor|Biak Barat','Biak Numfor|Biak Kota','Biak Numfor|Biak Timur',
'Biak Numfor|Biak Utara','Biak Numfor|Bondifuar','Biak Numfor|Bruyadori','Biak Numfor|Numfor Barat','Biak Numfor|Numfor Timur',
'Biak Numfor|Oridek','Biak Numfor|Orkeri','Biak Numfor|Padaido','Biak Numfor|Poiru','Biak Numfor|Samofa','Biak Numfor|Swandiwe',
'Biak Numfor|Warsa','Biak Numfor|Yawosi','Biak Numfor|Yendidori',
'Boven Digoel|Ambatkwi','Boven Digoel|Arimop','Boven Digoel|Bomakia','Boven Digoel|Firiwage','Boven Digoel|Fofi',
'Boven Digoel|Iniyandit','Boven Digoel|Jair','Boven Digoel|Kawagit','Boven Digoel|Ki','Boven Digoel|Kombay',
'Boven Digoel|Kombut','Boven Digoel|Kouh','Boven Digoel|Mandobo','Boven Digoel|Manggelum','Boven Digoel|Mindiptana',
'Boven Digoel|Ninati','Boven Digoel|Sesnuk','Boven Digoel|Subur','Boven Digoel|Waropko','Boven Digoel|Yaniruma',
'Deiyai|Bowobado','Deiyai|Kapiraya','Deiyai|Tigi','Deiyai|Tigi Barat','Deiyai|Tigi Timur',
'Dogiyai|Dogiyai','Dogiyai|Kamu','Dogiyai|Kamu Selatan','Dogiyai|Kamu Timur','Dogiyai|Kamu Utara','Dogiyai|Mapia',
'Dogiyai|Mapia Barat','Dogiyai|Mapia Tengah','Dogiyai|Piyaiye','Dogiyai|Sukikai Selatan',
'Intan Jaya|Agisiga','Intan Jaya|Biandoga','Intan Jaya|Hitadipa','Intan Jaya|Homeyo','Intan Jaya|Sugapa','Intan Jaya|Tomosiga',
'Intan Jaya|Ugimba','Intan Jaya|Wandai',
'Jayapura|Airu','Jayapura|Demta','Jayapura|Depapre','Jayapura|Ebungfao','Jayapura|Gresi Selatan','Jayapura|Kaureh',
'Jayapura|Kemtuk','Jayapura|Kemtuk Gresi','Jayapura|Nambluong','Jayapura|Nimbokrang','Jayapura|Nimboran','Jayapura|Ravenirara',
'Jayapura|Sentani','Jayapura|Sentani Barat','Jayapura|Sentani Timur','Jayapura|Unurum Guay','Jayapura|Waibu','Jayapura|Yapsi','Jayapura|Yokari',
'Jayawijaya|Asologaima','Jayawijaya|Asolokobal','Jayawijaya|Asotipo','Jayawijaya|Bolakme','Jayawijaya|Bpiri',
'Jayawijaya|Bugi','Jayawijaya|Hubikiak','Jayawijaya|Hubikosi','Jayawijaya|Ibele','Jayawijaya|Itlay Hisage',
'Jayawijaya|Koragi','Jayawijaya|Kurulu','Jayawijaya|Libarek','Jayawijaya|Maima','Jayawijaya|Molagalome',
'Jayawijaya|Muliama','Jayawijaya|Musatfak','Jayawijaya|Napua','Jayawijaya|Pelebaga','Jayawijaya|Piramid',
'Jayawijaya|Pisugi','Jayawijaya|Popugoba','Jayawijaya|Siepkosi','Jayawijaya|Silo Karno Doga','Jayawijaya|Taelarek',
'Jayawijaya|Tagime','Jayawijaya|Tagineri','Jayawijaya|Trikora','Jayawijaya|Usilimo','Jayawijaya|Wadangku',
'Jayawijaya|Walaik','Jayawijaya|Walelagama','Jayawijaya|Wame','Jayawijaya|Wamena','Jayawijaya|Welesi','Jayawijaya|Wesaput',
'Jayawijaya|Wita Waya','Jayawijaya|Wollo','Jayawijaya|Wouma','Jayawijaya|Yalengga',
'Keerom|Arso','Keerom|Arso Barat','Keerom|Arso Timur','Keerom|Kaisenar','Keerom|Mannem','Keerom|Senggi','Keerom|Skanto',
'Keerom|Towe','Keerom|Waris','Keerom|Web','Keerom|Yaffi',
'Kepulauan Yapen|Angkaisera','Kepulauan Yapen|Anotaurei','Kepulauan Yapen|Kepulauan Ambai','Kepulauan Yapen|Kosiwo',
'Kepulauan Yapen|Nusawani','Kepulauan Yapen|Poom','Kepulauan Yapen|Pulau Kurudu','Kepulauan Yapen|Pulau Yerui',
'Kepulauan Yapen|Raimbawi','Kepulauan Yapen|Teluk Ampimoi','Kepulauan Yapen|Windesi','Kepulauan Yapen|Wonawa',
'Kepulauan Yapen|Yapen Barat','Kepulauan Yapen|Yapen Selatan','Kepulauan Yapen|Yapen Timur','Kepulauan Yapen|Yapen Utara',
'Lanny Jaya|Awina','Lanny Jaya|Ayumnati','Lanny Jaya|Balingga','Lanny Jaya|Balingga Barat','Lanny Jaya|Bruwa',
'Lanny Jaya|Buguk Gona','Lanny Jaya|Dimba','Lanny Jaya|Gamelia','Lanny Jaya|Gelok Beam','Lanny Jaya|Goa Balim',
'Lanny Jaya|Gollo','Lanny Jaya|Guna','Lanny Jaya|Gupura','Lanny Jaya|Karu','Lanny Jaya|Kelulome','Lanny Jaya|Kolawa',
'Lanny Jaya|Kuly Lanny','Lanny Jaya|Kuyawage','Lanny Jaya|Lannyna','Lanny Jaya|Makki','Lanny Jaya|Melagi','Lanny Jaya|Melagineri',
'Lanny Jaya|Milimbo','Lanny Jaya|Mokoni','Lanny Jaya|Muara','Lanny Jaya|Nikogwe','Lanny Jaya|Niname','Lanny Jaya|Nogi',
'Lanny Jaya|Pirime','Lanny Jaya|Poga','Lanny Jaya|Tiom','Lanny Jaya|Tiom Ollo','Lanny Jaya|Tiomneri','Lanny Jaya|Wiringgambut',
'Lanny Jaya|Wugi','Lanny Jaya|Yiginua','Lanny Jaya|Yiluk','Lanny Jaya|Yugungwi',
'Mamberamo Raya|Benuki','Mamberamo Raya|Mamberamo Hilir','Mamberamo Raya|Mamberamo Hulu','Mamberamo Raya|Mamberamo Tengah',
'Mamberamo Raya|Mamberamo Tengah Timur','Mamberamo Raya|Rufaer','Mamberamo Raya|Sawai','Mamberamo Raya|Waropen Atas',
'Mamberamo Tengah|Eragayam','Mamberamo Tengah|Ilugwa','Mamberamo Tengah|Kelila','Mamberamo Tengah|Kobakma','Mamberamo Tengah|Megambilis',
'Mappi|Assue','Mappi|Bamgi','Mappi|Citak Mitak','Mappi|Edera','Mappi|Haju','Mappi|Kaibar','Mappi|Minyamur','Mappi|Obaa',
'Mappi|Passue','Mappi|Passue Bawah','Mappi|Syahcame','Mappi|Ti Zain','Mappi|Venaha','Mappi|Yakomi',
'Merauke|Animha','Merauke|Distrik Ulilin','Merauke|Eligobel','Merauke|Ilyawab','Merauke|Jagebob','Merauke|Kaptel',
'Merauke|Kimaam','Merauke|Kontuar','Merauke|Kurik','Merauke|Malind','Merauke|Merauke','Merauke|Muting','Merauke|Naukenjerai',
'Merauke|Ngguti','Merauke|Okaba','Merauke|Padua','Merauke|Semangga','Merauke|Sota','Merauke|Tabonji','Merauke|Tanah Miring',
'Merauke|Tubang','Merauke|Ulilin','Merauke|Waan',
'Mimika|Agimuga','Mimika|Alama','Mimika|Amar','Mimika|Hoya','Mimika|Iwaka','Mimika|Jila','Mimika|Jita','Mimika|Kuala Kencana',
'Mimika|Kwamki Narama','Mimika|Mimika Barat','Mimika|Mimika Barat Jauh','Mimika|Mimika Barat Tengah','Mimika|Mimika Baru',
'Mimika|Mimika Tengah','Mimika|Mimika Timur','Mimika|Mimika Timur Jauh','Mimika|Tembagapura','Mimika|Wania',
'Nabire|Dipa','Nabire|Makimi','Nabire|Menou','Nabire|Moora','Nabire|Nabire','Nabire|Nabire Barat','Nabire|Napan',
'Nabire|Siriwo','Nabire|Teluk Kimi','Nabire|Teluk Umar','Nabire|Uwapa','Nabire|Wanggar','Nabire|Wapoga','Nabire|Yaro',
'Nabire|Yaur',
'Nduga|Alama','Nduga|Dal','Nduga|Embetpen','Nduga|Gearek','Nduga|Geselma','Nduga|Inikgal','Nduga|Iniye','Nduga|Kegayem',
'Nduga|Kenyam','Nduga|Kilmid','Nduga|Kora','Nduga|Koroptak','Nduga|Krepkuri','Nduga|Mam','Nduga|Mapenduma','Nduga|Mbua Tengah',
'Nduga|Mbulmu Yalma','Nduga|Mbuwa','Nduga|Mebarok','Nduga|Moba','Nduga|Mugi','Nduga|Nenggeagin','Nduga|Nirkuri',
'Nduga|Paro','Nduga|Pasir Putih','Nduga|Pija','Nduga|Wosak','Nduga|Wusi','Nduga|Wutpaga','Nduga|Yal','Nduga|Yenggelo','Nduga|Yigi',
'Paniai|Aradide','Paniai|Aweida','Paniai|Baya Biru','Paniai|Bibida','Paniai|Bogabaida','Paniai|Deiyai Miyo','Paniai|Dogomo',
'Paniai|Dumadama','Paniai|Ekadide','Paniai|Fajar Timur','Paniai|Kebo','Paniai|Muye','Paniai|Nakama','Paniai|Paniai Barat',
'Paniai|Paniai Timur','Paniai|Pugo Dagi','Paniai|Siriwo','Paniai|Teluk Deya','Paniai|Topiyai','Paniai|Wegee Bino',
'Paniai|Wegee Muka','Paniai|Yagai','Paniai|Yatamo',
'Pegunungan Bintang|Aboy','Pegunungan Bintang|Alemsom','Pegunungan Bintang|Awinbon','Pegunungan Bintang|Batani',
'Pegunungan Bintang|Batom','Pegunungan Bintang|Bime','Pegunungan Bintang|Borme','Pegunungan Bintang|Eipumek',
'Pegunungan Bintang|Iwur','Pegunungan Bintang|Jetfa','Pegunungan Bintang|Kalomdol','Pegunungan Bintang|Kawor',
'Pegunungan Bintang|Kiwirok','Pegunungan Bintang|Kiwirok Timur','Pegunungan Bintang|Mofinop','Pegunungan Bintang|Murkim',
'Pegunungan Bintang|Nongme','Pegunungan Bintang|Ok Aom','Pegunungan Bintang|Okbab','Pegunungan Bintang|Okbape','Pegunungan Bintang|Okbemtau',
'Pegunungan Bintang|Okbibab','Pegunungan Bintang|Okhika','Pegunungan Bintang|Oklip','Pegunungan Bintang|Oksamol','Pegunungan Bintang|Oksebang',
'Pegunungan Bintang|Oksibil','Pegunungan Bintang|Oksop','Pegunungan Bintang|Pamek','Pegunungan Bintang|Pepera',
'Pegunungan Bintang|Serambakon','Pegunungan Bintang|Tarup','Pegunungan Bintang|Teiraplu','Pegunungan Bintang|Weime',
'Puncak|Agandugume','Puncak|Amungkalpia','Puncak|Beoga','Puncak|Beoga Barat','Puncak|Beoga Timur','Puncak|Bina',
'Puncak|Dervos','Puncak|Doufo','Puncak|Erelmakawia','Puncak|Gome','Puncak|Gome Utara','Puncak|Ilaga','Puncak|Ilaga Utara',
'Puncak|Kembru','Puncak|Lambewi','Puncak|Mageabume','Puncak|Ogamanim','Puncak|Omukia','Puncak|Oneri','Puncak|Pogoma',
'Puncak|Sinak','Puncak|Sinak Barat','Puncak|Wangbe','Puncak|Yugumuak',
'Puncak Jaya|Dagai','Puncak Jaya|Dokome','Puncak Jaya|Fawi','Puncak Jaya|Gubume','Puncak Jaya|Gurage','Puncak Jaya|Ilamburawi',
'Puncak Jaya|Ilu','Puncak Jaya|Irimuli','Puncak Jaya|Kalome','Puncak Jaya|Kiyage','Puncak Jaya|Lumo','Puncak Jaya|Mewoluk',
'Puncak Jaya|Molanikime','Puncak Jaya|Muara','Puncak Jaya|Mulia','Puncak Jaya|Nioga','Puncak Jaya|Nume','Puncak Jaya|Pagaleme',
'Puncak Jaya|Taganombak','Puncak Jaya|Tingginambut','Puncak Jaya|Torere','Puncak Jaya|Waegi','Puncak Jaya|Wanwi',
'Puncak Jaya|Yambi','Puncak Jaya|Yamoneri',
'Sarmi|Apawer Hulu','Sarmi|Bonggo','Sarmi|Bonggo Timur','Sarmi|Pantai Barat','Sarmi|Pantai Timur','Sarmi|Pantai Timur Bagian Barat',
'Sarmi|Sarmi','Sarmi|Sarmi Selatan','Sarmi|Sarmi Timur','Sarmi|Tor Atas',
'Supiori|Kepulauan Aruri','Supiori|Supiori Barat','Supiori|Supiori Selatan','Supiori|Supiori Timur','Supiori|Supiori Utara',
'Tolikara|Airgaram','Tolikara|Anawi','Tolikara|Aweku','Tolikara|Bewani','Tolikara|Biuk','Tolikara|Bogonuk','Tolikara|Bokondini',
'Tolikara|Bokoneri','Tolikara|Danime','Tolikara|Dekai','Tolikara|Demba','Tolikara|Dow','Tolikara|Dundu','Tolikara|Egiam',
'Tolikara|Geya','Tolikara|Gika','Tolikara|Gilubandu','Tolikara|Goyage','Tolikara|Gundagi','Tolikara|Kai','Tolikara|Kamboneri',
'Tolikara|Kanggime','Tolikara|Karubaga','Tolikara|Kembu','Tolikara|Kondaga','Tolikara|Kuari','Tolikara|Kubu','Tolikara|Li Anogomma',
'Tolikara|Mbalim Ekare','Tolikara|Mbulman Dua','Tolikara|Nabunage','Tolikara|Nelawi','Tolikara|Numba','Tolikara|Nunggawi',
'Tolikara|Panaga','Tolikara|Poganeri','Tolikara|Tagime','Tolikara|Tegina','Tolikara|Telenggame','Tolikara|Timori','Tolikara|Umagi',
'Tolikara|Wakuwo','Tolikara|Wari','Tolikara|Wenam','Tolikara|Wina','Tolikara|Wonoki','Tolikara|Wugi','Tolikara|Wunim','Tolikara|Yuko',
'Tolikara|Yuneri',
'Waropen|Demba','Waropen|Inggerus','Waropen|Kirihi','Waropen|Masirei','Waropen|Oudate','Waropen|Risei Sayati',
'Waropen|Soyoi Mambai','Waropen|Urei Faisei','Waropen|Wapoga','Waropen|Waropen Bawah','Waropen|Wonti',
'Yahukimo|Amuma','Yahukimo|Anggruk','Yahukimo|Bomela','Yahukimo|Dekai','Yahukimo|Dirwemna','Yahukimo|Duram',
'Yahukimo|Endomen','Yahukimo|Hereapini','Yahukimo|Hilipuk','Yahukimo|Hogio','Yahukimo|Holuon','Yahukimo|Kabianggama',
'Yahukimo|Kayo','Yahukimo|Kona','Yahukimo|Koropun','Yahukimo|Kosarek','Yahukimo|Kurima','Yahukimo|Kwelemdua','Yahukimo|Kwikma',
'Yahukimo|Langda','Yahukimo|Lolat','Yahukimo|Mugi','Yahukimo|Musaik','Yahukimo|Nalca','Yahukimo|Ninia','Yahukimo|Nipsan',
'Yahukimo|Obio','Yahukimo|Panggema','Yahukimo|Pasema','Yahukimo|Pronggoli','Yahukimo|Puldama','Yahukimo|Samenage',
'Yahukimo|Sela','Yahukimo|Seredela','Yahukimo|Silimo','Yahukimo|Soba','Yahukimo|Sobaham','Yahukimo|Soloikma','Yahukimo|Sumo',
'Yahukimo|Suntamon','Yahukimo|Suru Suru','Yahukimo|Talambo','Yahukimo|Tangma','Yahukimo|Ubahak','Yahukimo|Ubalihi',
'Yahukimo|Ukha','Yahukimo|Walma','Yahukimo|Werima','Yahukimo|Wusama','Yahukimo|Yahuliambut','Yahukimo|Yogosem',
'Yalimo|Abenaho','Yalimo|Apalapsili','Yalimo|Benawa','Yalimo|Elelim','Yalimo|Welarek',
'Jayapura Kota|Abepura','Jayapura Kota|Heram','Jayapura Kota|Jayapura Selatan','Jayapura Kota|Jayapura Utara','Jayapura Kota|Muara Tami',
], 'Papua');

echo "Papua Barat & Papua done.\n";
