<?php
function add($f, $entries, $prov) {
    $o = '';
    foreach ($entries as $e) {
        $p = explode('|', $e);
        $k = trim($p[0]); $n = trim($p[1]);
        $s = strtolower(str_replace(' ', '-', $n));
        $s = str_replace(["'", '/', '(', ')', '.'], '', $s);
        $s = str_replace('--', '-', $s); $s = trim($s, '-');
        $ne = str_replace("'", "\'", $n);
        $o .= "        ['slug' => '{$s}', 'nama' => '{$ne}', 'kota' => '{$k}', 'provinsi' => '{$prov}'],\n";
    }
    file_put_contents($f, $o, FILE_APPEND);
}
$f = __DIR__ . '/../config/pseo-kecamatan.php';

// JAWA TIMUR (38 kab/kota, ~666 kecamatan)
add($f, [
'Bangkalan|Arosbaya','Bangkalan|Bangkalan','Bangkalan|Blega','Bangkalan|Burneh','Bangkalan|Galis','Bangkalan|Geger',
'Bangkalan|Kamal','Bangkalan|Klampis','Bangkalan|Kokop','Bangkalan|Konang','Bangkalan|Kwanyar','Bangkalan|Labang',
'Bangkalan|Modung','Bangkalan|Sepulu','Bangkalan|Socah','Bangkalan|Tanah Merah','Bangkalan|Tanjungbumi','Bangkalan|Tragah',
'Banyuwangi|Bangorejo','Banyuwangi|Banyuwangi','Banyuwangi|Cluring','Banyuwangi|Gambiran','Banyuwangi|Genteng',
'Banyuwangi|Giri','Banyuwangi|Glagah','Banyuwangi|Glenmore','Banyuwangi|Kabat','Banyuwangi|Kalibaru',
'Banyuwangi|Kalipuro','Banyuwangi|Licin','Banyuwangi|Muncar','Banyuwangi|Pesanggaran','Banyuwangi|Purwoharjo',
'Banyuwangi|Rogojampi','Banyuwangi|Sempu','Banyuwangi|Siliragung','Banyuwangi|Singojuruh','Banyuwangi|Songgon',
'Banyuwangi|Srono','Banyuwangi|Tegaldlimo','Banyuwangi|Tegalsari','Banyuwangi|Wongsorejo',
'Blitar|Bakung','Blitar|Binangun','Blitar|Doko','Blitar|Gandusari','Blitar|Garum','Blitar|Kademangan','Blitar|Kanigoro',
'Blitar|Kesamben','Blitar|Nglegok','Blitar|Panggungrejo','Blitar|Ponggok','Blitar|Sanankulon','Blitar|Selopuro',
'Blitar|Selorejo','Blitar|Srengat','Blitar|Sutojayan','Blitar|Talun','Blitar|Udanawu','Blitar|Wates','Blitar|Wlingi',
'Blitar|Wonodadi','Blitar|Wonotirto',
'Bojonegoro|Balen','Bojonegoro|Baureno','Bojonegoro|Bojonegoro','Bojonegoro|Bubulan','Bojonegoro|Dander',
'Bojonegoro|Gayam','Bojonegoro|Gondang','Bojonegoro|Kalitidu','Bojonegoro|Kanor','Bojonegoro|Kapas','Bojonegoro|Kasiman',
'Bojonegoro|Kedewan','Bojonegoro|Kedungadem','Bojonegoro|Kepohbaru','Bojonegoro|Malo','Bojonegoro|Margomulyo',
'Bojonegoro|Ngambon','Bojonegoro|Ngasem','Bojonegoro|Ngraho','Bojonegoro|Padangan','Bojonegoro|Purwosari',
'Bojonegoro|Sekar','Bojonegoro|Sugihwaras','Bojonegoro|Sukosewu','Bojonegoro|Sumberrejo','Bojonegoro|Tambakrejo',
'Bojonegoro|Temayang','Bojonegoro|Trucuk',
'Bondowoso|Binakal','Bondowoso|Bondowoso','Bondowoso|Botolinggo','Bondowoso|Cermee','Bondowoso|Curahdami',
'Bondowoso|Grujugan','Bondowoso|Jambe Sari Darus Sholah','Bondowoso|Klabang','Bondowoso|Maesan','Bondowoso|Pakem',
'Bondowoso|Prajekan','Bondowoso|Pujer','Bondowoso|Sempol','Bondowoso|Sukosari','Bondowoso|Sumberwringin',
'Bondowoso|Taman Krocok','Bondowoso|Tamanan','Bondowoso|Tapen','Bondowoso|Tegalampel','Bondowoso|Tenggarang',
'Bondowoso|Tlogosari','Bondowoso|Wonosari','Bondowoso|Wringin',
'Gresik|Balongpanggang','Gresik|Benjeng','Gresik|Bungah','Gresik|Cerme','Gresik|Driyorejo','Gresik|Duduk Sampeyan',
'Gresik|Dukun','Gresik|Gresik','Gresik|Kebomas','Gresik|Kedamean','Gresik|Manyar','Gresik|Menganti','Gresik|Panceng',
'Gresik|Sangkapura','Gresik|Sidayu','Gresik|Tambak','Gresik|Ujung Pangkah','Gresik|Wringinanom',
'Jember|Ajung','Jember|Ambulu','Jember|Arjasa','Jember|Balung','Jember|Bangsalsari','Jember|Gumukmas','Jember|Jelbuk',
'Jember|Jenggawah','Jember|Jombang','Jember|Kalisat','Jember|Kaliwates','Jember|Kencong','Jember|Ledokombo',
'Jember|Mayang','Jember|Mumbulsari','Jember|Pakusari','Jember|Panti','Jember|Patrang','Jember|Puger','Jember|Rambipuji',
'Jember|Semboro','Jember|Silo','Jember|Sukorambi','Jember|Sukowono','Jember|Sumberbaru','Jember|Sumberjambe',
'Jember|Sumbersari','Jember|Tanggul','Jember|Tempurejo','Jember|Umbulsari','Jember|Wuluhan',
'Jombang|Bandar Kedungmulyo','Jombang|Bareng','Jombang|Diwek','Jombang|Gudo','Jombang|Jogoroto','Jombang|Jombang',
'Jombang|Kabuh','Jombang|Kesamben','Jombang|Kudu','Jombang|Megaluh','Jombang|Mojoagung','Jombang|Mojowarno',
'Jombang|Ngoro','Jombang|Ngusikan','Jombang|Perak','Jombang|Peterongan','Jombang|Plandaan','Jombang|Ploso',
'Jombang|Sumobito','Jombang|Tembelang','Jombang|Wonosalam',
'Kediri|Badas','Kediri|Banyakan','Kediri|Gampengrejo','Kediri|Grogol','Kediri|Gurah','Kediri|Kandangan','Kediri|Kandat',
'Kediri|Kayen Kidul','Kediri|Kepung','Kediri|Kras','Kediri|Kunjang','Kediri|Mojo','Kediri|Ngadiluwih','Kediri|Ngancar',
'Kediri|Pagu','Kediri|Papar','Kediri|Pare','Kediri|Plemahan','Kediri|Plosoklaten','Kediri|Puncu','Kediri|Purwoasri',
'Kediri|Ringinrejo','Kediri|Semen','Kediri|Tarokan','Kediri|Wates',
'Lamongan|Babat','Lamongan|Bluluk','Lamongan|Brondong','Lamongan|Deket','Lamongan|Glagah','Lamongan|Kalitengah',
'Lamongan|Karangbinangun','Lamongan|Karanggeneng','Lamongan|Kedungpring','Lamongan|Kembangbahu','Lamongan|Lamongan',
'Lamongan|Laren','Lamongan|Maduran','Lamongan|Mantup','Lamongan|Modo','Lamongan|Ngimbang','Lamongan|Paciran',
'Lamongan|Pucuk','Lamongan|Sambeng','Lamongan|Sarirejo','Lamongan|Sekaran','Lamongan|Solokuro','Lamongan|Sugio',
'Lamongan|Sukodadi','Lamongan|Sukorame','Lamongan|Tikung','Lamongan|Turi',
'Lumajang|Candipuro','Lumajang|Gucialit','Lumajang|Jatiroto','Lumajang|Kedungjajang','Lumajang|Klakah','Lumajang|Kunir',
'Lumajang|Lumajang','Lumajang|Padang','Lumajang|Pasirian','Lumajang|Pasrujambe','Lumajang|Pronojiwo','Lumajang|Randuagung',
'Lumajang|Ranuyoso','Lumajang|Rowokangkung','Lumajang|Senduro','Lumajang|Sukodono','Lumajang|Sumbersuko',
'Lumajang|Tekung','Lumajang|Tempeh','Lumajang|Tempursari','Lumajang|Yosowilangun',
'Madiun|Balerejo','Madiun|Dagangan','Madiun|Dolopo','Madiun|Geger','Madiun|Gemarang','Madiun|Jiwan','Madiun|Kare',
'Madiun|Kebonsari','Madiun|Madiun','Madiun|Mejayan','Madiun|Pilangkenceng','Madiun|Saradan','Madiun|Sawahan',
'Madiun|Wonoasri','Madiun|Wungu',
'Magetan|Barat','Magetan|Bendo','Magetan|Karangrejo','Magetan|Karas','Magetan|Kartoharjo','Magetan|Kawedanan',
'Magetan|Lembeyan','Magetan|Magetan','Magetan|Maospati','Magetan|Ngariboyo','Magetan|Nguntoronadi','Magetan|Panekan',
'Magetan|Parang','Magetan|Plaosan','Magetan|Poncol','Magetan|Sidorejo','Magetan|Sukomoro','Magetan|Takeran',
'Malang|Ampelgading','Malang|Bantur','Malang|Bululawang','Malang|Dampit','Malang|Dau','Malang|Donomulyo','Malang|Gedangan',
'Malang|Gondanglegi','Malang|Jabung','Malang|Kalipare','Malang|Karangploso','Malang|Kasembon','Malang|Kepanjen',
'Malang|Kromengan','Malang|Lawang','Malang|Ngajum','Malang|Ngantang','Malang|Pagak','Malang|Pagelaran','Malang|Pakis',
'Malang|Pakisaji','Malang|Poncokusumo','Malang|Pujon','Malang|Singosari','Malang|Sumbermanjing Wetan','Malang|Sumberpucung',
'Malang|Tajinan','Malang|Tirtoyudo','Malang|Tumpang','Malang|Turen','Malang|Wagir','Malang|Wajak','Malang|Wonosari',
'Mojokerto|Bangsal','Mojokerto|Dawar Blandong','Mojokerto|Dlanggu','Mojokerto|Gedeg','Mojokerto|Gondang','Mojokerto|Jatirejo',
'Mojokerto|Jetis','Mojokerto|Kemlagi','Mojokerto|Kutorejo','Mojokerto|Mojoanyar','Mojokerto|Mojosari','Mojokerto|Ngoro',
'Mojokerto|Pacet','Mojokerto|Pungging','Mojokerto|Puri','Mojokerto|Sooko','Mojokerto|Trawas','Mojokerto|Trowulan',
'Nganjuk|Bagor','Nganjuk|Baron','Nganjuk|Berbek','Nganjuk|Gondang','Nganjuk|Jatikalen','Nganjuk|Kertosono',
'Nganjuk|Lengkong','Nganjuk|Loceret','Nganjuk|Nganjuk','Nganjuk|Ngetos','Nganjuk|Ngluyu','Nganjuk|Ngronggot',
'Nganjuk|Pace','Nganjuk|Patianrowo','Nganjuk|Prambon','Nganjuk|Rejoso','Nganjuk|Sawahan','Nganjuk|Sukomoro',
'Nganjuk|Tanjunganom','Nganjuk|Wilangan',
'Ngawi|Bringin','Ngawi|Geneng','Ngawi|Gerih','Ngawi|Jogorogo','Ngawi|Karanganyar','Ngawi|Karangjati','Ngawi|Kasreman',
'Ngawi|Kedunggalar','Ngawi|Kendal','Ngawi|Kwadungan','Ngawi|Mantingan','Ngawi|Ngawi','Ngawi|Ngrambe','Ngawi|Padas',
'Ngawi|Pangkur','Ngawi|Paron','Ngawi|Pitu','Ngawi|Sine','Ngawi|Widodaren',
'Pacitan|Arjosari','Pacitan|Bandar','Pacitan|Donorojo','Pacitan|Kebonagung','Pacitan|Nawangan','Pacitan|Ngadirojo',
'Pacitan|Pacitan','Pacitan|Pringkuku','Pacitan|Punung','Pacitan|Sudimoro','Pacitan|Tegalombo','Pacitan|Tulakan',
'Pamekasan|Batumarmar','Pamekasan|Galis','Pamekasan|Kadur','Pamekasan|Larangan','Pamekasan|Pademawu','Pamekasan|Pakong',
'Pamekasan|Palengaan','Pamekasan|Pamekasan','Pamekasan|Pasean','Pamekasan|Pegantenan','Pamekasan|Proppo','Pamekasan|Tlanakan',
'Pamekasan|Waru',
'Pasuruan|Bangil','Pasuruan|Beji','Pasuruan|Gempol','Pasuruan|Gondangwetan','Pasuruan|Grati','Pasuruan|Kejayan',
'Pasuruan|Kraton','Pasuruan|Lekok','Pasuruan|Lumbang','Pasuruan|Nguling','Pasuruan|Pandaan','Pasuruan|Pasrepan',
'Pasuruan|Pohjentrek','Pasuruan|Prigen','Pasuruan|Purwodadi','Pasuruan|Purwosari','Pasuruan|Puspo','Pasuruan|Rejoso',
'Pasuruan|Rembang','Pasuruan|Sukorejo','Pasuruan|Tosari','Pasuruan|Tutur','Pasuruan|Winongan','Pasuruan|Wonorejo',
'Ponorogo|Babadan','Ponorogo|Badegan','Ponorogo|Balong','Ponorogo|Bungkal','Ponorogo|Jambon','Ponorogo|Jenangan',
'Ponorogo|Jetis','Ponorogo|Kauman','Ponorogo|Mlarak','Ponorogo|Ngebel','Ponorogo|Ngrayun','Ponorogo|Ponorogo',
'Ponorogo|Pudak','Ponorogo|Pulung','Ponorogo|Sambit','Ponorogo|Sampung','Ponorogo|Sawoo','Ponorogo|Siman',
'Ponorogo|Slahung','Ponorogo|Sooko','Ponorogo|Sukorejo',
'Probolinggo|Bantaran','Probolinggo|Banyuanyar','Probolinggo|Besuk','Probolinggo|Dringu','Probolinggo|Gading',
'Probolinggo|Gending','Probolinggo|Kotaanyar','Probolinggo|Kraksaan','Probolinggo|Krejengan','Probolinggo|Krucil',
'Probolinggo|Kuripan','Probolinggo|Leces','Probolinggo|Lumbang','Probolinggo|Maron','Probolinggo|Paiton',
'Probolinggo|Pajarakan','Probolinggo|Pakuniran','Probolinggo|Sukapura','Probolinggo|Sumber','Probolinggo|Sumberasih',
'Probolinggo|Tegalsiwalan','Probolinggo|Tiris','Probolinggo|Tongas','Probolinggo|Wonomerto',
'Sampang|Banyuates','Sampang|Camplong','Sampang|Jrengik','Sampang|Karangpenang','Sampang|Kedungdung','Sampang|Ketapang',
'Sampang|Omben','Sampang|Robatal','Sampang|Sampang','Sampang|Sokobanah','Sampang|Sreseh','Sampang|Tambelangan',
'Sampang|Torjun',
'Sidoarjo|Balongbendo','Sidoarjo|Buduran','Sidoarjo|Candi','Sidoarjo|Gedangan','Sidoarjo|Jabon','Sidoarjo|Krembung',
'Sidoarjo|Krian','Sidoarjo|Pagerwojo','Sidoarjo|Porong','Sidoarjo|Prambon','Sidoarjo|Sedati','Sidoarjo|Sidoarjo',
'Sidoarjo|Sukodono','Sidoarjo|Taman','Sidoarjo|Tanggulangin','Sidoarjo|Tarik','Sidoarjo|Tulangan','Sidoarjo|Waru',
'Situbondo|Arjasa','Situbondo|Asembagus','Situbondo|Banyuglugur','Situbondo|Banyuputih','Situbondo|Besuki',
'Situbondo|Bungatan','Situbondo|Jangkar','Situbondo|Jatibanteng','Situbondo|Kapongan','Situbondo|Kendit',
'Situbondo|Mangaran','Situbondo|Mlandingan','Situbondo|Panarukan','Situbondo|Panji','Situbondo|Situbondo',
'Situbondo|Suboh','Situbondo|Sumbermalang',
'Sumenep|Ambunten','Sumenep|Arjasa','Sumenep|Batang Batang','Sumenep|Batuan','Sumenep|Batuputih','Sumenep|Bluto',
'Sumenep|Dasuk','Sumenep|Dungkek','Sumenep|Ganding','Sumenep|Gapura','Sumenep|Gayam','Sumenep|Giligenteng',
'Sumenep|Guluk-Guluk','Sumenep|Kalianget','Sumenep|Kangayan','Sumenep|Kota Sumenep','Sumenep|Lenteng','Sumenep|Manding',
'Sumenep|Masalembu','Sumenep|Nonggunong','Sumenep|Pasongsongan','Sumenep|Pragaan','Sumenep|Raas','Sumenep|Rubaru',
'Sumenep|Sapeken','Sumenep|Saronggi','Sumenep|Talango',
'Trenggalek|Bendungan','Trenggalek|Dongko','Trenggalek|Durenan','Trenggalek|Gandusari','Trenggalek|Kampak',
'Trenggalek|Karangan','Trenggalek|Munjungan','Trenggalek|Panggul','Trenggalek|Pogalan','Trenggalek|Pule',
'Trenggalek|Suruh','Trenggalek|Trenggalek','Trenggalek|Tugu','Trenggalek|Watulimo',
'Tuban|Bancar','Tuban|Bangilan','Tuban|Grabagan','Tuban|Jatirogo','Tuban|Jenu','Tuban|Kenduruan','Tuban|Kerek',
'Tuban|Merakurak','Tuban|Montong','Tuban|Palang','Tuban|Parengan','Tuban|Plumpang','Tuban|Rengel','Tuban|Semanding',
'Tuban|Senori','Tuban|Singgahan','Tuban|Soko','Tuban|Tambakboyo','Tuban|Tuban','Tuban|Widang',
'Tulungagung|Bandung','Tulungagung|Besuki','Tulungagung|Boyolangu','Tulungagung|Campurdarat','Tulungagung|Gondang',
'Tulungagung|Kalidawir','Tulungagung|Karangrejo','Tulungagung|Kauman','Tulungagung|Kedungwaru','Tulungagung|Ngantru',
'Tulungagung|Ngunut','Tulungagung|Pagerwojo','Tulungagung|Pakel','Tulungagung|Pucanglaban','Tulungagung|Rejotangan',
'Tulungagung|Sendang','Tulungagung|Sumbergempol','Tulungagung|Tanggunggunung','Tulungagung|Tulungagung',
'Batu|Batu','Batu|Bumiaji','Batu|Junrejo',
'Blitar Kota|Kepanjenkidul','Blitar Kota|Sananwetan','Blitar Kota|Sukorejo',
'Kediri Kota|Kediri','Kediri Kota|Mojoroto','Kediri Kota|Pesantren',
'Madiun Kota|Kartoharjo','Madiun Kota|Manguharjo','Madiun Kota|Taman',
'Malang Kota|Blimbing','Malang Kota|Kedungkandang','Malang Kota|Klojen','Malang Kota|Lowokwaru','Malang Kota|Sukun',
'Mojokerto Kota|Kranggan','Mojokerto Kota|Magersari','Mojokerto Kota|Prajuritkulon',
'Pasuruan Kota|Bugul Kidul','Pasuruan Kota|Gadingrejo','Pasuruan Kota|Panggungrejo','Pasuruan Kota|Purworejo',
'Probolinggo Kota|Kademangan','Probolinggo Kota|Kanigaran','Probolinggo Kota|Kedopok','Probolinggo Kota|Mayangan','Probolinggo Kota|Wonoasih',
'Surabaya|Asemrowo','Surabaya|Benowo','Surabaya|Bubutan','Surabaya|Bulak','Surabaya|Dukuh Pakis','Surabaya|Gayungan',
'Surabaya|Genteng','Surabaya|Gubeng','Surabaya|Gunung Anyar','Surabaya|Jambangan','Surabaya|Karangpilang',
'Surabaya|Kenjeran','Surabaya|Krembangan','Surabaya|Lakarsantri','Surabaya|Mulyorejo','Surabaya|Pabean Cantian',
'Surabaya|Pakal','Surabaya|Rungkut','Surabaya|Sambikerep','Surabaya|Sawahan','Surabaya|Semampir','Surabaya|Simokerto',
'Surabaya|Sukolilo','Surabaya|Sukomanunggal','Surabaya|Tambaksari','Surabaya|Tandes','Surabaya|Tegalsari',
'Surabaya|Tenggilis Mejoyo','Surabaya|Wiyung','Surabaya|Wonocolo','Surabaya|Wonokromo',
], 'Jawa Timur');

echo "Jawa Timur done.\n";
