<?php
function add($f, $entries, $prov) {
    $o = '';
    foreach ($entries as $e) {
        $p = explode('|', $e);
        $k = trim($p[0]); $n = trim($p[1]);
        $s = strtolower(str_replace(' ', '-', $n));
        $s = str_replace(["'", '/', '(', ')', '.'], '', $s);
        $s = str_replace('--', '-', $s); $s = trim($s, '-');
        $ne = str_replace("'", "\'", $n);
        $o .= "        ['slug' => '{$s}', 'nama' => '{$ne}', 'kota' => '{$k}', 'provinsi' => '{$prov}'],\n";
    }
    file_put_contents($f, $o, FILE_APPEND);
}
$f = __DIR__ . '/../config/pseo-kecamatan.php';

// SULAWESI SELATAN (24 kab/kota, ~313 kecamatan)
add($f, [
'Bantaeng|Bantaeng','Bantaeng|Bissappu','Bantaeng|Eremerasa','Bantaeng|Gantarangkeke','Bantaeng|Pa\'jukukang',
'Bantaeng|Sinoa','Bantaeng|Tompobulu','Bantaeng|Uluere',
'Barru|Balusu','Barru|Barru','Barru|Mallusetasi','Barru|Pujananting','Barru|Soppeng Riaja','Barru|Tanete Riaja','Barru|Tanete Rilau',
'Bone|Ajangale','Bone|Amali','Bone|Awangpone','Bone|Barebbo','Bone|Bengo','Bone|Bontocani','Bone|Cenrana','Bone|Cina',
'Bone|Dua Boccoe','Bone|Kahu','Bone|Kajuara','Bone|Lamuru','Bone|Lappariaja','Bone|Libureng','Bone|Mare','Bone|Palakka',
'Bone|Patimpeng','Bone|Ponre','Bone|Salomekko','Bone|Sibulue','Bone|Tanete Riattang','Bone|Tanete Riattang Barat',
'Bone|Tanete Riattang Timur','Bone|Tellu Limpoe','Bone|Tellu Siattinge','Bone|Tonra','Bone|Ulaweng',
'Bulukumba|Bonto Bahari','Bulukumba|Bontotiro','Bulukumba|Bulukumba','Bulukumba|Gantarang','Bulukumba|Hero Lange-Lange',
'Bulukumba|Kajang','Bulukumba|Kindang','Bulukumba|Rilau Ale','Bulukumba|Ujung Bulu','Bulukumba|Ujung Loe',
'Enrekang|Alla','Enrekang|Anggeraja','Enrekang|Baraka','Enrekang|Baroko','Enrekang|Bungin','Enrekang|Buntu Batu',
'Enrekang|Cendana','Enrekang|Curio','Enrekang|Enrekang','Enrekang|Maiwa','Enrekang|Malua','Enrekang|Masalle',
'Gowa|Bajeng','Gowa|Bajeng Barat','Gowa|Barombong','Gowa|Biringbulu','Gowa|Bontolempangan','Gowa|Bontomarannu',
'Gowa|Bontonompo','Gowa|Bontonompo Selatan','Gowa|Bungaya','Gowa|Manuju','Gowa|Pallangga','Gowa|Parangloe',
'Gowa|Parigi','Gowa|Pattallassang','Gowa|Somba Opu','Gowa|Tinggimoncong','Gowa|Tombolo Pao','Gowa|Tompobulu',
'Jeneponto|Arungkeke','Jeneponto|Bangkala','Jeneponto|Bangkala Barat','Jeneponto|Batang','Jeneponto|Binamu',
'Jeneponto|Bontoramba','Jeneponto|Kelara','Jeneponto|Rumbia','Jeneponto|Tamalatea','Jeneponto|Tarowang','Jeneponto|Turatea',
'Kepulauan Selayar|Benteng','Kepulauan Selayar|Bontoharu','Kepulauan Selayar|Bontomanai','Kepulauan Selayar|Bontomatene',
'Kepulauan Selayar|Bontosikuyu','Kepulauan Selayar|Buki','Kepulauan Selayar|Pasilambena','Kepulauan Selayar|Pasimarannu',
'Kepulauan Selayar|Pasimassunggu','Kepulauan Selayar|Pasimassunggu Timur','Kepulauan Selayar|Takabonerate',
'Luwu|Bajo','Luwu|Bajo Barat','Luwu|Bassesangtempe','Luwu|Bassesangtempe Utara','Luwu|Belopa','Luwu|Belopa Utara',
'Luwu|Bua','Luwu|Bua Ponrang','Luwu|Kamanre','Luwu|Lamasi','Luwu|Lamasi Timur','Luwu|Larompong','Luwu|Larompong Selatan',
'Luwu|Latimojong','Luwu|Ponrang','Luwu|Ponrang Selatan','Luwu|Suli','Luwu|Suli Barat','Luwu|Walenrang','Luwu|Walenrang Barat',
'Luwu|Walenrang Timur','Luwu|Walenrang Utara',
'Luwu Timur|Angkona','Luwu Timur|Burau','Luwu Timur|Kalaena','Luwu Timur|Malili','Luwu Timur|Mangkutana','Luwu Timur|Nuha',
'Luwu Timur|Tomoni','Luwu Timur|Tomoni Timur','Luwu Timur|Towuti','Luwu Timur|Wasuponda','Luwu Timur|Wotu',
'Luwu Utara|Baebunta','Luwu Utara|Baebunta Selatan','Luwu Utara|Bone-Bone','Luwu Utara|Limbong','Luwu Utara|Malangke',
'Luwu Utara|Malangke Barat','Luwu Utara|Mappedeceng','Luwu Utara|Masamba','Luwu Utara|Rampi','Luwu Utara|Sabbang',
'Luwu Utara|Sabbang Selatan','Luwu Utara|Seko','Luwu Utara|Sukamaju','Luwu Utara|Tana Lili',
'Maros|Bantimurung','Maros|Bontoa','Maros|Camba','Maros|Cenrana','Maros|Lau','Maros|Mallawa','Maros|Mandai','Maros|Maros Baru',
'Maros|Marusu','Maros|Moncongloe','Maros|Simbang','Maros|Tanralili','Maros|Tompobulu','Maros|Turikale',
'Pangkajene dan Kepulauan|Balocci','Pangkajene dan Kepulauan|Bungoro','Pangkajene dan Kepulauan|Labakkang',
'Pangkajene dan Kepulauan|Liukang Kalmas','Pangkajene dan Kepulauan|Liukang Tangaya','Pangkajene dan Kepulauan|Liukang Tupabbiring',
'Pangkajene dan Kepulauan|Mandalle','Pangkajene dan Kepulauan|Ma\'rang','Pangkajene dan Kepulauan|Minasa Te\'ne',
'Pangkajene dan Kepulauan|Pangkajene','Pangkajene dan Kepulauan|Segeri','Pangkajene dan Kepulauan|Tondong Tallasa',
'Pinrang|Batulappa','Pinrang|Cempa','Pinrang|Duampanua','Pinrang|Lanrisang','Pinrang|Lembang','Pinrang|Mattiro Bulu',
'Pinrang|Mattiro Sompe','Pinrang|Paleteang','Pinrang|Patampanua','Pinrang|Suppa','Pinrang|Tiroang','Pinrang|Watang Sawitto',
'Sidenreng Rappang|Baranti','Sidenreng Rappang|Dua Pitue','Sidenreng Rappang|Kulo','Sidenreng Rappang|Maritengngae',
'Sidenreng Rappang|Panca Lautang','Sidenreng Rappang|Panca Rijang','Sidenreng Rappang|Pitu Raise','Sidenreng Rappang|Pitu Riawa',
'Sidenreng Rappang|Tellu Limpoe','Sidenreng Rappang|Watang Pulu','Sidenreng Rappang|Wattang Sidenreng',
'Sinjai|Bulupoddo','Sinjai|Pulau Sembilan','Sinjai|Sinjai Barat','Sinjai|Sinjai Borong','Sinjai|Sinjai Selatan',
'Sinjai|Sinjai Tengah','Sinjai|Sinjai Timur','Sinjai|Sinjai Utara','Sinjai|Tellu Limpoe',
'Soppeng|Citta','Soppeng|Donri Donri','Soppeng|Ganra','Soppeng|Lalabata','Soppeng|Lili Rilau','Soppeng|Liliraja',
'Soppeng|Mario Riawa','Soppeng|Mario Riwawo',
'Takalar|Galesong','Takalar|Galesong Selatan','Takalar|Galesong Utara','Takalar|Mangarabombang','Takalar|Mappakasunggu',
'Takalar|Patallassang','Takalar|Polombangkeng Selatan','Takalar|Polombangkeng Utara','Takalar|Sanrobone',
'Tana Toraja|Bittuang','Tana Toraja|Bonggakaradeng','Tana Toraja|Gandangbatu Sillanan','Tana Toraja|Kurra','Tana Toraja|Makale',
'Tana Toraja|Makale Selatan','Tana Toraja|Makale Utara','Tana Toraja|Malimbong Balepe','Tana Toraja|Mappak',
'Tana Toraja|Masanda','Tana Toraja|Mengkendek','Tana Toraja|Rano','Tana Toraja|Rantetayo','Tana Toraja|Rembon',
'Tana Toraja|Saluputti','Tana Toraja|Sangalla','Tana Toraja|Sangalla Selatan','Tana Toraja|Sangalla Utara','Tana Toraja|Simbuang',
'Toraja Utara|Awan Rante Karua','Toraja Utara|Balusu','Toraja Utara|Bangkelekila','Toraja Utara|Baruppu','Toraja Utara|Buntao',
'Toraja Utara|Buntu Pepasan','Toraja Utara|Dende Piongan Napo','Toraja Utara|Kapala Pitu','Toraja Utara|Kesu',
'Toraja Utara|Nanggala','Toraja Utara|Rantebua','Toraja Utara|Rantepao','Toraja Utara|Rindingallo','Toraja Utara|Sa\'dan',
'Toraja Utara|Sanggalangi','Toraja Utara|Sesean','Toraja Utara|Sesean Suloara','Toraja Utara|Sopai','Toraja Utara|Tallunglipu',
'Toraja Utara|Tikala','Toraja Utara|Tondon',
'Wajo|Belawa','Wajo|Bola','Wajo|Gilireng','Wajo|Keera','Wajo|Majauleng','Wajo|Maniangpajo','Wajo|Pammana','Wajo|Penrang',
'Wajo|Pitumpanua','Wajo|Sabbangparu','Wajo|Sajoanging','Wajo|Takkalalla','Wajo|Tanasitolo','Wajo|Tempe',
'Makassar|Biringkanaya','Makassar|Bontoala','Makassar|Makassar','Makassar|Mamajang','Makassar|Manggala','Makassar|Mariso',
'Makassar|Panakkukang','Makassar|Rappocini','Makassar|Tallo','Makassar|Tamalanrea','Makassar|Tamalate','Makassar|Ujung Pandang',
'Makassar|Ujung Tanah','Makassar|Wajo',
'Palopo|Bara','Palopo|Mungkajang','Palopo|Sendana','Palopo|Telluwanua','Palopo|Wara','Palopo|Wara Barat',
'Palopo|Wara Selatan','Palopo|Wara Timur','Palopo|Wara Utara',
'Parepare|Bacukiki','Parepare|Bacukiki Barat','Parepare|Soreang','Parepare|Ujung',
], 'Sulawesi Selatan');

// SULAWESI TENGGARA (17 kab/kota, ~219 kecamatan)
add($f, [
'Bombana|Kabaena','Bombana|Kabaena Barat','Bombana|Kabaena Selatan','Bombana|Kabaena Tengah','Bombana|Kabaena Timur',
'Bombana|Kabaena Utara','Bombana|Kepulauan Masaloka Raya','Bombana|Lantari Jaya','Bombana|Mata Oleo','Bombana|Mata Usu',
'Bombana|Poleang','Bombana|Poleang Barat','Bombana|Poleang Selatan','Bombana|Poleang Tengah','Bombana|Poleang Tenggara',
'Bombana|Poleang Timur','Bombana|Poleang Utara','Bombana|Rarowatu','Bombana|Rarowatu Utara','Bombana|Tontonunu',
'Buton|Kapontori','Buton|Lasalimu','Buton|Lasalimu Selatan','Buton|Pasarwajo','Buton|Siotapina','Buton|Wabula','Buton|Wolowa',
'Buton Selatan|Batauga','Buton Selatan|Batu Atas','Buton Selatan|Kadatua','Buton Selatan|Lapandewa','Buton Selatan|Sampolawa',
'Buton Selatan|Siompu','Buton Selatan|Siompu Barat',
'Buton Tengah|Gunung Jaya','Buton Tengah|Lakudo','Buton Tengah|Mawasangka','Buton Tengah|Mawasangka Tengah',
'Buton Tengah|Mawasangka Timur','Buton Tengah|Sangia Wambulu','Buton Tengah|Talaga Raya',
'Buton Utara|Bonegunu','Buton Utara|Kambowa','Buton Utara|Kulisusu','Buton Utara|Kulisusu Barat','Buton Utara|Kulisusu Utara',
'Buton Utara|Wakorumba Utara',
'Kolaka|Baula','Kolaka|Iwoimendaa','Kolaka|Kolaka','Kolaka|Latambaga','Kolaka|Pomalaa','Kolaka|Polinggona','Kolaka|Samaturu',
'Kolaka|Tanggetada','Kolaka|Toari','Kolaka|Watubangga','Kolaka|Wolo','Kolaka|Wundulako',
'Kolaka Timur|Aere','Kolaka Timur|Dangia','Kolaka Timur|Ladongi','Kolaka Timur|Lalolae','Kolaka Timur|Lambandia',
'Kolaka Timur|Loea','Kolaka Timur|Mowewe','Kolaka Timur|Poli Polia','Kolaka Timur|Tinondo','Kolaka Timur|Tirawuta',
'Kolaka Timur|Ueesi','Kolaka Timur|Uluiwoi',
'Kolaka Utara|Batu Putih','Kolaka Utara|Katoi','Kolaka Utara|Kodeoha','Kolaka Utara|Lambai','Kolaka Utara|Lasusua',
'Kolaka Utara|Ngapa','Kolaka Utara|Pakue','Kolaka Utara|Pakue Tengah','Kolaka Utara|Pakue Utara','Kolaka Utara|Porehu',
'Kolaka Utara|Rante Angin','Kolaka Utara|Tiwu','Kolaka Utara|Tolala','Kolaka Utara|Watunohu','Kolaka Utara|Wawo',
'Konawe|Abuki','Konawe|Amonggedo','Konawe|Anggaberi','Konawe|Asinua','Konawe|Besulutu','Konawe|Bondoala','Konawe|Kapoiala',
'Konawe|Konawe','Konawe|Lalonggasumeeto','Konawe|Lambuya','Konawe|Latoma','Konawe|Meluhu','Konawe|Morosi',
'Konawe|Onembute','Konawe|Padangguni','Konawe|Pondidaha','Konawe|Puriala','Konawe|Routa','Konawe|Sampara',
'Konawe|Soropia','Konawe|Tongauna','Konawe|Tongauna Utara','Konawe|Uepai','Konawe|Unaaha','Konawe|Wawonii Barat',
'Konawe|Wawonii Selatan','Konawe|Wawonii Tengah','Konawe|Wawonii Tenggara','Konawe|Wawonii Timur','Konawe|Wawonii Timur Laut',
'Konawe|Wawonii Utara','Konawe|Wawotobi','Konawe|Wonggeduku','Konawe|Wonggeduku Barat',
'Konawe Kepulauan|Wawonii Barat','Konawe Kepulauan|Wawonii Selatan','Konawe Kepulauan|Wawonii Tengah','Konawe Kepulauan|Wawonii Tenggara',
'Konawe Kepulauan|Wawonii Timur','Konawe Kepulauan|Wawonii Timur Laut','Konawe Kepulauan|Wawonii Utara',
'Konawe Selatan|Andoolo','Konawe Selatan|Andoolo Barat','Konawe Selatan|Angata','Konawe Selatan|Baito','Konawe Selatan|Basala',
'Konawe Selatan|Benua','Konawe Selatan|Buke','Konawe Selatan|Kolono','Konawe Selatan|Kolono Timur','Konawe Selatan|Konda',
'Konawe Selatan|Laeya','Konawe Selatan|Lainea','Konawe Selatan|Lalembuu','Konawe Selatan|Landono','Konawe Selatan|Laonti',
'Konawe Selatan|Moramo','Konawe Selatan|Moramo Utara','Konawe Selatan|Mowila','Konawe Selatan|Palangga','Konawe Selatan|Palangga Selatan',
'Konawe Selatan|Ranomeeto','Konawe Selatan|Ranomeeto Barat','Konawe Selatan|Tinanggea','Konawe Selatan|Wolasi',
'Konawe Utara|Andowia','Konawe Utara|Asera','Konawe Utara|Landawe','Konawe Utara|Langgingima','Konawe Utara|Lasolo',
'Konawe Utara|Lasolo Kepulauan','Konawe Utara|Lembo','Konawe Utara|Molawe','Konawe Utara|Motui','Konawe Utara|Oheo',
'Konawe Utara|Sawa','Konawe Utara|Wawolesea','Konawe Utara|Wiwirano',
'Muna|Batalaiworu','Muna|Batukara','Muna|Bone','Muna|Duruka','Muna|Kabangka','Muna|Kabawo','Muna|Katobu','Muna|Kontu Kowuna',
'Muna|Kontunaga','Muna|Lasalepa','Muna|Lohia','Muna|Maligano','Muna|Marobo','Muna|Napabalano','Muna|Parigi','Muna|Pasir Putih',
'Muna|Pasi Kolaga','Muna|Sawerigadi','Muna|Tiworo Kepulauan','Muna|Tiworo Selatan','Muna|Tiworo Tengah','Muna|Tiworo Utara',
'Muna|Tongkuno','Muna|Tongkuno Selatan','Muna|Towea','Muna|Wa Daga','Muna|Watopute',
'Muna Barat|Barangka','Muna Barat|Kusambi','Muna Barat|Lawa','Muna Barat|Maginti','Muna Barat|Napano Kusambi',
'Muna Barat|Sawerigadi','Muna Barat|Tiworo Kepulauan','Muna Barat|Tiworo Selatan','Muna Barat|Tiworo Tengah','Muna Barat|Tiworo Utara',
'Muna Barat|Wa Daga',
'Wakatobi|Binongko','Wakatobi|Kaledupa','Wakatobi|Kaledupa Selatan','Wakatobi|Togo Binongko','Wakatobi|Tomia',
'Wakatobi|Tomia Timur','Wakatobi|Wangi-Wangi','Wakatobi|Wangi-Wangi Selatan',
'Bau-Bau|Batupoaro','Bau-Bau|Betoambari','Bau-Bau|Bungi','Bau-Bau|Kokalukuna','Bau-Bau|Lea-Lea','Bau-Bau|Murhum',
'Bau-Bau|Sorawolio','Bau-Bau|Wolio',
'Kendari|Abeli','Kendari|Baruga','Kendari|Kadia','Kendari|Kambu','Kendari|Kendari','Kendari|Kendari Barat','Kendari|Mandonga',
'Kendari|Nambo','Kendari|Poasia','Kendari|Puuwatu','Kendari|Wua-Wua',
], 'Sulawesi Tenggara');

echo "Sulawesi Selatan & Tenggara done.\n";
