<?php
function add($f, $entries, $prov) {
    $o = '';
    foreach ($entries as $e) {
        $p = explode('|', $e);
        $k = trim($p[0]); $n = trim($p[1]);
        $s = strtolower(str_replace(' ', '-', $n));
        $s = str_replace(["'", '/', '(', ')', '.'], '', $s);
        $s = str_replace('--', '-', $s); $s = trim($s, '-');
        $ne = str_replace("'", "\'", $n);
        $o .= "        ['slug' => '{$s}', 'nama' => '{$ne}', 'kota' => '{$k}', 'provinsi' => '{$prov}'],\n";
    }
    file_put_contents($f, $o, FILE_APPEND);
}
$f = __DIR__ . '/../config/pseo-kecamatan.php';

// SUMATERA BARAT (19 kab/kota, ~179 kecamatan)
add($f, [
'Agam|Ampek Nagari','Agam|Banuhampu','Agam|Baso','Agam|Candung','Agam|IV Angkat Candung','Agam|IV Koto',
'Agam|Kamang Magek','Agam|Lubuk Basung','Agam|Malalak','Agam|Matur','Agam|Palembayan','Agam|Palupuh',
'Agam|Sungai Pua','Agam|Tanjung Mutiara','Agam|Tanjung Raya','Agam|Tilatang Kamang',
'Dharmasraya|Asam Jujuhan','Dharmasraya|Koto Baru','Dharmasraya|Koto Besar','Dharmasraya|Koto Salak',
'Dharmasraya|Padang Laweh','Dharmasraya|Pulau Punjung','Dharmasraya|Sembilan Koto','Dharmasraya|Sitiung',
'Dharmasraya|Sungai Rumbai','Dharmasraya|Timpeh','Dharmasraya|Tiumang',
'Kepulauan Mentawai|Pagai Selatan','Kepulauan Mentawai|Pagai Utara','Kepulauan Mentawai|Siberut Barat',
'Kepulauan Mentawai|Siberut Barat Daya','Kepulauan Mentawai|Siberut Selatan','Kepulauan Mentawai|Siberut Tengah',
'Kepulauan Mentawai|Siberut Utara','Kepulauan Mentawai|Sikakap','Kepulauan Mentawai|Sipora Selatan',
'Kepulauan Mentawai|Sipora Utara',
'Lima Puluh Kota|Akabiluru','Lima Puluh Kota|Bukit Barisan','Lima Puluh Kota|Guguak','Lima Puluh Kota|Gunuang Omeh',
'Lima Puluh Kota|Harau','Lima Puluh Kota|Kapur IX','Lima Puluh Kota|Lareh Sago Halaban','Lima Puluh Kota|Luak',
'Lima Puluh Kota|Mungka','Lima Puluh Kota|Pangkalan Koto Baru','Lima Puluh Kota|Payakumbuh','Lima Puluh Kota|Situjuah Limo Nagari',
'Lima Puluh Kota|Suliki',
'Padang Pariaman|2x11 Enam Lingkung','Padang Pariaman|2x11 Kayu Tanam','Padang Pariaman|Batang Anai',
'Padang Pariaman|Batang Gasan','Padang Pariaman|Enam Lingkung','Padang Pariaman|IV Koto Aur Malintang',
'Padang Pariaman|Lubuk Alung','Padang Pariaman|Nan Sabaris','Padang Pariaman|Padang Sago','Padang Pariaman|Patamuan',
'Padang Pariaman|Sintuak Toboh Gadang','Padang Pariaman|Sungai Geringging','Padang Pariaman|Sungai Limau',
'Padang Pariaman|VII Koto Sungai Sarik','Padang Pariaman|V Koto Kampung Dalam','Padang Pariaman|V Koto Timur',
'Pasaman|Bonjol','Pasaman|Duo Koto','Pasaman|Lubuk Sikaping','Pasaman|Mapat Tunggul','Pasaman|Mapat Tunggul Selatan',
'Pasaman|Padang Gelugur','Pasaman|Panti','Pasaman|Rao','Pasaman|Rao Selatan','Pasaman|Rao Utara','Pasaman|Simpang Alahan Mati',
'Pasaman|Tigo Nagari',
'Pasaman Barat|Gunung Tuleh','Pasaman Barat|Kinali','Pasaman Barat|Koto Balingka','Pasaman Barat|Lembah Melintang',
'Pasaman Barat|Luhak Nan Duo','Pasaman Barat|Pasaman','Pasaman Barat|Ranah Batahan','Pasaman Barat|Sasak Ranah Pasisie',
'Pasaman Barat|Sei Beremas','Pasaman Barat|Sungai Aur','Pasaman Barat|Talamau',
'Pesisir Selatan|Airpura','Pesisir Selatan|Basa Ampek Balai Tapan','Pesisir Selatan|Batang Kapas','Pesisir Selatan|Bayang',
'Pesisir Selatan|IV Jurai','Pesisir Selatan|IV Nagari Bayang Utara','Pesisir Selatan|Koto XI Tarusan',
'Pesisir Selatan|Lengayang','Pesisir Selatan|Linggo Sari Baganti','Pesisir Selatan|Lunang','Pesisir Selatan|Pancung Soal',
'Pesisir Selatan|Ranah Ampek Hulu Tapan','Pesisir Selatan|Ranah Pesisir','Pesisir Selatan|Silaut','Pesisir Selatan|Sutera',
'Sijunjung|IV Nagari','Sijunjung|Kamang Baru','Sijunjung|Koto VII','Sijunjung|Kupitan','Sijunjung|Lubuak Tarok',
'Sijunjung|Sijunjung','Sijunjung|Sumpur Kudus','Sijunjung|Tanjung Gadang',
'Solok|Bukit Sundi','Solok|Danau Kembar','Solok|Gunung Talang','Solok|Hiliran Gumanti','Solok|IX Koto Sungai Lasi',
'Solok|Junjung Sirih','Solok|Kubung','Solok|Lembah Gumanti','Solok|Lembang Jaya','Solok|Pantai Cermin',
'Solok|Payung Sekaki','Solok|Tigo Lurah','Solok|X Koto Diatas','Solok|X Koto Singkarak',
'Solok Selatan|Koto Parik Gadang Diateh','Solok Selatan|Pauh Duo','Solok Selatan|Sangir','Solok Selatan|Sangir Balai Janggo',
'Solok Selatan|Sangir Batang Hari','Solok Selatan|Sangir Jujuan','Solok Selatan|Sungai Pagu',
'Tanah Datar|Batipuh','Tanah Datar|Batipuh Selatan','Tanah Datar|Lima Kaum','Tanah Datar|Lintau Buo',
'Tanah Datar|Lintau Buo Utara','Tanah Datar|Padang Ganting','Tanah Datar|Pariangan','Tanah Datar|Rambatan',
'Tanah Datar|Salimpaung','Tanah Datar|Sepuluh Koto','Tanah Datar|Sungai Tarab','Tanah Datar|Sungayang',
'Tanah Datar|Tanjung Baru','Tanah Datar|Tanjung Emas',
'Bukittinggi|Aur Birugo Tigo Baleh','Bukittinggi|Guguk Panjang','Bukittinggi|Mandiangin Koto Selayan',
'Padang|Bungus Teluk Kabung','Padang|Koto Tangah','Padang|Kuranji','Padang|Lubuk Begalung','Padang|Lubuk Kilangan',
'Padang|Nanggalo','Padang|Padang Barat','Padang|Padang Selatan','Padang|Padang Timur','Padang|Padang Utara','Padang|Pauh',
'Padang Panjang|Padang Panjang Barat','Padang Panjang|Padang Panjang Timur',
'Pariaman|Pariaman Selatan','Pariaman|Pariaman Tengah','Pariaman|Pariaman Timur','Pariaman|Pariaman Utara',
'Payakumbuh|Lamposi Tigo Nagori','Payakumbuh|Payakumbuh Barat','Payakumbuh|Payakumbuh Selatan',
'Payakumbuh|Payakumbuh Timur','Payakumbuh|Payakumbuh Utara',
'Sawahlunto|Barangin','Sawahlunto|Lembah Segar','Sawahlunto|Silungkang','Sawahlunto|Talawi',
'Solok Kota|Lubuk Sikarah','Solok Kota|Tanjung Harapan',
], 'Sumatera Barat');

// RIAU (12 kab/kota, ~178 kecamatan)
add($f, [
'Bengkalis|Bandar Laksamana','Bengkalis|Bantan','Bengkalis|Bathin Solapan','Bengkalis|Bengkalis',
'Bengkalis|Bukit Batu','Bengkalis|Mandau','Bengkalis|Pinggir','Bengkalis|Rupat','Bengkalis|Rupat Utara',
'Bengkalis|Siak Kecil','Bengkalis|Talang Muandau',
'Indragiri Hilir|Batang Tuaka','Indragiri Hilir|Concong','Indragiri Hilir|Enok','Indragiri Hilir|Gaung',
'Indragiri Hilir|Gaung Anak Serka','Indragiri Hilir|Kateman','Indragiri Hilir|Kempas','Indragiri Hilir|Kemuning',
'Indragiri Hilir|Keritang','Indragiri Hilir|Kuala Indragiri','Indragiri Hilir|Mandah','Indragiri Hilir|Pelangiran',
'Indragiri Hilir|Pulau Burung','Indragiri Hilir|Reteh','Indragiri Hilir|Sungai Batang','Indragiri Hilir|Tanah Merah',
'Indragiri Hilir|Teluk Belengkong','Indragiri Hilir|Tembilahan','Indragiri Hilir|Tembilahan Hulu','Indragiri Hilir|Tempuling',
'Indragiri Hulu|Batang Cenaku','Indragiri Hulu|Batang Gansal','Indragiri Hulu|Batang Peranap','Indragiri Hulu|Kelayang',
'Indragiri Hulu|Kuala Cenaku','Indragiri Hulu|Lirik','Indragiri Hulu|Lubuk Batu Jaya','Indragiri Hulu|Pasir Penyu',
'Indragiri Hulu|Peranap','Indragiri Hulu|Rakit Kulim','Indragiri Hulu|Rengat','Indragiri Hulu|Rengat Barat',
'Indragiri Hulu|Seberida','Indragiri Hulu|Sungai Lala',
'Kampar|Bangkinang','Kampar|Bangkinang Kota','Kampar|Gunung Sahilan','Kampar|Kampar','Kampar|Kampar Kiri',
'Kampar|Kampar Kiri Hilir','Kampar|Kampar Kiri Hulu','Kampar|Kampar Kiri Tengah','Kampar|Kampar Utara',
'Kampar|Koto Kampar Hulu','Kampar|Kuok','Kampar|Perhentian Raja','Kampar|Rumbio Jaya','Kampar|Salo',
'Kampar|Siak Hulu','Kampar|Tambang','Kampar|Tapung','Kampar|Tapung Hilir','Kampar|Tapung Hulu','Kampar|XIII Koto Kampar',
'Kepulauan Meranti|Merbau','Kepulauan Meranti|Pulau Merbau','Kepulauan Meranti|Rangsang','Kepulauan Meranti|Rangsang Barat',
'Kepulauan Meranti|Rangsang Pesisir','Kepulauan Meranti|Tasik Putri Puyu','Kepulauan Meranti|Tebing Tinggi',
'Kepulauan Meranti|Tebing Tinggi Barat','Kepulauan Meranti|Tebing Tinggi Timur',
'Kuantan Singingi|Benai','Kuantan Singingi|Cerenti','Kuantan Singingi|Gunung Toar','Kuantan Singingi|Hulu Kuantan',
'Kuantan Singingi|Inuman','Kuantan Singingi|Kuantan Hilir','Kuantan Singingi|Kuantan Hilir Seberang','Kuantan Singingi|Kuantan Mudik',
'Kuantan Singingi|Kuantan Tengah','Kuantan Singingi|Logas Tanah Darat','Kuantan Singingi|Pangean','Kuantan Singingi|Pucuk Rantau',
'Kuantan Singingi|Sentajo Raya','Kuantan Singingi|Singingi','Kuantan Singingi|Singingi Hilir',
'Pelalawan|Bandar Petalangan','Pelalawan|Bandar Sei Kijang','Pelalawan|Bunut','Pelalawan|Kerumutan','Pelalawan|Kuala Kampar',
'Pelalawan|Langgam','Pelalawan|Pangkalan Kerinci','Pelalawan|Pangkalan Kuras','Pelalawan|Pangkalan Lesung',
'Pelalawan|Pelalawan','Pelalawan|Teluk Meranti','Pelalawan|Ukui',
'Rokan Hilir|Bagan Sinembah','Rokan Hilir|Bagan Sinembah Raya','Rokan Hilir|Balai Jaya','Rokan Hilir|Bangko',
'Rokan Hilir|Bangko Pusako','Rokan Hilir|Batu Hampar','Rokan Hilir|Kubu','Rokan Hilir|Kubu Babussalam',
'Rokan Hilir|Pasir Limau Kapas','Rokan Hilir|Pekaitan','Rokan Hilir|Pujud','Rokan Hilir|Rantau Kopar',
'Rokan Hilir|Rimba Melintang','Rokan Hilir|Simpang Kanan','Rokan Hilir|Sinaboi','Rokan Hilir|Tanah Putih',
'Rokan Hilir|Tanah Putih Tanjung Melawan',
'Rokan Hulu|Bangun Purba','Rokan Hulu|Bonai Darussalam','Rokan Hulu|Kabun','Rokan Hulu|Kepenuhan','Rokan Hulu|Kepenuhan Hulu',
'Rokan Hulu|Kunto Darussalam','Rokan Hulu|Pagaran Tapah Darussalam','Rokan Hulu|Pendalian IV Koto','Rokan Hulu|Rambah',
'Rokan Hulu|Rambah Hilir','Rokan Hulu|Rambah Samo','Rokan Hulu|Rokan IV Koto','Rokan Hulu|Tambusai','Rokan Hulu|Tambusai Utara',
'Rokan Hulu|Tandun','Rokan Hulu|Ujung Batu',
'Siak|Bunga Raya','Siak|Dayun','Siak|Kandis','Siak|Kerinci Kanan','Siak|Koto Gasib','Siak|Lubuk Dalam',
'Siak|Mempura','Siak|Minas','Siak|Pusako','Siak|Sabak Auh','Siak|Siak','Siak|Sungai Apit','Siak|Sungai Mandau',
'Siak|Tualang',
'Dumai|Bukit Kapur','Dumai|Dumai Barat','Dumai|Dumai Kota','Dumai|Dumai Selatan','Dumai|Dumai Timur',
'Dumai|Medang Kampai','Dumai|Sungai Sembilan',
'Pekanbaru|Binawidya','Pekanbaru|Bukit Raya','Pekanbaru|Kulim','Pekanbaru|Lima Puluh','Pekanbaru|Marpoyan Damai',
'Pekanbaru|Payung Sekaki','Pekanbaru|Pekanbaru Kota','Pekanbaru|Rumbai','Pekanbaru|Rumbai Barat',
'Pekanbaru|Rumbai Timur','Pekanbaru|Sail','Pekanbaru|Senapelan','Pekanbaru|Sukajadi','Pekanbaru|Tenayan Raya',
'Pekanbaru|Tuah Madani',
], 'Riau');

// JAMBI (11 kab/kota, ~141 kecamatan)
add($f, [
'Batanghari|Bajubang','Batanghari|Batin XXIV','Batanghari|Maro Sebo Ilir','Batanghari|Maro Sebo Ulu',
'Batanghari|Mersam','Batanghari|Muara Bulian','Batanghari|Muara Tembesi','Batanghari|Pemayung',
'Bungo|Bathin II Babeko','Bungo|Bathin II Pelayang','Bungo|Bathin III','Bungo|Bathin III Ulu','Bungo|Bungo Dani',
'Bungo|Jujuhan','Bungo|Jujuhan Ilir','Bungo|Limbur Lubuk Mengkuang','Bungo|Muko-Muko Bathin VII',
'Bungo|Pasar Jambi','Bungo|Pasar Muara Bungo','Bungo|Pelepat','Bungo|Pelepat Ilir','Bungo|Rantau Pandan',
'Bungo|Rimbo Tengah','Bungo|Tanah Sepenggal','Bungo|Tanah Sepenggal Lintas','Bungo|Tanah Tumbuh',
'Jambi Kota|Alam Barajo','Jambi Kota|Danau Sipin','Jambi Kota|Danau Teluk','Jambi Kota|Jambi Selatan',
'Jambi Kota|Jambi Timur','Jambi Kota|Jelutung','Jambi Kota|Kota Baru','Jambi Kota|Pasar Jambi','Jambi Kota|Pelayangan',
'Jambi Kota|Telanaipura',
'Kerinci|Air Hangat','Kerinci|Air Hangat Barat','Kerinci|Air Hangat Timur','Kerinci|Batang Merangin','Kerinci|Bukitkerman',
'Kerinci|Danau Kerinci','Kerinci|Danau Kerinci Barat','Kerinci|Depati Tujuh','Kerinci|Gunung Kerinci','Kerinci|Gunung Raya',
'Kerinci|Gunung Tujuh','Kerinci|Kayu Aro','Kerinci|Kayu Aro Barat','Kerinci|Keliling Danau','Kerinci|Sitinjau Laut',
'Kerinci|Siulak','Kerinci|Siulak Mukai',
'Merangin|Bangko','Merangin|Bangko Barat','Merangin|Batang Masumai','Merangin|Jangkat','Merangin|Jangkat Timur',
'Merangin|Lembah Masurai','Merangin|Margo Tabir','Merangin|Muara Siau','Merangin|Nalo Tantan','Merangin|Pamenang',
'Merangin|Pamenang Barat','Merangin|Pamenang Selatan','Merangin|Pangkalan Jambu','Merangin|Renah Pamenang',
'Merangin|Renah Pembarap','Merangin|Sungai Manau','Merangin|Tabir','Merangin|Tabir Barat','Merangin|Tabir Ilir',
'Merangin|Tabir Lintas','Merangin|Tabir Selatan','Merangin|Tabir Timur','Merangin|Tabir Ulu','Merangin|Tiang Pumpung',
'Muaro Jambi|Bahar Selatan','Muaro Jambi|Bahar Utara','Muaro Jambi|Jambi Luar Kota','Muaro Jambi|Kumpeh',
'Muaro Jambi|Kumpeh Ulu','Muaro Jambi|Maro Sebo','Muaro Jambi|Mestong','Muaro Jambi|Sekernan','Muaro Jambi|Sungai Bahar',
'Muaro Jambi|Sungai Gelam','Muaro Jambi|Taman Rajo',
'Sarolangun|Air Hitam','Sarolangun|Batang Asai','Sarolangun|Bathin VIII','Sarolangun|Cermin Nan Gedang','Sarolangun|Limun',
'Sarolangun|Mandiangin','Sarolangun|Pauh','Sarolangun|Pelawan','Sarolangun|Sarolangun','Sarolangun|Singkut',
'Tanjung Jabung Barat|Batang Asam','Tanjung Jabung Barat|Betara','Tanjung Jabung Barat|Bram Itam','Tanjung Jabung Barat|Kuala Betara',
'Tanjung Jabung Barat|Merlung','Tanjung Jabung Barat|Muara Papalik','Tanjung Jabung Barat|Pengabuan',
'Tanjung Jabung Barat|Renah Mendaluh','Tanjung Jabung Barat|Seberang Kota','Tanjung Jabung Barat|Senyerang',
'Tanjung Jabung Barat|Tebing Tinggi','Tanjung Jabung Barat|Tungkal Ilir','Tanjung Jabung Barat|Tungkal Ulu',
'Tanjung Jabung Timur|Berbak','Tanjung Jabung Timur|Dendang','Tanjung Jabung Timur|Geragai','Tanjung Jabung Timur|Kuala Jambi',
'Tanjung Jabung Timur|Mendahara','Tanjung Jabung Timur|Mendahara Ulu','Tanjung Jabung Timur|Muara Sabak Barat',
'Tanjung Jabung Timur|Muara Sabak Timur','Tanjung Jabung Timur|Nipah Panjang','Tanjung Jabung Timur|Rantau Rasau',
'Tanjung Jabung Timur|Sadu',
'Tebo|Muara Tabir','Tebo|Rimbo Bujang','Tebo|Rimbo Ilir','Tebo|Rimbo Ulu','Tebo|Serai Serumpun',
'Tebo|Sumay','Tebo|Tebo Ilir','Tebo|Tebo Tengah','Tebo|Tebo Ulu','Tebo|Tengah Ilir','Tebo|VII Koto','Tebo|VII Koto Ilir',
'Sungai Penuh|Hamparan Rawang','Sungai Penuh|Koto Baru','Sungai Penuh|Kumun Debai','Sungai Penuh|Pesisir Bukit',
'Sungai Penuh|Pondok Tinggi','Sungai Penuh|Sungai Bungkal','Sungai Penuh|Sungai Penuh','Sungai Penuh|Tanah Kampung',
], 'Jambi');

// SUMATERA SELATAN (17 kab/kota, ~241 kecamatan)
add($f, [
'Banyuasin|Air Kumbang','Banyuasin|Air Salek','Banyuasin|Banyuasin I','Banyuasin|Banyuasin II','Banyuasin|Banyuasin III',
'Banyuasin|Betung','Banyuasin|Karang Agung Ilir','Banyuasin|Makarti Jaya','Banyuasin|Muara Padang','Banyuasin|Muara Sugihan',
'Banyuasin|Muara Telang','Banyuasin|Pulau Rimau','Banyuasin|Rambutan','Banyuasin|Rantau Bayur','Banyuasin|Selat Penuguan',
'Banyuasin|Sembawa','Banyuasin|Suak Tapeh','Banyuasin|Sumber Marga Telang','Banyuasin|Talang Kelapa','Banyuasin|Tanjung Lago',
'Banyuasin|Tungkal Ilir',
'Empat Lawang|Lintang Kanan','Empat Lawang|Muara Pinang','Empat Lawang|Pasemah Air Keruh','Empat Lawang|Pendopo',
'Empat Lawang|Pendopo Barat','Empat Lawang|Saling','Empat Lawang|Sikap Dalam','Empat Lawang|Talang Padang',
'Empat Lawang|Tebing Tinggi','Empat Lawang|Ulu Musi',
'Lahat|Gumay Talang','Lahat|Gumay Ulu','Lahat|Jarai','Lahat|Kikim Barat','Lahat|Kikim Selatan','Lahat|Kikim Tengah',
'Lahat|Kikim Timur','Lahat|Kota Agung','Lahat|Lahat','Lahat|Lahat Selatan','Lahat|Merapi Barat','Lahat|Merapi Selatan',
'Lahat|Merapi Timur','Lahat|Muarapayang','Lahat|Mulak Sebingkai','Lahat|Mulak Ulu','Lahat|Pagar Gunung',
'Lahat|Pajar Bulan','Lahat|Pseksu','Lahat|Pulau Pinang','Lahat|Sukamerindu','Lahat|Tanjung Sakti Pumi',
'Lahat|Tanjung Sakti Pumu','Lahat|Tanjung Tebat',
'Muara Enim|Belida Darat','Muara Enim|Belimbing','Muara Enim|Benakat','Muara Enim|Embat Petar','Muara Enim|Gelumbang',
'Muara Enim|Gunung Megang','Muara Enim|Kelekar','Muara Enim|Lawang Kidul','Muara Enim|Lembak','Muara Enim|Lubai',
'Muara Enim|Lubai Ulu','Muara Enim|Muara Belida','Muara Enim|Muara Enim','Muara Enim|Panang Enim','Muara Enim|Rambang',
'Muara Enim|Rambang Dangku','Muara Enim|Semende Darat Laut','Muara Enim|Semende Darat Tengah','Muara Enim|Semende Darat Ulu',
'Muara Enim|Sungai Rotan','Muara Enim|Tanjung Agung','Muara Enim|Ujan Mas',
'Musi Banyuasin|Babat Supat','Musi Banyuasin|Babat Toman','Musi Banyuasin|Batang Hari Leko','Musi Banyuasin|Bayung Lencir',
'Musi Banyuasin|Jirak Jaya','Musi Banyuasin|Keluang','Musi Banyuasin|Lais','Musi Banyuasin|Lalan','Musi Banyuasin|Lawang Wetan',
'Musi Banyuasin|Plakat Tinggi','Musi Banyuasin|Sanga Desa','Musi Banyuasin|Sekayu','Musi Banyuasin|Sungai Keruh',
'Musi Banyuasin|Sungai Lilin','Musi Banyuasin|Tungkal Jaya',
'Musi Rawas|Bulang Tengah Suku Ulu','Musi Rawas|Jaya Loka','Musi Rawas|Megang Sakti','Musi Rawas|Muara Beliti',
'Musi Rawas|Muara Kelingi','Musi Rawas|Muara Lakitan','Musi Rawas|Purwodadi','Musi Rawas|Selangit',
'Musi Rawas|Suku Tengah Lakitan Ulu Terawas','Musi Rawas|Sumber Harta','Musi Rawas|Tiang Pumpung Kepungut',
'Musi Rawas|Tuah Negeri','Musi Rawas|Tugumulyo','Musi Rawas|Ulu Rawas',
'Musi Rawas Utara|Karang Dapo','Musi Rawas Utara|Karang Jaya','Musi Rawas Utara|Nibung','Musi Rawas Utara|Rawas Ilir',
'Musi Rawas Utara|Rawas Ulu','Musi Rawas Utara|Rupit','Musi Rawas Utara|Ulu Rawas',
'Ogan Ilir|Indralaya','Ogan Ilir|Indralaya Selatan','Ogan Ilir|Indralaya Utara','Ogan Ilir|Kandis','Ogan Ilir|Lubuk Keliat',
'Ogan Ilir|Muara Kuang','Ogan Ilir|Pemulutan','Ogan Ilir|Pemulutan Barat','Ogan Ilir|Pemulutan Selatan',
'Ogan Ilir|Rambang Kuang','Ogan Ilir|Rantau Alai','Ogan Ilir|Rantau Panjang','Ogan Ilir|Sungai Pinang',
'Ogan Ilir|Tanjung Batu','Ogan Ilir|Tanjung Raja',
'Ogan Komering Ilir|Air Sugihan','Ogan Komering Ilir|Cengal','Ogan Komering Ilir|Jejawi','Ogan Komering Ilir|Kayu Agung',
'Ogan Komering Ilir|Lempuing','Ogan Komering Ilir|Lempuing Jaya','Ogan Komering Ilir|Mesuji','Ogan Komering Ilir|Mesuji Makmur',
'Ogan Komering Ilir|Mesuji Raya','Ogan Komering Ilir|Pampangan','Ogan Komering Ilir|Pangkalan Lampam',
'Ogan Komering Ilir|Pedamaran','Ogan Komering Ilir|Pedamaran Timur','Ogan Komering Ilir|Sirah Pulau Padang',
'Ogan Komering Ilir|Sungai Menang','Ogan Komering Ilir|Tanjung Lubuk','Ogan Komering Ilir|Teluk Gelam',
'Ogan Komering Ilir|Tulung Selapan',
'Ogan Komering Ulu|Baturaja Barat','Ogan Komering Ulu|Baturaja Timur','Ogan Komering Ulu|Lengkiti',
'Ogan Komering Ulu|Lubuk Batang','Ogan Komering Ulu|Lubuk Raja','Ogan Komering Ulu|Muara Jaya',
'Ogan Komering Ulu|Pengandonan','Ogan Komering Ulu|Peninjauan','Ogan Komering Ulu|Semidang Aji',
'Ogan Komering Ulu|Sinar Peninjauan','Ogan Komering Ulu|Sosoh Buay Rayap','Ogan Komering Ulu|Ulu Ogan',
'Ogan Komering Ulu Timur|Belitang','Ogan Komering Ulu Timur|Belitang II','Ogan Komering Ulu Timur|Belitang III',
'Ogan Komering Ulu Timur|Belitang Jaya','Ogan Komering Ulu Timur|Belitang Madang Raya','Ogan Komering Ulu Timur|Belitang Mulya',
'Ogan Komering Ulu Timur|Buay Madang','Ogan Komering Ulu Timur|Buay Madang Timur','Ogan Komering Ulu Timur|Buay Pemuka Bangsa Raja',
'Ogan Komering Ulu Timur|Buay Pemuka Peliung','Ogan Komering Ulu Timur|Bunga Mayang','Ogan Komering Ulu Timur|Cempaka',
'Ogan Komering Ulu Timur|Jayapura','Ogan Komering Ulu Timur|Madang Suku I','Ogan Komering Ulu Timur|Madang Suku II',
'Ogan Komering Ulu Timur|Madang Suku III','Ogan Komering Ulu Timur|Martapura','Ogan Komering Ulu Timur|Semendawai Barat',
'Ogan Komering Ulu Timur|Semendawai Suku III','Ogan Komering Ulu Timur|Semendawai Timur',
'Ogan Komering Ulu Selatan|Banding Agung','Ogan Komering Ulu Selatan|Buana Pemaca','Ogan Komering Ulu Selatan|Buay Pemaca',
'Ogan Komering Ulu Selatan|Buay Rawan','Ogan Komering Ulu Selatan|Buay Runjung','Ogan Komering Ulu Selatan|Buay Sandang Aji',
'Ogan Komering Ulu Selatan|Kisam Ilir','Ogan Komering Ulu Selatan|Kisam Tinggi','Ogan Komering Ulu Selatan|Mekakau Ilir',
'Ogan Komering Ulu Selatan|Muaradua','Ogan Komering Ulu Selatan|Muaradua Kisam','Ogan Komering Ulu Selatan|Pulau Beringin',
'Ogan Komering Ulu Selatan|Runjung Agung','Ogan Komering Ulu Selatan|Simpang','Ogan Komering Ulu Selatan|Sindang Danau',
'Ogan Komering Ulu Selatan|Sungai Are','Ogan Komering Ulu Selatan|Tiga Dihaji','Ogan Komering Ulu Selatan|Warkuk Ranau Selatan',
'Penukal Abab Lematang Ilir|Abab','Penukal Abab Lematang Ilir|Penukal','Penukal Abab Lematang Ilir|Penukal Utara',
'Penukal Abab Lematang Ilir|Talang Ubi','Penukal Abab Lematang Ilir|Tanah Abang',
'Lubuklinggau|Lubuklinggau Barat I','Lubuklinggau|Lubuklinggau Barat II','Lubuklinggau|Lubuklinggau Selatan I',
'Lubuklinggau|Lubuklinggau Selatan II','Lubuklinggau|Lubuklinggau Timur I','Lubuklinggau|Lubuklinggau Timur II',
'Lubuklinggau|Lubuklinggau Utara I','Lubuklinggau|Lubuklinggau Utara II',
'Pagar Alam|Dempo Selatan','Pagar Alam|Dempo Tengah','Pagar Alam|Dempo Utara','Pagar Alam|Pagar Alam Selatan',
'Pagar Alam|Pagar Alam Utara',
'Palembang|Alang-Alang Lebar','Palembang|Bukit Kecil','Palembang|Gandus','Palembang|Ilir Barat I','Palembang|Ilir Barat II',
'Palembang|Ilir Timur I','Palembang|Ilir Timur II','Palembang|Ilir Timur III','Palembang|Jakabaring','Palembang|Kalidoni',
'Palembang|Kemuning','Palembang|Kertapati','Palembang|Plaju','Palembang|Sako','Palembang|Seberang Ulu I',
'Palembang|Seberang Ulu II','Palembang|Sematang Borang','Palembang|Sukarami',
'Prabumulih|Cambai','Prabumulih|Prabumulih Barat','Prabumulih|Prabumulih Selatan','Prabumulih|Prabumulih Timur',
'Prabumulih|Prabumulih Utara','Prabumulih|Rambang Kapak Tengah',
], 'Sumatera Selatan');

echo "Sumatera (Barat, Riau, Jambi, Selatan) done.\n";
