<?php
function add($f, $entries, $prov) {
    $o = '';
    foreach ($entries as $e) {
        $p = explode('|', $e);
        $k = trim($p[0]); $n = trim($p[1]);
        $s = strtolower(str_replace(' ', '-', $n));
        $s = str_replace(["'", '/', '(', ')', '.'], '', $s);
        $s = str_replace('--', '-', $s); $s = trim($s, '-');
        $ne = str_replace("'", "\'", $n);
        $o .= "        ['slug' => '{$s}', 'nama' => '{$ne}', 'kota' => '{$k}', 'provinsi' => '{$prov}'],\n";
    }
    file_put_contents($f, $o, FILE_APPEND);
}
$f = __DIR__ . '/../config/pseo-kecamatan.php';

add($f, [
'Asahan|Aek Kuasan','Asahan|Aek Ledong','Asahan|Aek Songsongan','Asahan|Air Batu','Asahan|Air Joman',
'Asahan|Bandar Pasir Mandoge','Asahan|Bandar Pulau','Asahan|Buntu Pane','Asahan|Kisaran Barat','Asahan|Kisaran Timur',
'Asahan|Meranti','Asahan|Pulau Rakyat','Asahan|Pulo Bandring','Asahan|Rahuning','Asahan|Rawang Panca Arga',
'Asahan|Sei Dadap','Asahan|Sei Kepayang','Asahan|Sei Kepayang Barat','Asahan|Sei Kepayang Timur','Asahan|Setia Janji',
'Asahan|Silau Laut','Asahan|Simpang Empat','Asahan|Tanjung Balai','Asahan|Teluk Dalam','Asahan|Tinggi Raja',
'Batu Bara|Air Putih','Batu Bara|Datuk Lima Puluh','Batu Bara|Datuk Tanah Datar','Batu Bara|Laut Tador',
'Batu Bara|Lima Puluh','Batu Bara|Lima Puluh Pesisir','Batu Bara|Medang Deras','Batu Bara|Nibung Hangus',
'Batu Bara|Sei Balai','Batu Bara|Sei Suka','Batu Bara|Talawi','Batu Bara|Tanjung Tiram',
'Dairi|Berampu','Dairi|Gunung Sitember','Dairi|Lae Parira','Dairi|Parbuluan','Dairi|Pegagan Hilir',
'Dairi|Sidikalang','Dairi|Siempat Nempu','Dairi|Siempat Nempu Hilir','Dairi|Siempat Nempu Hulu',
'Dairi|Silahisabungan','Dairi|Silima Pungga Pungga','Dairi|Sitinjo','Dairi|Sumbul','Dairi|Tanah Pinem','Dairi|Tiga Lingga',
'Deli Serdang|Bangun Purba','Deli Serdang|Batang Kuis','Deli Serdang|Beringin','Deli Serdang|Biru-Biru',
'Deli Serdang|Deli Tua','Deli Serdang|Galang','Deli Serdang|Gunung Meriah','Deli Serdang|Hamparan Perak',
'Deli Serdang|Kutalimbaru','Deli Serdang|Labuhan Deli','Deli Serdang|Lubuk Pakam','Deli Serdang|Namo Rambe',
'Deli Serdang|Pagar Merbau','Deli Serdang|Pancur Batu','Deli Serdang|Pantai Labu','Deli Serdang|Patumbak',
'Deli Serdang|Percut Sei Tuan','Deli Serdang|Sibolangit','Deli Serdang|Sinembah Tanjung Muda Hilir',
'Deli Serdang|Sinembah Tanjung Muda Hulu','Deli Serdang|Sunggal','Deli Serdang|Tanjung Morawa',
'Humbang Hasundutan|Baktiraja','Humbang Hasundutan|Dolok Sanggul','Humbang Hasundutan|Lintong Nihuta',
'Humbang Hasundutan|Onan Ganjang','Humbang Hasundutan|Pakkat','Humbang Hasundutan|Paranginan',
'Humbang Hasundutan|Parlilitan','Humbang Hasundutan|Pollung','Humbang Hasundutan|Sijamapolang','Humbang Hasundutan|Tarabintang',
'Karo|Barusjahe','Karo|Berastagi','Karo|Dolat Rayat','Karo|Juhar','Karo|Kabanjahe','Karo|Kutabuluh',
'Karo|Laubaleng','Karo|Mardinding','Karo|Merdeka','Karo|Merek','Karo|Munte','Karo|Naman Teran',
'Karo|Payung','Karo|Simpang Empat','Karo|Tiga Binanga','Karo|Tiga Panah','Karo|Tiganderket',
'Labuhanbatu|Bilah Barat','Labuhanbatu|Bilah Hilir','Labuhanbatu|Bilah Hulu','Labuhanbatu|Panai Hilir',
'Labuhanbatu|Panai Hulu','Labuhanbatu|Panai Tengah','Labuhanbatu|Pangkatan','Labuhanbatu|Rantau Selatan','Labuhanbatu|Rantau Utara',
'Labuhanbatu Selatan|Kampung Rakyat','Labuhanbatu Selatan|Kota Pinang','Labuhanbatu Selatan|Sei Kanan',
'Labuhanbatu Selatan|Silangkitang','Labuhanbatu Selatan|Sungai Kanan','Labuhanbatu Selatan|Torgamba',
'Labuhanbatu Utara|Aek Kuo','Labuhanbatu Utara|Aek Natas','Labuhanbatu Utara|Kualuh Hilir','Labuhanbatu Utara|Kualuh Hulu',
'Labuhanbatu Utara|Kualuh Leidong','Labuhanbatu Utara|Kualuh Selatan','Labuhanbatu Utara|Marbau','Labuhanbatu Utara|Na IX-X',
'Langkat|Babalan','Langkat|Bahorok','Langkat|Batang Serangan','Langkat|Berandan Barat','Langkat|Besitang',
'Langkat|Binjai','Langkat|Brandan Barat','Langkat|Gebang','Langkat|Hinai','Langkat|Kuala','Langkat|Kutambaru',
'Langkat|Padang Tualang','Langkat|Pangkalan Susu','Langkat|Pematang Jaya','Langkat|Salapian','Langkat|Sawit Seberang',
'Langkat|Secanggang','Langkat|Sei Bingai','Langkat|Sei Lepan','Langkat|Selesai','Langkat|Sirapit',
'Langkat|Stabat','Langkat|Tanjung Pura','Langkat|Wampu',
'Mandailing Natal|Batahan','Mandailing Natal|Batang Natal','Mandailing Natal|Bukit Malintang','Mandailing Natal|Huta Bargot',
'Mandailing Natal|Kotanopan','Mandailing Natal|Lembah Sorik Marapi','Mandailing Natal|Lingga Bayu',
'Mandailing Natal|Muara Batang Gadis','Mandailing Natal|Muara Sipongi','Mandailing Natal|Naga Juang',
'Mandailing Natal|Natal','Mandailing Natal|Pakantan','Mandailing Natal|Panyabungan','Mandailing Natal|Panyabungan Barat',
'Mandailing Natal|Panyabungan Kota','Mandailing Natal|Panyabungan Selatan','Mandailing Natal|Panyabungan Timur',
'Mandailing Natal|Panyabungan Utara','Mandailing Natal|Puncak Sorik Marapi','Mandailing Natal|Ranto Baek',
'Mandailing Natal|Siabu','Mandailing Natal|Sinunukan','Mandailing Natal|Tambangan','Mandailing Natal|Ulu Pungkut',
'Nias|Bawolato','Nias|Botomuzoi','Nias|Gido','Nias|Hiliduho','Nias|Hiliserangkai','Nias|Idanogawo',
'Nias|Mau','Nias|Sogaeadu','Nias|Somolo-molo','Nias|Ulugawo',
'Nias Barat|Lahomi','Nias Barat|Lolofitu Moi','Nias Barat|Mandrehe','Nias Barat|Mandrehe Barat',
'Nias Barat|Mandrehe Utara','Nias Barat|Moroo','Nias Barat|Sirombu','Nias Barat|Ulu Moroo',
'Nias Selatan|Amandraya','Nias Selatan|Aramo','Nias Selatan|Boronadu','Nias Selatan|Fanayama',
'Nias Selatan|Gomo','Nias Selatan|Hibala','Nias Selatan|Hilimegai','Nias Selatan|Hilisalawa Ahe',
'Nias Selatan|Huruna','Nias Selatan|Lahusa','Nias Selatan|Lolomatua','Nias Selatan|Lolowau',
'Nias Selatan|Luahagundre Maniamolo','Nias Selatan|Maniamolo','Nias Selatan|Mazino','Nias Selatan|Mazo',
'Nias Selatan|Onohazumba','Nias Selatan|Onolalu','Nias Selatan|Oou','Nias Selatan|Pulau-Pulau Batu',
'Nias Selatan|Pulau-Pulau Batu Barat','Nias Selatan|Pulau-Pulau Batu Timur','Nias Selatan|Pulau-Pulau Batu Utara',
'Nias Selatan|Siduaori','Nias Selatan|Simuk','Nias Selatan|Somambawa','Nias Selatan|Susua',
'Nias Selatan|Tanah Masa','Nias Selatan|Teluk Dalam','Nias Selatan|Toma','Nias Selatan|Ulunoyo',
'Nias Selatan|Ulususua','Nias Selatan|Umbunasi',
'Nias Utara|Afulu','Nias Utara|Alasa','Nias Utara|Alasa Talumuzoi','Nias Utara|Lahewa','Nias Utara|Lahewa Timur',
'Nias Utara|Lotu','Nias Utara|Namohalu Esiwa','Nias Utara|Sawo','Nias Utara|Sitolu Ori',
'Nias Utara|Tugala Oyo','Nias Utara|Tuhemberua',
'Padang Lawas|Aek Nabara Barumun','Padang Lawas|Barumun','Padang Lawas|Barumun Barat','Padang Lawas|Barumun Baru',
'Padang Lawas|Barumun Selatan','Padang Lawas|Barumun Tengah','Padang Lawas|Batang Lubu Sutam',
'Padang Lawas|Huristak','Padang Lawas|Huta Raja Tinggi','Padang Lawas|Lubuk Barumun','Padang Lawas|Sihapas Barumun',
'Padang Lawas|Sosa','Padang Lawas|Sosa Julu','Padang Lawas|Sosa Timur','Padang Lawas|Sosopan',
'Padang Lawas|Ulu Barumun','Padang Lawas|Ulu Sosa',
'Padang Lawas Utara|Batang Onang','Padang Lawas Utara|Dolok','Padang Lawas Utara|Dolok Sigompulon',
'Padang Lawas Utara|Halongonan','Padang Lawas Utara|Halongonan Timur','Padang Lawas Utara|Hulu Sihapas',
'Padang Lawas Utara|Padang Bolak','Padang Lawas Utara|Padang Bolak Julu','Padang Lawas Utara|Padang Bolak Tenggara',
'Padang Lawas Utara|Portibi','Padang Lawas Utara|Simangambat','Padang Lawas Utara|Ujung Batu',
'Pakpak Bharat|Kerajaan','Pakpak Bharat|Pagindar','Pakpak Bharat|Parbubu','Pakpak Bharat|Pergetteng Getteng Sengkut',
'Pakpak Bharat|Salak','Pakpak Bharat|Siempat Rube','Pakpak Bharat|Sitellu Tali Urang Jehe','Pakpak Bharat|Sitellu Tali Urang Julu',
'Samosir|Harian','Samosir|Nainggolan','Samosir|Onan Runggu','Samosir|Palipi','Samosir|Pangururan',
'Samosir|Ronggur Nihuta','Samosir|Sianjur Mulamula','Samosir|Simanindo','Samosir|Sitiotio',
'Serdang Bedagai|Bandar Khalipah','Serdang Bedagai|Bintang Bayu','Serdang Bedagai|Dolok Masihul',
'Serdang Bedagai|Dolok Merawan','Serdang Bedagai|Kotarih','Serdang Bedagai|Pantai Cermin',
'Serdang Bedagai|Pegajahan','Serdang Bedagai|Perbaungan','Serdang Bedagai|Sei Bamban','Serdang Bedagai|Sei Rampah',
'Serdang Bedagai|Serba Jadi','Serdang Bedagai|Silinda','Serdang Bedagai|Sipispis',
'Serdang Bedagai|Tanjung Beringin','Serdang Bedagai|Tebing Syahbandar','Serdang Bedagai|Tebing Tinggi','Serdang Bedagai|Teluk Mengkudu',
'Simalungun|Bandar','Simalungun|Bandar Huluan','Simalungun|Bandar Masilam','Simalungun|Bosar Maligas',
'Simalungun|Dolok Batu Nanggar','Simalungun|Dolok Panribuan','Simalungun|Dolok Pardamean','Simalungun|Dolok Silau',
'Simalungun|Girsang Sipangan Bolon','Simalungun|Gunung Malela','Simalungun|Gunung Maligas','Simalungun|Haranggaol Horisan',
'Simalungun|Hatonduhan','Simalungun|Huta Bayu Raja','Simalungun|Jawa Maraja Bah Jambi','Simalungun|Jorlang Hataran',
'Simalungun|Panei','Simalungun|Panombeian Panei','Simalungun|Pematang Bandar','Simalungun|Pematang Sidamanik',
'Simalungun|Pematang Silima Huta','Simalungun|Purba','Simalungun|Raya','Simalungun|Raya Kahean',
'Simalungun|Siantar','Simalungun|Sidamanik','Simalungun|Silimakuta','Simalungun|Silou Kahean',
'Simalungun|Tanah Jawa','Simalungun|Tapian Dolok','Simalungun|Ujung Padang',
'Tapanuli Selatan|Aek Bilah','Tapanuli Selatan|Angkola Barat','Tapanuli Selatan|Angkola Muara Tais',
'Tapanuli Selatan|Angkola Sangkunur','Tapanuli Selatan|Angkola Selatan','Tapanuli Selatan|Angkola Timur',
'Tapanuli Selatan|Arse','Tapanuli Selatan|Batang Angkola','Tapanuli Selatan|Batang Toru','Tapanuli Selatan|Marancar',
'Tapanuli Selatan|Muara Batang Toru','Tapanuli Selatan|Saipar Dolok Hole','Tapanuli Selatan|Sayur Matinggi',
'Tapanuli Selatan|Sipirok','Tapanuli Selatan|Tano Tombangan Angkola',
'Tapanuli Tengah|Andam Dewi','Tapanuli Tengah|Badiri','Tapanuli Tengah|Barus','Tapanuli Tengah|Barus Utara',
'Tapanuli Tengah|Kolang','Tapanuli Tengah|Lumut','Tapanuli Tengah|Manduamas','Tapanuli Tengah|Pandan',
'Tapanuli Tengah|Pasaribu Tobing','Tapanuli Tengah|Pinangsori','Tapanuli Tengah|Sarudik','Tapanuli Tengah|Sibabangun',
'Tapanuli Tengah|Sirandorung','Tapanuli Tengah|Sitahuis','Tapanuli Tengah|Sorkam','Tapanuli Tengah|Sorkam Barat',
'Tapanuli Tengah|Sosor Gadong','Tapanuli Tengah|Suka Bangun','Tapanuli Tengah|Tapian Nauli','Tapanuli Tengah|Tukka',
'Tapanuli Utara|Adian Koting','Tapanuli Utara|Garoga','Tapanuli Utara|Muara','Tapanuli Utara|Pagaran',
'Tapanuli Utara|Pahae Jae','Tapanuli Utara|Pahae Julu','Tapanuli Utara|Pangaribuan','Tapanuli Utara|Parmonangan',
'Tapanuli Utara|Purbatua','Tapanuli Utara|Siatas Barita','Tapanuli Utara|Siborong-Borong','Tapanuli Utara|Simangumban',
'Tapanuli Utara|Sipahutar','Tapanuli Utara|Sipoholon','Tapanuli Utara|Tarutung',
'Toba|Ajibata','Toba|Balige','Toba|Bonatua Lunasi','Toba|Borbor','Toba|Habinsaran','Toba|Laguboti',
'Toba|Lumban Julu','Toba|Nassau','Toba|Parmaksian','Toba|Pintu Pohan Meranti','Toba|Porsea',
'Toba|Siantar Narumonda','Toba|Sigumpar','Toba|Silaen','Toba|Tampahan','Toba|Uluan',
'Binjai|Binjai Barat','Binjai|Binjai Kota','Binjai|Binjai Selatan','Binjai|Binjai Timur','Binjai|Binjai Utara',
'Gunungsitoli|Gunungsitoli','Gunungsitoli|Gunungsitoli Alo Oa','Gunungsitoli|Gunungsitoli Barat',
'Gunungsitoli|Gunungsitoli Idanoi','Gunungsitoli|Gunungsitoli Selatan','Gunungsitoli|Gunungsitoli Utara',
'Medan|Medan Amplas','Medan|Medan Area','Medan|Medan Barat','Medan|Medan Baru','Medan|Medan Belawan',
'Medan|Medan Deli','Medan|Medan Denai','Medan|Medan Helvetia','Medan|Medan Johor','Medan|Medan Kota',
'Medan|Medan Labuhan','Medan|Medan Maimun','Medan|Medan Marelan','Medan|Medan Perjuangan','Medan|Medan Petisah',
'Medan|Medan Polonia','Medan|Medan Selayang','Medan|Medan Sunggal','Medan|Medan Tembung','Medan|Medan Timur','Medan|Medan Tuntungan',
'Padang Sidempuan|Padang Sidempuan Angkola Julu','Padang Sidempuan|Padang Sidempuan Batunadua',
'Padang Sidempuan|Padang Sidempuan Hutaimbaru','Padang Sidempuan|Padang Sidempuan Selatan',
'Padang Sidempuan|Padang Sidempuan Tenggara','Padang Sidempuan|Padang Sidempuan Utara',
'Pematang Siantar|Siantar Barat','Pematang Siantar|Siantar Marihat','Pematang Siantar|Siantar Marimbun',
'Pematang Siantar|Siantar Martoba','Pematang Siantar|Siantar Selatan','Pematang Siantar|Siantar Sitalasari',
'Pematang Siantar|Siantar Timur','Pematang Siantar|Siantar Utara',
'Sibolga|Sibolga Kota','Sibolga|Sibolga Sambas','Sibolga|Sibolga Selatan','Sibolga|Sibolga Utara',
'Tanjung Balai|Datuk Bandar','Tanjung Balai|Datuk Bandar Timur','Tanjung Balai|Sei Tualang Raso',
'Tanjung Balai|Tanjung Balai Selatan','Tanjung Balai|Tanjung Balai Utara','Tanjung Balai|Teluk Nibung',
'Tebing Tinggi|Bajenis','Tebing Tinggi|Padang Hilir','Tebing Tinggi|Padang Hulu','Tebing Tinggi|Rambutan','Tebing Tinggi|Tebing Tinggi Kota',
], 'Sumatera Utara');

echo "Sumatera Utara done.\n";
