<?php
// Sumatera provinces generator - Part 1
// Each line format: kabupaten|kecamatan|provinsi

function addEntries($file, $entries, $provinsi) {
    $lines = "        // ============================================================\n";
    $lines .= "        // {$provinsi}\n";
    $lines .= "        // ============================================================\n";
    foreach ($entries as $entry) {
        $parts = explode('|', $entry);
        $kota = trim($parts[0]);
        $nama = trim($parts[1]);
        $slug = strtolower(str_replace(' ', '-', $nama));
        $slug = str_replace(["'", '/', '(', ')', '.'], '', $slug);
        $slug = str_replace('--', '-', $slug);
        $slug = trim($slug, '-');
        $namaEsc = str_replace("'", "\'", $nama);
        $lines .= "        ['slug' => '{$slug}', 'nama' => '{$namaEsc}', 'kota' => '{$kota}', 'provinsi' => '{$provinsi}'],\n";
    }
    file_put_contents($file, $lines, FILE_APPEND);
}

// Initialize file
$file = __DIR__ . '/../config/pseo-kecamatan.php';
file_put_contents($file, "<?php\n\nreturn [\n    'kecamatan' => [\n");

// ==============================
// ACEH
// ==============================
addEntries($file, [
'Aceh Selatan|Bakongan',
'Aceh Selatan|Bakongan Timur',
'Aceh Selatan|Kluet Selatan',
'Aceh Selatan|Kluet Tengah',
'Aceh Selatan|Kluet Timur',
'Aceh Selatan|Kluet Utara',
'Aceh Selatan|Kota Bahagia',
'Aceh Selatan|Labuhan Haji',
'Aceh Selatan|Labuhan Haji Barat',
'Aceh Selatan|Labuhan Haji Timur',
'Aceh Selatan|Meukek',
'Aceh Selatan|Pasie Raja',
'Aceh Selatan|Sama Dua',
'Aceh Selatan|Sawang',
'Aceh Selatan|Tapak Tuan',
'Aceh Selatan|Trumon',
'Aceh Selatan|Trumon Tengah',
'Aceh Selatan|Trumon Timur',
'Aceh Tenggara|Babul Makmur',
'Aceh Tenggara|Babul Rahmat',
'Aceh Tenggara|Babussalam',
'Aceh Tenggara|Badar',
'Aceh Tenggara|Bambel',
'Aceh Tenggara|Bukit Tusam',
'Aceh Tenggara|Darul Hasanah',
'Aceh Tenggara|Deleng Pokhkisen',
'Aceh Tenggara|Ketambe',
'Aceh Tenggara|Lawe Alas',
'Aceh Tenggara|Lawe Bulan',
'Aceh Tenggara|Lawe Sigala-Gala',
'Aceh Tenggara|Lawe Sumur',
'Aceh Tenggara|Leuser',
'Aceh Tenggara|Semadam',
'Aceh Tenggara|Tanah Alas',
'Aceh Timur|Banda Alam',
'Aceh Timur|Birem Bayeun',
'Aceh Timur|Darul Aman',
'Aceh Timur|Darul Falah',
'Aceh Timur|Darul Ihsan',
'Aceh Timur|Idi Rayeuk',
'Aceh Timur|Idi Timur',
'Aceh Timur|Idi Tunong',
'Aceh Timur|Indra Makmur',
'Aceh Timur|Julok',
'Aceh Timur|Madat',
'Aceh Timur|Nurussalam',
'Aceh Timur|Pante Bidari',
'Aceh Timur|Peudawa',
'Aceh Timur|Peunaron',
'Aceh Timur|Peureulak',
'Aceh Timur|Peureulak Barat',
'Aceh Timur|Peureulak Timur',
'Aceh Timur|Rantau Selamat',
'Aceh Timur|Ranto Peureulak',
'Aceh Timur|Serba Jadi',
'Aceh Timur|Simpang Jernih',
'Aceh Timur|Simpang Ulim',
'Aceh Timur|Sungai Raya',
'Aceh Tengah|Atu Lintang',
'Aceh Tengah|Bebesen',
'Aceh Tengah|Bies',
'Aceh Tengah|Bintang',
'Aceh Tengah|Celala',
'Aceh Tengah|Jagong Jeget',
'Aceh Tengah|Kebayakan',
'Aceh Tengah|Ketol',
'Aceh Tengah|Kute Panang',
'Aceh Tengah|Laut Tawar',
'Aceh Tengah|Linge',
'Aceh Tengah|Pegasing',
'Aceh Tengah|Rusip Antara',
'Aceh Tengah|Silih Nara',
'Aceh Barat|Arongan Lambalek',
'Aceh Barat|Bubon',
'Aceh Barat|Johan Pahlawan',
'Aceh Barat|Kaway XVI',
'Aceh Barat|Meureubo',
'Aceh Barat|Pante Ceureumen',
'Aceh Barat|Panton Reu',
'Aceh Barat|Samatiga',
'Aceh Barat|Sungai Mas',
'Aceh Barat|Woyla',
'Aceh Barat|Woyla Barat',
'Aceh Barat|Woyla Timur',
'Aceh Besar|Baitussalam',
'Aceh Besar|Blang Bintang',
'Aceh Besar|Darul Imarah',
'Aceh Besar|Darul Kamal',
'Aceh Besar|Darussalam',
'Aceh Besar|Indrapuri',
'Aceh Besar|Ingin Jaya',
'Aceh Besar|Kota Jantho',
'Aceh Besar|Krueng Barona Jaya',
'Aceh Besar|Kuta Baro',
'Aceh Besar|Kuta Cot Glie',
'Aceh Besar|Kuta Malaka',
'Aceh Besar|Lembah Seulawah',
'Aceh Besar|Leupung',
'Aceh Besar|Lhoknga',
'Aceh Besar|Lhoong',
'Aceh Besar|Mesjid Raya',
'Aceh Besar|Montasik',
'Aceh Besar|Peukan Bada',
'Aceh Besar|Pulo Aceh',
'Aceh Besar|Seulimeum',
'Aceh Besar|Simpang Tiga',
'Aceh Besar|Suka Makmur',
'Pidie|Batee',
'Pidie|Delima',
'Pidie|Geumpang',
'Pidie|Glumpang Baro',
'Pidie|Glumpang Tiga',
'Pidie|Grong Grong',
'Pidie|Indrajaya',
'Pidie|Kembang Tanjong',
'Pidie|Keumala',
'Pidie|Kota Sigli',
'Pidie|Mane',
'Pidie|Mila',
'Pidie|Muara Tiga',
'Pidie|Mutiara',
'Pidie|Mutiara Timur',
'Pidie|Padang Tiji',
'Pidie|Peukan Baro',
'Pidie|Pidie',
'Pidie|Sakti',
'Pidie|Simpang Tiga',
'Pidie|Tangse',
'Pidie|Tiro Truseb',
'Pidie|Titeue',
'Bireuen|Gandapura',
'Bireuen|Jangka',
'Bireuen|Jeumpa',
'Bireuen|Jeunieb',
'Bireuen|Kota Juang',
'Bireuen|Kuala',
'Bireuen|Kuta Blang',
'Bireuen|Makmur',
'Bireuen|Pandrah',
'Bireuen|Peudada',
'Bireuen|Peulimbang',
'Bireuen|Peusangan',
'Bireuen|Peusangan Selatan',
'Bireuen|Peusangan Siblah Krueng',
'Bireuen|Samalanga',
'Bireuen|Simpang Mamplam',
'Aceh Utara|Baktiya',
'Aceh Utara|Baktiya Barat',
'Aceh Utara|Cot Girek',
'Aceh Utara|Dewantara',
'Aceh Utara|Geureudong Pase',
'Aceh Utara|Kuta Makmur',
'Aceh Utara|Langkahan',
'Aceh Utara|Lapang',
'Aceh Utara|Lhoksukon',
'Aceh Utara|Matangkuli',
'Aceh Utara|Meurah Mulia',
'Aceh Utara|Muara Batu',
'Aceh Utara|Nibong',
'Aceh Utara|Nisam',
'Aceh Utara|Nisam Antara',
'Aceh Utara|Paya Bakong',
'Aceh Utara|Pirak Timur',
'Aceh Utara|Samudera',
'Aceh Utara|Sawang',
'Aceh Utara|Seunuddon',
'Aceh Utara|Simpang Keramat',
'Aceh Utara|Syamtalira Aron',
'Aceh Utara|Syamtalira Bayu',
'Aceh Utara|Tanah Jambo Aye',
'Aceh Utara|Tanah Luas',
'Aceh Utara|Tanah Pasir',
'Aceh Barat Daya|Babah Rot',
'Aceh Barat Daya|Blangpidie',
'Aceh Barat Daya|Jeumpa',
'Aceh Barat Daya|Kuala Batee',
'Aceh Barat Daya|Lembah Sabil',
'Aceh Barat Daya|Manggeng',
'Aceh Barat Daya|Setia',
'Aceh Barat Daya|Susoh',
'Aceh Barat Daya|Tangan-Tangan',
'Gayo Lues|Blangjerango',
'Gayo Lues|Blangkejeren',
'Gayo Lues|Blangpegayon',
'Gayo Lues|Dabun Gelang',
'Gayo Lues|Kuta Panjang',
'Gayo Lues|Pantan Cuaca',
'Gayo Lues|Pining',
'Gayo Lues|Putri Betung',
'Gayo Lues|Rikit Gaib',
'Gayo Lues|Terangun',
'Gayo Lues|Tripe Jaya',
'Aceh Tamiang|Banda Mulia',
'Aceh Tamiang|Bandar Pusaka',
'Aceh Tamiang|Bendahara',
'Aceh Tamiang|Karang Baru',
'Aceh Tamiang|Kejuruan Muda',
'Aceh Tamiang|Kota Kualasinpang',
'Aceh Tamiang|Manyak Payed',
'Aceh Tamiang|Rantau',
'Aceh Tamiang|Sekerak',
'Aceh Tamiang|Seruway',
'Aceh Tamiang|Tamiang Hulu',
'Aceh Tamiang|Tenggulun',
'Nagan Raya|Beutong',
'Nagan Raya|Beutong Ateuh Banggalang',
'Nagan Raya|Darul Makmur',
'Nagan Raya|Kuala',
'Nagan Raya|Kuala Pesisir',
'Nagan Raya|Seunagan',
'Nagan Raya|Seunagan Timur',
'Nagan Raya|Suka Makmue',
'Nagan Raya|Tadu Raya',
'Nagan Raya|Tripa Makmur',
'Aceh Jaya|Darul Hikmah',
'Aceh Jaya|Indra Jaya',
'Aceh Jaya|Jaya',
'Aceh Jaya|Krueng Sabee',
'Aceh Jaya|Panga',
'Aceh Jaya|Pasie Raya',
'Aceh Jaya|Sampoiniet',
'Aceh Jaya|Setia Bakti',
'Aceh Jaya|Teunom',
'Bener Meriah|Bandar',
'Bener Meriah|Bener Kelipah',
'Bener Meriah|Bukit',
'Bener Meriah|Gajah Putih',
'Bener Meriah|Mesidah',
'Bener Meriah|Permata',
'Bener Meriah|Pintu Rime Gayo',
'Bener Meriah|Syiah Utama',
'Bener Meriah|Timang Gajah',
'Bener Meriah|Wih Pesam',
'Pidie Jaya|Bandar Baru',
'Pidie Jaya|Bandar Dua',
'Pidie Jaya|Jangka Buya',
'Pidie Jaya|Meurah Dua',
'Pidie Jaya|Meureudu',
'Pidie Jaya|Panteraja',
'Pidie Jaya|Tringgadeng',
'Pidie Jaya|Ulim',
'Aceh Singkil|Danau Paris',
'Aceh Singkil|Gunung Meriah',
'Aceh Singkil|Kota Baharu',
'Aceh Singkil|Kuala Baru',
'Aceh Singkil|Pulau Banyak',
'Aceh Singkil|Pulau Banyak Barat',
'Aceh Singkil|Simpang Kanan',
'Aceh Singkil|Singkil',
'Aceh Singkil|Singkil Utara',
'Aceh Singkil|Singkohor',
'Aceh Singkil|Suro Makmur',
'Banda Aceh|Baiturrahman',
'Banda Aceh|Banda Raya',
'Banda Aceh|Jaya Baru',
'Banda Aceh|Kuta Alam',
'Banda Aceh|Kuta Raja',
'Banda Aceh|Lueng Bata',
'Banda Aceh|Meuraxa',
'Banda Aceh|Syiah Kuala',
'Banda Aceh|Ulee Kareng',
'Sabang|Sukajaya',
'Sabang|Sukakarya',
'Langsa|Langsa Barat',
'Langsa|Langsa Kota',
'Langsa|Langsa Lama',
'Langsa|Langsa Teungoh',
'Langsa|Langsa Timur',
'Lhokseumawe|Banda Sakti',
'Lhokseumawe|Blang Mangat',
'Lhokseumawe|Muara Dua',
'Lhokseumawe|Muara Satu',
'Subulussalam|Longkib',
'Subulussalam|Penanggalan',
'Subulussalam|Rundeng',
'Subulussalam|Simpang Kiri',
'Subulussalam|Sultan Daulat',
], 'Aceh');

echo "Aceh done.\n";
