<?php
function add($f, $entries, $prov) {
    $o = '';
    foreach ($entries as $e) {
        $p = explode('|', $e);
        $k = trim($p[0]); $n = trim($p[1]);
        $s = strtolower(str_replace(' ', '-', $n));
        $s = str_replace(["'", '/', '(', ')', '.'], '', $s);
        $s = str_replace('--', '-', $s); $s = trim($s, '-');
        $ne = str_replace("'", "\'", $n);
        $o .= "        ['slug' => '{$s}', 'nama' => '{$ne}', 'kota' => '{$k}', 'provinsi' => '{$prov}'],\n";
    }
    file_put_contents($f, $o, FILE_APPEND);
}
$f = __DIR__ . '/../config/pseo-kecamatan.php';

// JAWA TENGAH (35 kab/kota, ~576 kecamatan)
add($f, [
'Banjarnegara|Banjarmangu','Banjarnegara|Banjarnegara','Banjarnegara|Batur','Banjarnegara|Bawang',
'Banjarnegara|Kalibening','Banjarnegara|Karangkobar','Banjarnegara|Madukara','Banjarnegara|Mandiraja',
'Banjarnegara|Pagedongan','Banjarnegara|Pagentan','Banjarnegara|Pandanarum','Banjarnegara|Pejawaran',
'Banjarnegara|Punggelan','Banjarnegara|Purwonegoro','Banjarnegara|Purworejo Klampok','Banjarnegara|Rakit',
'Banjarnegara|Sigaluh','Banjarnegara|Susukan','Banjarnegara|Wanadadi','Banjarnegara|Wanayasa',
'Banyumas|Ajibarang','Banyumas|Banyumas','Banyumas|Baturaden','Banyumas|Cilongok','Banyumas|Gumelar',
'Banyumas|Jatilawang','Banyumas|Kalibagor','Banyumas|Karanglewas','Banyumas|Kebasen','Banyumas|Kedung Banteng',
'Banyumas|Kembaran','Banyumas|Kemranjen','Banyumas|Lumbir','Banyumas|Patikraja','Banyumas|Pekuncen',
'Banyumas|Purwojati','Banyumas|Purwokerto Barat','Banyumas|Purwokerto Selatan','Banyumas|Purwokerto Timur',
'Banyumas|Purwokerto Utara','Banyumas|Rawalo','Banyumas|Sokaraja','Banyumas|Somagede','Banyumas|Sumbang',
'Banyumas|Sumpiuh','Banyumas|Tambak','Banyumas|Wangon',
'Batang|Bandar','Batang|Banyuputih','Batang|Batang','Batang|Bawang','Batang|Blado','Batang|Gringsing',
'Batang|Kandeman','Batang|Limpung','Batang|Pecalungan','Batang|Reban','Batang|Subah','Batang|Tersono',
'Batang|Tulis','Batang|Warungasem','Batang|Wonotunggal',
'Blora|Banjarejo','Blora|Blora','Blora|Bogorejo','Blora|Cepu','Blora|Japah','Blora|Jati','Blora|Jepon',
'Blora|Jiken','Blora|Kedungtuban','Blora|Kradenan','Blora|Kunduran','Blora|Ngawen','Blora|Randublatung',
'Blora|Sambong','Blora|Todanan','Blora|Tunjungan',
'Boyolali|Ampel','Boyolali|Andong','Boyolali|Banyudono','Boyolali|Boyolali','Boyolali|Cepogo','Boyolali|Juwangi',
'Boyolali|Karanggede','Boyolali|Kemusu','Boyolali|Klego','Boyolali|Mojosongo','Boyolali|Musuk','Boyolali|Ngemplak',
'Boyolali|Nogosari','Boyolali|Sambi','Boyolali|Sawit','Boyolali|Selo','Boyolali|Simo','Boyolali|Tamansari',
'Boyolali|Teras','Boyolali|Wonosegoro',
'Brebes|Banjarharjo','Brebes|Bantarkawung','Brebes|Brebes','Brebes|Bulakamba','Brebes|Bumiayu','Brebes|Jatibarang',
'Brebes|Kersana','Brebes|Ketanggungan','Brebes|Larangan','Brebes|Losari','Brebes|Paguyangan','Brebes|Salem',
'Brebes|Sirampog','Brebes|Songgom','Brebes|Tanjung','Brebes|Tonjong','Brebes|Wanasari',
'Cilacap|Adipala','Cilacap|Bantarsari','Cilacap|Binangun','Cilacap|Cilacap Selatan','Cilacap|Cilacap Tengah',
'Cilacap|Cilacap Utara','Cilacap|Cimanggu','Cilacap|Cipari','Cilacap|Dayeuhluhur','Cilacap|Gandrungmangu',
'Cilacap|Jeruklegi','Cilacap|Kampung Laut','Cilacap|Karangpucung','Cilacap|Kawunganten','Cilacap|Kedungreja',
'Cilacap|Kesugihan','Cilacap|Kroya','Cilacap|Majenang','Cilacap|Maos','Cilacap|Nusawungu','Cilacap|Patimuan',
'Cilacap|Sampang','Cilacap|Sidareja','Cilacap|Wanareja',
'Demak|Bonang','Demak|Demak','Demak|Dempet','Demak|Gajah','Demak|Guntur','Demak|Karanganyar','Demak|Karangawen',
'Demak|Karangtengah','Demak|Kebonagung','Demak|Mijen','Demak|Mranggen','Demak|Sayung','Demak|Wedung','Demak|Wonosalam',
'Grobogan|Brati','Grobogan|Gabus','Grobogan|Geyer','Grobogan|Godong','Grobogan|Grobogan','Grobogan|Gubug',
'Grobogan|Karangrayung','Grobogan|Kedungjati','Grobogan|Klambu','Grobogan|Kradenan','Grobogan|Ngaringan',
'Grobogan|Penawangan','Grobogan|Pulokulon','Grobogan|Purwodadi','Grobogan|Tanggungharjo','Grobogan|Tawangharjo',
'Grobogan|Tegowanu','Grobogan|Toroh','Grobogan|Wirosari',
'Jepara|Bangsri','Jepara|Batealit','Jepara|Donorojo','Jepara|Jepara','Jepara|Kalinyamatan','Jepara|Karimunjawa',
'Jepara|Kedung','Jepara|Keling','Jepara|Kembang','Jepara|Mayong','Jepara|Mlonggo','Jepara|Nalumsari',
'Jepara|Pakis Aji','Jepara|Pecangaan','Jepara|Tahunan','Jepara|Welahan',
'Karanganyar|Colomadu','Karanganyar|Gondangrejo','Karanganyar|Jaten','Karanganyar|Jatipuro','Karanganyar|Jatiyoso',
'Karanganyar|Jenawi','Karanganyar|Jumantono','Karanganyar|Jumapolo','Karanganyar|Karanganyar','Karanganyar|Karangpandan',
'Karanganyar|Kebakkramat','Karanganyar|Kerjo','Karanganyar|Matesih','Karanganyar|Mojogedang','Karanganyar|Ngargoyoso',
'Karanganyar|Tasikmadu','Karanganyar|Tawangmangu',
'Kebumen|Adimulyo','Kebumen|Alian','Kebumen|Ambal','Kebumen|Ayah','Kebumen|Bonorowo','Kebumen|Buayan',
'Kebumen|Gombong','Kebumen|Karanganyar','Kebumen|Karanggayam','Kebumen|Karangsambung','Kebumen|Kebumen',
'Kebumen|Klirong','Kebumen|Kutowinangun','Kebumen|Kuwarasan','Kebumen|Mirit','Kebumen|Padureso','Kebumen|Pejagoan',
'Kebumen|Petanahan','Kebumen|Poncowarno','Kebumen|Prembun','Kebumen|Puring','Kebumen|Rowokele','Kebumen|Sadang',
'Kebumen|Sempor','Kebumen|Sruweng',
'Kendal|Boja','Kendal|Brangsong','Kendal|Cepiring','Kendal|Gemuh','Kendal|Kaliwungu','Kendal|Kaliwungu Selatan',
'Kendal|Kangkung','Kendal|Kendal','Kendal|Limbangan','Kendal|Ngampel','Kendal|Pageruyung','Kendal|Patean',
'Kendal|Patebon','Kendal|Pegandon','Kendal|Plantungan','Kendal|Ringinarum','Kendal|Rowosari','Kendal|Singorojo',
'Kendal|Sukorejo','Kendal|Weleri',
'Klaten|Bayat','Klaten|Cawas','Klaten|Ceper','Klaten|Delanggu','Klaten|Gantiwarno','Klaten|Jatinom','Klaten|Jogonalan',
'Klaten|Juwiring','Klaten|Kalikotes','Klaten|Karanganom','Klaten|Karangdowo','Klaten|Karangnongko','Klaten|Kebonarum',
'Klaten|Kemalang','Klaten|Klaten Selatan','Klaten|Klaten Tengah','Klaten|Klaten Utara','Klaten|Manisrenggo',
'Klaten|Ngawen','Klaten|Pedan','Klaten|Polanharjo','Klaten|Prambanan','Klaten|Trucuk','Klaten|Tulung',
'Klaten|Wedi','Klaten|Wonosari',
'Kudus|Bae','Kudus|Dawe','Kudus|Gebog','Kudus|Jati','Kudus|Jekulo','Kudus|Kaliwungu','Kudus|Kudus','Kudus|Mejobo',
'Kudus|Undaan',
'Magelang|Bandongan','Magelang|Borobudur','Magelang|Candimulyo','Magelang|Dukun','Magelang|Grabag','Magelang|Kajoran',
'Magelang|Kaliangkrik','Magelang|Mertoyudan','Magelang|Mungkid','Magelang|Muntilan','Magelang|Ngablak','Magelang|Ngluwar',
'Magelang|Pakis','Magelang|Salam','Magelang|Salaman','Magelang|Sawangan','Magelang|Secang','Magelang|Srumbung',
'Magelang|Tegalrejo','Magelang|Tempuran','Magelang|Windusari',
'Pati|Batangan','Pati|Cluwak','Pati|Dukuhseti','Pati|Gabus','Pati|Gembong','Pati|Gunungwungkal','Pati|Jaken',
'Pati|Jakenan','Pati|Juwana','Pati|Kayen','Pati|Margorejo','Pati|Margoyoso','Pati|Pati','Pati|Pucakwangi',
'Pati|Sukolilo','Pati|Tambakromo','Pati|Tayu','Pati|Tlogowungu','Pati|Trangkil','Pati|Wedarijaksa','Pati|Winong',
'Pekalongan|Bojong','Pekalongan|Buaran','Pekalongan|Doro','Pekalongan|Kajen','Pekalongan|Kandangserang',
'Pekalongan|Karanganyar','Pekalongan|Karangdadap','Pekalongan|Kedungwuni','Pekalongan|Kesesi','Pekalongan|Lebakbarang',
'Pekalongan|Paninggaran','Pekalongan|Petungkriono','Pekalongan|Siwalan','Pekalongan|Sragi','Pekalongan|Talun',
'Pekalongan|Tirto','Pekalongan|Wiradesa','Pekalongan|Wonokerto','Pekalongan|Wonopringgo',
'Pemalang|Ampelgading','Pemalang|Bantarbolang','Pemalang|Belik','Pemalang|Bodeh','Pemalang|Comal','Pemalang|Moga',
'Pemalang|Pemalang','Pemalang|Petarukan','Pemalang|Pulosari','Pemalang|Randudongkal','Pemalang|Taman','Pemalang|Ulujami',
'Pemalang|Warungpring','Pemalang|Watukumpul',
'Purbalingga|Bobotsari','Purbalingga|Bojongsari','Purbalingga|Bukateja','Purbalingga|Kaligondang','Purbalingga|Kalimanah',
'Purbalingga|Karanganyar','Purbalingga|Karangjambu','Purbalingga|Karangmoncol','Purbalingga|Karangreja','Purbalingga|Kejobong',
'Purbalingga|Kemangkon','Purbalingga|Kertanegara','Purbalingga|Kutasari','Purbalingga|Mrebet','Purbalingga|Padamara',
'Purbalingga|Pengadegan','Purbalingga|Purbalingga','Purbalingga|Rembang',
'Purworejo|Bagelen','Purworejo|Banyuurip','Purworejo|Bayan','Purworejo|Bener','Purworejo|Bruno','Purworejo|Butuh',
'Purworejo|Gebang','Purworejo|Grabag','Purworejo|Kaligesing','Purworejo|Kemiri','Purworejo|Kutoarjo','Purworejo|Loano',
'Purworejo|Ngombol','Purworejo|Pituruh','Purworejo|Purwodadi','Purworejo|Purworejo',
'Rembang|Bulu','Rembang|Gunem','Rembang|Kaliori','Rembang|Kragan','Rembang|Lasem','Rembang|Pamotan','Rembang|Pancur',
'Rembang|Rembang','Rembang|Sale','Rembang|Sarang','Rembang|Sedan','Rembang|Sluke','Rembang|Sulang','Rembang|Sumber',
'Semarang|Ambarawa','Semarang|Bancak','Semarang|Bandungan','Semarang|Banyubiru','Semarang|Bawen','Semarang|Bergas',
'Semarang|Bringin','Semarang|Getasan','Semarang|Jambu','Semarang|Kaliwungu','Semarang|Pabelan','Semarang|Pringapus',
'Semarang|Sumowono','Semarang|Suruh','Semarang|Susukan','Semarang|Tengaran','Semarang|Tuntang','Semarang|Ungaran Barat',
'Semarang|Ungaran Timur',
'Sragen|Gemolong','Sragen|Gesi','Sragen|Gondang','Sragen|Jenar','Sragen|Kalijambe','Sragen|Karangmalang','Sragen|Kedawung',
'Sragen|Masaran','Sragen|Miri','Sragen|Mondokan','Sragen|Ngrampal','Sragen|Plupuh','Sragen|Sambirejo','Sragen|Sambungmacan',
'Sragen|Sidoharjo','Sragen|Sragen','Sragen|Sukodono','Sragen|Sumberlawang','Sragen|Tangen','Sragen|Tanon',
'Sukoharjo|Baki','Sukoharjo|Bendosari','Sukoharjo|Bulu','Sukoharjo|Gatak','Sukoharjo|Grogol','Sukoharjo|Kartasura',
'Sukoharjo|Mojolaban','Sukoharjo|Nguter','Sukoharjo|Polokarto','Sukoharjo|Sukoharjo','Sukoharjo|Tawangsari','Sukoharjo|Weru',
'Tegal|Adiwerna','Tegal|Balapulang','Tegal|Bojong','Tegal|Bumijawa','Tegal|Dukuhturi','Tegal|Dukuhwaru','Tegal|Jatinegara',
'Tegal|Kedungbanteng','Tegal|Kramat','Tegal|Lebaksiu','Tegal|Margasari','Tegal|Pagerbarang','Tegal|Pangkah',
'Tegal|Slawi','Tegal|Suradadi','Tegal|Talang','Tegal|Tarub','Tegal|Warureja',
'Temanggung|Bansari','Temanggung|Bejen','Temanggung|Bulu','Temanggung|Candiroto','Temanggung|Gemawang','Temanggung|Jumo',
'Temanggung|Kaloran','Temanggung|Kandangan','Temanggung|Kedu','Temanggung|Kledung','Temanggung|Kranggan','Temanggung|Ngadirejo',
'Temanggung|Parakan','Temanggung|Pringsurat','Temanggung|Selopampang','Temanggung|Temanggung','Temanggung|Tembarak',
'Temanggung|Tlogomulyo','Temanggung|Tretep','Temanggung|Wonoboyo',
'Wonogiri|Baturetno','Wonogiri|Batuwarno','Wonogiri|Bulukerto','Wonogiri|Eromoko','Wonogiri|Girimarto','Wonogiri|Giritontro',
'Wonogiri|Giriwoyo','Wonogiri|Jatipurno','Wonogiri|Jatiroto','Wonogiri|Jatisrono','Wonogiri|Karangtengah',
'Wonogiri|Kismantoro','Wonogiri|Manyaran','Wonogiri|Ngadirojo','Wonogiri|Nguntoronadi','Wonogiri|Paranggupito',
'Wonogiri|Pracimantoro','Wonogiri|Puhpelem','Wonogiri|Purwantoro','Wonogiri|Selogiri','Wonogiri|Sidoharjo',
'Wonogiri|Slogohimo','Wonogiri|Tirtomoyo','Wonogiri|Wonogiri','Wonogiri|Wuryantoro',
'Wonosobo|Garung','Wonosobo|Kalibawang','Wonosobo|Kalikajar','Wonosobo|Kaliwiro','Wonosobo|Kejajar','Wonosobo|Kepil',
'Wonosobo|Kertek','Wonosobo|Leksono','Wonosobo|Mojotengah','Wonosobo|Sapuran','Wonosobo|Selomerto','Wonosobo|Sukoharjo',
'Wonosobo|Wadaslintang','Wonosobo|Watumalang','Wonosobo|Wonosobo',
'Magelang Kota|Magelang Selatan','Magelang Kota|Magelang Tengah','Magelang Kota|Magelang Utara',
'Pekalongan Kota|Pekalongan Barat','Pekalongan Kota|Pekalongan Selatan','Pekalongan Kota|Pekalongan Timur',
'Pekalongan Kota|Pekalongan Utara',
'Salatiga|Argomulyo','Salatiga|Sidomukti','Salatiga|Sidorejo','Salatiga|Tingkir',
'Semarang Kota|Banyumanik','Semarang Kota|Candisari','Semarang Kota|Gajahmungkur','Semarang Kota|Gayamsari',
'Semarang Kota|Genuk','Semarang Kota|Gunungpati','Semarang Kota|Mijen','Semarang Kota|Ngaliyan','Semarang Kota|Pedurungan',
'Semarang Kota|Semarang Barat','Semarang Kota|Semarang Selatan','Semarang Kota|Semarang Tengah','Semarang Kota|Semarang Timur',
'Semarang Kota|Semarang Utara','Semarang Kota|Tembalang','Semarang Kota|Tugu',
'Surakarta|Banjarsari','Surakarta|Jebres','Surakarta|Laweyan','Surakarta|Pasar Kliwon','Surakarta|Serengan',
'Tegal Kota|Margadana','Tegal Kota|Tegal Barat','Tegal Kota|Tegal Selatan','Tegal Kota|Tegal Timur',
], 'Jawa Tengah');

// DI YOGYAKARTA (5 kab/kota, 78 kecamatan)
add($f, [
'Bantul|Bambanglipuro','Bantul|Banguntapan','Bantul|Bantul','Bantul|Dlingo','Bantul|Imogiri','Bantul|Jetis',
'Bantul|Kasihan','Bantul|Kretek','Bantul|Pajangan','Bantul|Pandak','Bantul|Piyungan','Bantul|Pleret','Bantul|Pundong',
'Bantul|Sanden','Bantul|Sedayu','Bantul|Sewon','Bantul|Srandakan',
'Gunungkidul|Gedangsari','Gunungkidul|Girisubo','Gunungkidul|Karangmojo','Gunungkidul|Ngawen','Gunungkidul|Nglipar',
'Gunungkidul|Paliyan','Gunungkidul|Panggang','Gunungkidul|Patuk','Gunungkidul|Playen','Gunungkidul|Ponjong',
'Gunungkidul|Purwosari','Gunungkidul|Rongkop','Gunungkidul|Saptosari','Gunungkidul|Semanu','Gunungkidul|Semin',
'Gunungkidul|Tanjungsari','Gunungkidul|Tepus','Gunungkidul|Wonosari',
'Kulon Progo|Galur','Kulon Progo|Girimulyo','Kulon Progo|Kalibawang','Kulon Progo|Kokap','Kulon Progo|Lendah',
'Kulon Progo|Nanggulan','Kulon Progo|Panjatan','Kulon Progo|Pengasih','Kulon Progo|Samigaluh','Kulon Progo|Sentolo',
'Kulon Progo|Temon','Kulon Progo|Wates',
'Sleman|Berbah','Sleman|Cangkringan','Sleman|Depok','Sleman|Gamping','Sleman|Godean','Sleman|Kalasan','Sleman|Minggir',
'Sleman|Mlati','Sleman|Moyudan','Sleman|Ngaglik','Sleman|Ngemplak','Sleman|Pakem','Sleman|Prambanan','Sleman|Seyegan',
'Sleman|Sleman','Sleman|Tempel','Sleman|Turi',
'Yogyakarta|Danurejan','Yogyakarta|Gedongtengen','Yogyakarta|Gondokusuman','Yogyakarta|Gondomanan',
'Yogyakarta|Jetis','Yogyakarta|Kotagede','Yogyakarta|Kraton','Yogyakarta|Mantrijeron','Yogyakarta|Mergangsan',
'Yogyakarta|Ngampilan','Yogyakarta|Pakualaman','Yogyakarta|Tegalrejo','Yogyakarta|Umbulharjo','Yogyakarta|Wirobrajan',
], 'DI Yogyakarta');

echo "Jawa Tengah & DIY done.\n";
